### ISSUE TITLE
v5.0.0-alpha.1-androidx 依赖的是Support包而非Androidx

### ISSUE THREAD

**Issue by Lowae** [Justson/AgentWeb#1002]
![image](https://user-images.githubusercontent.com/40293334/179442275-e4c0b1c8-87db-44ab-ab1f-d6fe73cc77d8.png)

AndroidX的依赖是不是搞错了？咋是support包呢
implementation 'com.github.Justson.AgentWeb:agentweb-core:v5.0.0-alpha.1-androidx' // (必选)

**Comment by OvenCroc** [comment]
大兄弟解决没得

**Comment by Lowae** [comment]
> 大兄弟解决没得

我直接自己重新打包了

**Comment by Justson** [comment]
```
 implementation 'com.github.Justson.AgentWeb:agentweb-core:v5.0.6-androidx' // (必选)
 implementation 'com.github.Justson.AgentWeb:agentweb-filechooser:v5.0.6-androidx' // (可选)
 implementation 'com.github.Justson:Downloader:v5.0.4-androidx'
```
