### ISSUE TITLE
自从更新到v5.0.0-alpha.1-androidx，有大量onReceivedError出错上报

### ISSUE THREAD

**Issue by BarretWu** [Justson/AgentWeb#1005]
如：ERR_NAME_NOT_RESOLVED

**Comment by Xxj-star** [comment]
已经停止维护更新了

**Comment by zhangxu2814** [comment]
<img width="454" alt="image" src="https://user-images.githubusercontent.com/8907295/187330255-3c3d64af-f283-4dba-8876-71a82f1cdff6.png">
        android:usesCleartextTraffic="true"
