### ISSUE TITLE
某些机型出现这种问题，不知道如何解决，希望大佬能给点思路。

### ISSUE THREAD

**Issue by jxpanda** [Justson/AgentWeb#1006]
#00 pc 0000000001f13008 /system/product/app/WebViewGoogle/WebViewGoogle.apk
#01 pc 0000000001f12ec4 /system/product/app/WebViewGoogle/WebViewGoogle.apk
java:
android.os.MessageQueue.next(MessageQueue.java:339)
android.os.Looper.loopOnce(Looper.java:186)
android.os.Looper.loop(Looper.java:334)
android.app.ActivityThread.main(ActivityThread.java:8399)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)

**Comment by dblr4287** [comment]
怎么解决的？

**Comment by kongnanlive** [comment]
解决办法就是crash率太小忽略不计
