### ISSUE TITLE
java.lang.NullPointerException  Attempt to invoke virtual method 'android.net.Uri com.just.agentweb.Action.getUri()' on a null object reference

### ISSUE THREAD

**Issue by lishangwl** [Justson/AgentWeb#1012]
[#50015 java.lang.NullPointerException](https://bugly.qq.com/v2/crash-reporting/crashes/54d008ba72/50015?pid=1)
Attempt to invoke virtual method 'android.net.Uri com.just.agentweb.Action.getUri()' on a null object reference
com.just.agentweb.AgentActionFragment.void onActivityResult(int,int,android.content.Intent)(AgentActionFragment.java:144)

**Comment by Justson** [comment]
implementation 'com.github.Justson.AgentWeb:agentweb-core:v5.0.6-androidx' // (必选)
 implementation 'com.github.Justson.AgentWeb:agentweb-filechooser:v5.0.6-androidx' // (可选)
 implementation 'com.github.Justson:Downloader:v5.0.4-androidx'
