### ISSUE TITLE
账号密码自动填充

### ISSUE THREAD

**Issue by zhoukp616** [Justson/AgentWeb#1015]
原生WebView是支持账号密码自动的填充的，使用AgentWeb后webView就不支持了。即使自己setWebView(webView)设置了自定义webView也不支持。这个是有开关吗？

**Comment by wangjian-k** [comment]
老哥用遇到cacheMode=load_default但是缓存不生效的问题吗

**Comment by xiexindev** [comment]
以前是直接savePassword(true)就行, 后来说这个不安全, 因为WebView是明文保存在数据库里面的, 所以标记过时了, 新版本就不再支持自动保存密码了.  这不是框架问题, 而是WebView本身就不支持了.
