### ISSUE TITLE
文件选择器（相册）在申请权限的时候没走权限拦截方法

### ISSUE THREAD

**Issue by a272312970** [Justson/AgentWeb#1019]
调查代码中发现，调用相机权限的时候，正常调用了权限拦截PermissionInterceptor的方法，但是在调用fileChooser的时候并没有调用mPermissionInterceptor.intercept方法，导致在监听中监听不到申请存储权限的回调

**Comment by LXLYHM** [comment]
v5.1.1-androidx最新版本遇到同一问题+1咋解决的？

**Comment by LXLYHM** [comment]
咋关闭了？demo运行在安卓10的手机也有这个问题，请问怎么解决的？
