### ISSUE TITLE
键盘遮挡输入框，输入框不自动上移

### ISSUE THREAD

**Issue by michaelrepo** [Justson/AgentWeb#1021]
新建了一个普通WebView就没问题，用AgentWeb就不行。

**Comment by michaelrepo** [comment]
Sorry！和此库无关。
使用了ImmersionBar这个库，它默认把键盘和输入框移动给关了，打开就好了。

**Comment by Soltus** [comment]
在 webview 中呼出键盘过程会有黑色区域，不够丝滑，有没有解决办法
