### ISSUE TITLE
集成了com.alipay(支付宝;阿里乘车码;阿里芝麻信用实名认5证;芝麻认证)等SDK

### ISSUE THREAD

**Issue by lzy0016** [Justson/AgentWeb#1026]
在华为上架的时候审核会因为集成了com.alipay(支付宝;阿里乘车码;阿里芝麻信用实名认5证;芝麻认证)等SDK导致不通过，具体是AgentWeb里依赖了alipaySdk-20180601.jar这个jar包

**Comment by lzy0016** [comment]
![alipay](https://user-images.githubusercontent.com/9514526/208391000-5eef841a-b4a8-45bf-99b6-974b03473094.png)

**Comment by JayceG** [comment]
我调用了  .closeWebViewClientHelper() ，好像可以避免初始化这些，但是又触发了 加载传感器之类的逻辑
