### ISSUE TITLE
拍照和文件选择问题

### ISSUE THREAD

**Issue by jpchenghub** [Justson/AgentWeb#1029]
您好， 问下AgentWeb最新版本支持拍照和选择文件默认只是拍照或者选择文件，现在好像默认是让用户选择相机或文件，但是我的需求是只需要拍照不需要暴露文件选项！

**Comment by lx1549181884** [comment]
mAgentWeb = AgentWeb.with(this)
                .setAgentWebParent()
                .useDefaultIndicator()
                .setAgentWebUIController(new AgentWebUIControllerImplBase(){
                    @Override
                    public void onSelectItemsPrompt(WebView view, String url, String[] ways, Handler.Callback callback) {
                        // 拦截拍照和选择文件，自定义代码可参考 super.onSelectItemsPrompt
                    }
                })
                .createAgentWeb()
                .go(getUrl());

**Comment by LXLYHM** [comment]
.setAgentWebUIController(object : AgentWebUIControllerImplBase() {
                override fun onSelectItemsPrompt(view: WebView, url: String, ways: Array<String>, callback: Handler.Callback) {
                    // 拦截拍照和选择文件，只需要拍照
                    if (callback != null) {
                        val mMessage = Message.obtain()
                        mMessage.what = 0 //mMessage.what 必须等于ways的index
                        callback.handleMessage(mMessage) //最后callback一定要回调
                    }
                }
            })
只让用户跳转相册，但是还是会弹出读取文件的权限怎么解决？

**Comment by liuxuesong001** [comment]
![Image](https://github.com/user-attachments/assets/54d4cbbb-117a-438c-a4c4-7bf6dda77338) 
好像不行，存储权限是默认申请的吧？
