### ISSUE TITLE
我想使用Android本地方法传递给Js一个很大的参数（图片的Base64）有提供方法实现么？

### ISSUE THREAD

**Issue by FmrChina** [Justson/AgentWeb#103]
在Simple中 传递图片mAgentWeb.uploadFileResult(requestCode, resultCode, data);  这个方法要求data（也就是onActivityResult() 中的Intent）必须不为null，但是很多手机这个data是为null的，我现在为了兼容自己获取到了一个file，想把这个file传给Js能实现么？

**Comment by Justson** [comment]
将文件转字符串？

**Comment by FmrChina** [comment]
就是图片转成Base64的字符串.. 可能我没有描述清楚，发现图片过大js方法就不会调用了。

**Comment by FmrChina** [comment]
库里的方式是把图片上传至js，但是这样做很多国产机子，经常拍照返回的data为null，所以这种方式兼容性并不好用，我就想把图片转成Base64通过参数传递过去，然后就出现js方法不调用，这应该是WebView的显示，而不是库的原因。

**Comment by FmrChina** [comment]
库里的方式是把图片上传至js，但是这样做很多国产机子，经常拍照返回的data为null，所以这种方式兼容性并不好，我就想把图片转成Base64通过参数传递过去，然后就出现js方法不调用，这应该是WebView的问题，而不是库的问题。

**Comment by Justson** [comment]
只要用户选择了图片data就不会为`null` ， `AgentWeb 2.0.0` 已经废弃该方法了。 还有我这边测试下了， 5M 图片转成字符串传给Js目前来说没发现问题 ， 当然这中间文件转化比较耗时， 最好还是走系统方法Uri回传 。

**Comment by FmrChina** [comment]
····那我猜测是不是和手机性能有关，我使用的是htc m9 一个100+ kb的图片都需要先把字符串转成json对象才能拿到，当用到1mb的图片的时候 js方法确实是没用调用的。

**Comment by FmrChina** [comment]
我看了下源码，最终也是调用的WebView原生的方法，所以我觉得这和这个库没有关系了~

**Comment by FmrChina** [comment]
现在我这边解决办法是先把图片上传至服务器，然后html再去服务器拿，我返回给html的只是一个服务器链接 - -！

**Comment by FmrChina** [comment]
这个问题是在我没看源码情况下提出的，不算这个库的问题，你现在可以关闭这个issues了。
