### ISSUE TITLE
在系统4.4.4的情况下，报错

### ISSUE THREAD

**Issue by CCTV-11** [Justson/AgentWeb#1035]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.genius.watch.main/com.genius.watch.main.ui.activity.web.AgentWebActivity}: android.util.AndroidRuntimeException: java.lang.ClassNotFoundException: com.android.webview.chromium.WebViewChromiumFactoryProvider

  Caused by: java.lang.ClassNotFoundException: com.android.webview.chromium.WebViewChromiumFactoryProvider

怎么处理？

**Comment by yuandoudou928** [comment]
捉。CCTV11 ？？适配4.4.4吗还要，哈哈
