### ISSUE TITLE
腾讯tbs文档能力开始收费了，谁有什么好的替代方案推荐么

### ISSUE THREAD

**Issue by hanqingkai** [Justson/AgentWeb#1043]
腾讯tbs文档能力开始收费了，谁有什么好的替代方案推荐么
![image](https://github.com/Justson/AgentWeb/assets/9988660/be66985f-27f4-44b0-ae71-5fbe27f54b00)

**Comment by duan759968124** [comment]
您好，找到好的方案了吗？遇到了同样的问题

**Comment by hanqingkai** [comment]
让服务端大佬处理吧，webview打开

**Comment by Justson** [comment]
PDFViewer
