### ISSUE TITLE
返回无反应

### ISSUE THREAD

**Issue by Biekangdong** [Justson/AgentWeb#1047]
@Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (keyCode == KeyEvent.KEYCODE_BACK) {
            if (agentWeb.getWebCreator().getWebView().canGoBack()) {
                agentWeb.getWebCreator().getWebView().goBack();
                return true;
            }

            finish();
        }
        return super.onKeyDown(keyCode, event);
    }

https://github.com/Justson/AgentWeb/assets/13655207/9a058c5b-0cd5-4103-8fe3-61b5b92181f5

**Comment by amisd** [comment]
解决了吗

**Comment by duan759968124** [comment]
解决了吗？canGoBack()一直返回false，并且调用goback无反应。
