### ISSUE TITLE
关于H5页面请求过多，导致Webviiew打不开的问题 

### ISSUE THREAD

**Issue by budaowengd** [Justson/AgentWeb#1058]
请帮忙分析下下面问题：
比如： 首页有2个Fragment，分别是A和B，都是Webview布局，显示A页面时，发送了2000个请求，每个请求的超时时间是5分钟，这时由于服务器问题，请求一直在处理中，A页面在等待。
这时，我点击B，B页面也有10个请求，这10个请求所在的服务器和A页面是不同的，只要请求，服务器会立马返回结果， 理论上B页面会立马显示，但是。。。

问题：B页面一直卡着，页面显示空白，现在也不知道B页面请求是否发送了，用户就是反馈B页面打不开，我们已经确认A页面服务器确实是有问题的，B页面的服务器是正常的。

请问是什么原因导致B页面无法显示数据的？
<img width="836" alt="image" src="https://github.com/Justson/AgentWeb/assets/16216657/11a3bf8e-d92b-4c32-9170-b910930cff2e">

**Comment by Justson** [comment]
chrome://inspect 自行分析下白屏的原因

**Comment by budaowengd** [comment]
> chrome://inspect 自行分析下白屏的原因

线上用户通过视频反馈的，本地没有测试出来。请问Juston你认为可能会有哪些原因造成？
