### ISSUE TITLE
ScrollView中加载不出来 类似淘宝的那种

### ISSUE THREAD

**Issue by xiang473535976** [Justson/AgentWeb#107]
ScrollView中  webview加载不出来   他的包裹器  必须制定高度才行

**Comment by xiang473535976** [comment]
应该是加载成功了 只是因为包裹器 没有高度了  没有显示出来    手动给包裹器设个死高度 就行

**Comment by Justson** [comment]
`AgentWeb`  的宽高由
```
setAgentWebParent((ViewGroup) view, new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT))//
```
 决定

**Comment by xiang473535976** [comment]
ViewGroup, LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT)   在ScrollView会看不见网页  
用 LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT)   只能铺满剩余屏幕大小 没法上下滑动

**Comment by xiang473535976** [comment]
@Justson   这个问题怎么处理啊    我这个和淘宝的一样的    肯定不能固定死高度啊

**Comment by Justson** [comment]
Google 不建议使用`ScrollView`嵌套 `WebView` ，`AgentWeb` 本身对事件没做处理 。

**Comment by xiang473535976** [comment]
我ScrollView嵌套 一个原生的WebView  就能显示出来   你i那个只能固定死高度才能显示出来
因为是商品详情页面 高度肯定不能固定死 
![6u 8oax8 4 vxz_ w m 0](https://user-images.githubusercontent.com/18111614/30797592-2aff8700-a209-11e7-8c85-96e049d6f40f.png)

**Comment by xiang473535976** [comment]
![6u 8oax8 4 vxz_ w m 0](https://user-images.githubusercontent.com/18111614/30797619-3ed6509c-a209-11e7-85b3-5c005d78348e.png)

**Comment by xiang473535976** [comment]
@Justson

**Comment by Justson** [comment]
如果`setAgentWebParent `传入的是`ScrollView`，那么你的布局层级是这样的 `ScrollView->FrameLayout->WebView`，， 你可以自定义` WebLayout `改成` FrameLayout->ScrollView->WebVIew`

**Comment by xiang473535976** [comment]
The specified child already has a parent. You must call removeView() on the child's parent first.
setAgentWebParent传入的是ScrollView   里面包含了一个webview  然后   .setWebView(wbview)
就报错了 @Justson

**Comment by xiang473535976** [comment]
ScrollView  中加了AgentWeb  没法滑动的 @Justson   请解决哈这个问题    谢谢
