### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by wanmeiwl** [Justson/AgentWeb#111]
建议接入腾讯X5内核for浏览器！
这样的话，什么全屏播放啥的全部好解

**Comment by wanmeiwl** [comment]
哈哈哈  小白一个 看看源码学习学习哈哈

**Comment by wanmeiwl** [comment]
https://x5.tencent.com/

**Comment by Justson** [comment]
![AgentWebX5](https://github.com/Justson/AgentWebX5)
