### ISSUE TITLE
是否可以更换webview

### ISSUE THREAD

**Issue by tyousyuka** [Justson/AgentWeb#12]
webview是否可以通过传入实现，比如腾讯的x5，性能相比原生webview好一点

**Comment by Justson** [comment]
支持定义 `WebView` 传入 ， 但必须是 `android.webkit.WebView` 类或者子类 ，腾讯的`com.tencent.smtt.sdk.WebView` 是继承于 FrameLayout ， 所以暂时没办法支持 腾讯的 `WebView`  。

**Comment by tyousyuka** [comment]
@Justson 希望后期可以支持一下，毕竟原生的webview性能不太好，bug也多的

**Comment by Justson** [comment]
感谢你的建议 。

**Comment by EvlinLee** [comment]
同样喜欢能更换webview，现在很多都直接用腾讯X5了。

**Comment by BolexLiu** [comment]
@Justson  请问一下那么到底如何传入一个自定义后的WebView呢？特殊场景确实要改动WebView
