### ISSUE TITLE
Agentweb怎么清空历史记录呢.

### ISSUE THREAD

**Issue by kangjinwen** [Justson/AgentWeb#128]
webView=mAgentWeb.getWebCreator().get();

//点击首页按钮 执行
mAgentWeb.getLoader().loadUrl(getUrl());
//加载首页后清除历史记录
webview.clearHistory;

这样清空历史记录后,按返回,还能返回之前加载的历史网址.
我想实现的是点击跳转首页后,按返回就停留在首页页面.
因为登录记录了cookies,所有不能执行mAgentWeb.clearWebCache();

**Comment by Justson** [comment]
`mAgentWeb.getWebCreator().get()`拿到WebView
