### ISSUE TITLE
下载文件为APK时，回调执行安装缺乏权限

### ISSUE THREAD

**Issue by jk25084** [Justson/AgentWeb#134]
目前下载目录无法设置？默认存储位置无法执行安装等操作，不知道也没有办法？

**Comment by Justson** [comment]
下载路径无法设置
```
String dir = getDiskExternalCacheDir(context);
File mFile = new File(dir, FILE_CACHE_PATH);
```

**Comment by jk25084** [comment]
因为默认路径在android 7.0有权限限制，下载APK文件完成，回调函数里面如果调用安装程序，安装界面会弹出来，但点安装会报找不到文件

**Comment by adymilk** [comment]
@Justson 该类对外是不开放的？用不了

**Comment by Justson** [comment]
`AgentWebUtils`本身不在设计API范围内。 如果确实需要，`getCommonFileIntentCompat`可以考虑自己拷贝一下源码出来也是很简单的，或者反射(不建议)。
