### ISSUE TITLE
加载bug

### ISSUE THREAD

**Issue by zds-github** [Justson/AgentWeb#137]
红米note1 在fragment AgentWeb加载网页时底部会消失

**Comment by Alex861** [comment]
导航切换fragment？我的也是，fragment加载网页，当切换过去的时候导航会闪一下消失，然后网页加载完成又出现了，只是第一次会出现，初始后再切换就不会了，原来使用webview没这个问题，看了半天不知道为啥，莫名其妙。。。。。

**Comment by Justson** [comment]
关闭硬件加速。
