### ISSUE TITLE
请问：怎么在H5中使用js调用java？？window.android.callAndroid()就这一句吗？？

### ISSUE THREAD

**Issue by Y-JH** [Justson/AgentWeb#140]
请问一个问题：
我按照作者的指示操作，
//Android 端 ， AndroidInterface 是一个注入类 ，里面有一个无参数方法：callAndroid 
mAgentWeb.getJsInterfaceHolder().addJavaObject("android",new AndroidInterface(mAgentWeb,this));
//在 Js 里就能通过 
window.android.callAndroid() //调用 Java 层的 AndroidInterface 类里 callAndroid 方法

目的使用js调用我的java代码。但是我同事使用window.android.callAndroid()在H5中找不到方法，无法完成调用。是不是需要H5做一些什么操作才能行？？
我的java代码是这样的：
public class AndroidInterface {

    private Handler deliver = new Handler(Looper.getMainLooper());
    private AgentWeb agent;
    private Context context;
    private ICallAndroidListener listener;

    public AndroidInterface(AgentWeb agent, Context context, ICallAndroidListener listener) {
        Toast.makeText(context.getApplicationContext(), "AndroidInterface" , Toast.LENGTH_LONG).show();
        this.agent = agent;
        this.context = context;
        this.listener = listener;
    }

    @JavascriptInterface
    public void callAndroid(final String msg) {
        deliver.post(new Runnable() {
            @Override
            public void run() {
                Toast.makeText(context.getApplicationContext(), "" + msg, Toast.LENGTH_LONG).show();

                listener.onAndroidCallbackListener();
            }
        });

    }
}

Activity中

 mAgentWeb = AgentWeb.with(this)//
                .setAgentWebParent(reWebContainer, new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT))//传入AgentWeb的父控件
                .useDefaultIndicator()
                .defaultProgressBarColor()
                .setAgentWebSettings(WebDefaultSettingsManager.getInstance())//设置 AgentWebSettings
                .setWebViewClient(mWebViewClient)//WebViewClient ， 与WebView 一样
                .setWebChromeClient(mWebChromeClient) //WebChromeClient
//                .setPermissionInterceptor(mPermissionInterceptor) //权限拦截
                .setReceivedTitleCallback(mCallback)//标题回调
                .setSecutityType(AgentWeb.SecurityType.strict) //严格模式
//                .addDownLoadResultListener(mDownLoadResultListener) //下载回调
//                .openParallelDownload()//打开并行下载 , 默认串行下载
//                .setNotifyIcon(R.mipmap.download)
                .createAgentWeb()//创建AgentWeb
                .ready()//设置 WebSettings
                .go(H5_Url); //WebView载入该url地址的页面并显示。

//在这里进行 H5 对 Android原生的调用
    private void jsAndroid() {
        //Android 端 ， AndroidInterface 是一个注入类 ，里面有一个无参数方法：callAndroid
        mAgentWeb.getJsInterfaceHolder().addJavaObject("android", new AndroidInterface(mAgentWeb, this, new ICallAndroidListener() {
            @Override
            public void onAndroidCallbackListener() {
                //关闭activity
                finish();
            }
        }));
    }

**Comment by Y-JH** [comment]
我同事在H5的js中对一个按钮做监听，然后调用了那一行代码。但是不管用，没有任何反应。。。。请问怎么解决的？？

**Comment by Justson** [comment]
'Sample' 点击事情能正常响应吗？

**Comment by wonxll** [comment]
最后是怎么回事啊？我的也是这样，没有用，提示Undifined

**Comment by sooner0493** [comment]
这问题就直接关闭了？搞笑？

**Comment by flyzend** [comment]
。。。。我特么看了半天，没有下文

**Comment by Kylewwb** [comment]
同问，怎么解决的?

**Comment by BeforeFuture** [comment]
> 
> 
> 我同事在H5的js中对一个按钮做监听，然后调用了那一行代码。但是不管用，没有任何反应。。。。请问怎么解决的？？

因为你的callAndroid 方法是有参数的，他h5掉用你的callAndroid 没有传参数，所以方法对不上，当然调用不了了。

**Comment by BeforeFuture** [comment]
> 
> 
> 同问，怎么解决的?


因为你的callAndroid 方法是有参数的，他h5掉用你的callAndroid 没有传参数，所以方法对不上，当然调用不了了。

**Comment by BeforeFuture** [comment]
> 
> 
> 。。。。我特么看了半天，没有下文


因为你的callAndroid 方法是有参数的，他h5掉用你的callAndroid 没有传参数，所以方法对不上，当然调用不了了。
