### ISSUE TITLE
崩溃了，请看看描述

### ISSUE THREAD

**Issue by qq1458740677** [Justson/AgentWeb#141]
java.lang.RuntimeException:Unable to start activity ComponentInfo{per.xjx.notepad/com.just.library.ActionActivity}: java.lang.NullPointerException: Attempt to read from field 'int com.just.library.ActionActivity$Action.action' on a null object reference

**Comment by Justson** [comment]
系统版本 ， 手机信息 ，在什么情况下触发的异常， 最好链接也发一下 。

**Comment by qq1458740677** [comment]
截图：
[http://note.youdao.com/noteshare?id=8c29f908c4e60a0e187f47e645243d24&sub=67613C6B65984D3E898A3636495DF4D0](url)

我的应用根本就没有调用ActionActivity这个类，崩溃信息是别的用户手机上的崩溃日志，我觉得是不是杀毒软件在检测应用启动这个类了，导致崩溃。

**Comment by Justson** [comment]
看不到你的截图 。

**Comment by qq1458740677** [comment]
复制地址，在浏览器上打开，直接点好像github会跳到404，不行加个wechat发给你吧！

**Comment by Justson** [comment]
如果外部启动 `ActiongAtivity` 该类 ， 没有传 `KEY_ACTION` 的话， 确实会报错 。

**Comment by qq1458740677** [comment]
是的，我的应用没用过这个类，我都不知道有这个类，只用了AgentWeb这个类，那么就奇怪了。还是希望处理一下这种状况吧，估计是安全软件的沙箱检测或者是人为破解。

**Comment by Justson** [comment]
一般来说，不会出现你所说的问题， 因为`ActionActivity`对外是不开放的， 也就是说 `exported=false` 外部是无法启动的 ， 除非你在  `manifest` 里面重复声明 `exported=true` 或者加上` intent-filter` 。
