### ISSUE TITLE
看你写的挺简单的，可是实在用不起来啊

### ISSUE THREAD

**Issue by WangLei20167** [Justson/AgentWeb#144]

**Comment by WangLei20167** [comment]
mAgentWeb = AgentWeb.with(this)//传入Activity or Fragment
                .setAgentWebParent(mLinearLayout, new LinearLayout.LayoutParams(-1, -1))//传入AgentWeb 的父控件 ，如果父控件为 RelativeLayout ， 那么第二参数需要传入 RelativeLayout.LayoutParams ,第一个参数和第二个参数应该对应。
                .useDefaultIndicator()// 使用默认进度条
                .defaultProgressBarColor() // 使用默认进度条颜色
                .setReceivedTitleCallback(mCallback) //设置 Web 页面的 title 回调
                .createAgentWeb()//
                .ready()
                .go("http://www.jd.com");

//这一段  之前的代码该怎么写  大神能不能把文档写的详细些

**Comment by Justson** [comment]
看看`Sample` ， 谢谢
