### ISSUE TITLE
java.lang.UnsatisfiedLinkError:dlopen failed: "/data/app/com.google.android.webview-1/lib/arm/libwebviewchromium.so" is 32-bit instead of 64-bit

### ISSUE THREAD

**Issue by GongZiZhang** [Justson/AgentWeb#154]
java.lang.UnsatisfiedLinkError:dlopen failed: "/data/app/com.google.android.webview-1/lib/arm/libwebviewchromium.so" is 32-bit instead of 64-bit

**Comment by dicallc** [comment]
我也发生了这个问题，主要是华为机器一启动就会崩溃

**Comment by andy91310** [comment]
这个应该是需要添加ndk
