### ISSUE TITLE
Android5.1以上点击相机报错。Android5.0以下正常

### ISSUE THREAD

**Issue by zhangeq** [Justson/AgentWeb#156]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=596, result=0, data=null} to activity {cn.wbiao.wbmjapp/com.just.library.ActionActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.just.library.ActionActivity$FileDataListener.onFileDataResult(int, int, android.content.Intent)' on a null object reference；

**Comment by Justson** [comment]
没加相机权限
