### ISSUE TITLE
指定系统语言，使用此lib加载web后关闭此activity语言又切回成跟随系统语言

### ISSUE THREAD

**Issue by yudehai0204** [Justson/AgentWeb#158]
指定系统语言，使用此lib加载web后关闭此activity语言又切回跟随系统语言
比如我系统是中文  第一个页面指定app使用英语 跳转web页面 关闭webactivtiy 后 其他页面语言变成了系统语言中文。

**Comment by JeremyMing** [comment]
解决这个问题了吗
