### ISSUE TITLE
是否支持调用返回值呢?

### ISSUE THREAD

**Issue by tututututututu** [Justson/AgentWeb#16]
Js调用Android 后Android返回数据给js
或者android 调用js后js返回数据给Android 
https://github.com/lzyzsd/JsBridge
如上这个库提供这样的功能

**Comment by Justson** [comment]
暂时不支持哦

**Comment by Justson** [comment]
`Android 4.4` 以上支持 Js 返回数据 。

**Comment by Justson** [comment]
#24
