### ISSUE TITLE
 java.lang.NoSuchMethodError: android.webkit.WebSettings.setAllowUniversalAccessFromFileURLs

### ISSUE THREAD

**Issue by williamsswl** [Justson/AgentWeb#175]
AndroidRuntime | java.lang.NoSuchMethodError: android.webkit.WebSettings.setAllowUniversalAccessFromFileURLs
at com.just.library.WebDefaultSettingsManager.settings(WebDefaultSettingsManager.java:78)
at com.just.library.WebDefaultSettingsManager.toSetting(WebDefaultSettingsManager.java:37)
at com.just.library.AgentWeb.ready(AgentWeb.java:292)
at com.just.library.AgentWeb.access$5700(AgentWeb.java:41)
at com.just.library.AgentWeb$PreAgentWeb.ready(AgentWeb.java:520)

小米 小米MI-ONE Plus  操作系统 | android 4.0.4 (SDK 版本：15)

**Comment by Justson** [comment]
非常感谢你的反馈。
