### ISSUE TITLE
加载https网页不显示

### ISSUE THREAD

**Issue by Alex861** [Justson/AgentWeb#179]
加载https网页不显示

**Comment by Alex861** [comment]
解决了
setWebViewClient(new WebViewClient() {
                        @Override
                        public void onReceivedSslError(WebView view, SslErrorHandler handler, SslError error) {
                            handler.proceed();
                        }
                    })

**Comment by a8453770** [comment]
根本就没有回调这个方法

**Comment by a8453770** [comment]
android 4.4 设备以下 部分https 网页打不开,应该是系统的问题,换使用tencent x5浏览器是可以的

**Comment by Alex861** [comment]
public CommonAgentBuilder setWebViewClient(@Nullable WebViewClient webViewClient) {
            this.mAgentBuilder.mWebViewClient = webViewClient;
            return this;
        }
这不是？不换内核，加上这个，https一样打开(android4.0模拟器测试OK)，还有作者各种builder让人头晕。。。。顺序错了都加不上

**Comment by a8453770** [comment]
好的 多谢,,我再试试
