### ISSUE TITLE
请问怎么调用 setOnTouchListener 等事件

### ISSUE THREAD

**Issue by GitHubAFeng** [Justson/AgentWeb#18]
如题，我想处理上拉下拉滑动事件，点不出来 setOnTouchListener

**Comment by GitHubAFeng** [comment]
尝试了下，似乎是 
mAgentWeb.getWebCreator().get();

**Comment by Justson** [comment]
是的 ， 通过 mAgentWeb.getWebCreator().get(); 得到 WebView .
