### ISSUE TITLE
为什么用了有的页面用了agentweb之后，在跳转另一个用了webview的页面加载不出来东西？

### ISSUE THREAD

**Issue by liujing0824** [Justson/AgentWeb#180]
比如：
activityB里面单独用到一个webview，加载页面成功。
然后，返回在去点击 activityA，里面单独用到一个agentWeb加载页面，可以加载成功。
然后在返回点击activityb,b页面无法加载成功。

**Comment by Justson** [comment]
B页面`mWebview.resumeTimers()`

**Comment by liujing0824** [comment]
@Justson 非常感谢!
