### ISSUE TITLE
部分接口设计不合理

### ISSUE THREAD

**Issue by zhouzhiyong619** [Justson/AgentWeb#183]
1、ready()返回的是PreAgentWeb，这个时候无法获取webview修改相关设置如UserAgent
2、无法自定义Settings，在AgentWeb#ready时候强制检查是否是WebDefaultSettingsManager，如果不是则mWebListenerManager为空，无法设置WebviewClient。代码如下：
        if (mWebListenerManager == null && mAgentWebSettings instanceof WebDefaultSettingsManager) {
            mWebListenerManager = (WebListenerManager) mAgentWebSettings;
        }
3、Download通知栏样式无法修改。

**Comment by Justson** [comment]
### 问题一 ,问题二，通过自定义`Settings `设置`UserAgent`
```
public class CustomSettings extends WebDefaultSettingsManager {
    protected CustomSettings() {
        super();
    }


    @Override
    public AgentWebSettings toSetting(WebView webView) {
        super.toSetting(webView);
        getWebSettings().setBlockNetworkImage(false);//是否阻塞加载网络图片  协议http or https
        getWebSettings().setAllowFileAccess(false); //允许加载本地文件html  file协议, 这可能会造成不安全 , 建议重写关闭
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
            getWebSettings().setAllowFileAccessFromFileURLs(false); //通过 file url 加载的 Javascript 读取其他的本地文件 .建议关闭
            getWebSettings().setAllowUniversalAccessFromFileURLs(false);//允许通过 file url 加载的 Javascript 可以访问其他的源，包括其他的文件和 http，https 等其他的源
        }
        
        return this;
    }
}
```
### 问题三
首先必须承认 ， 在UI设计有缺陷 ，因为当时设计想法 ，尽量减少界面的出现 ， 但是整个工程还是有不少地方出现于用户交互 ，将出现必要交互的界面都写在`DefaultWebClient` 和 `DefaultChromeClient`里面 ， 唯一修改的方式就是通过重写 `WebViewClient` 或者`WebChromeClient`相对应的方法来覆盖 （下个版本会改善该问题），通知栏用的是系统的样式 ， 比较简单 ， 只有一个`icon`并提供了 API 配置 。

### 感谢
`AgentWeb` 还存在很多地方不足 ，感谢你们每一个人的反馈 。
