### ISSUE TITLE
recyclerview 里嵌套agentWeb,加载长图报错

### ISSUE THREAD

**Issue by zomll** [Justson/AgentWeb#190]
大佬，这个怎么解决？ 

java.lang.IllegalStateException: Unable to create layer for WebView, size 1440x33124 exceeds max size 8192

**Comment by zomll** [comment]
找到原因了，
这个错误是由于webview在scrollview里设置成了wrap_content，导致webview不确定大小，而且webview启动了硬件加速，由于硬件加速是有个最小的缓存区域的，最终导致超过了缓存范围。 
解决方法： 
webView.setLayerType(View.LAYER_TYPE_NONE, null); 
关闭硬件加速即可，也不能使用软件加速

希望可以帮到出现同样问题的朋友

**Comment by tanzhixue** [comment]
能贴一下代码怎么设置么 ？

**Comment by 18826243441m** [comment]
@zomll 兄弟,你的界面recycleview嵌套webview不会导致webview显示不全的问题?
