### ISSUE TITLE
在一个activity中进行多个Fragment切换，只能显示第一个默认的Fragment网页内容

### ISSUE THREAD

**Issue by Y-JH** [Justson/AgentWeb#196]
您好，请问：在一个activity中进行多个Fragment切换，只能显示第一个默认的Fragment网页内容，这种情况怎么解决？
private String H5_Url = "http://192.168.10.236:82/wap-1.0/index-m2.html";
private String H5_Url = "http://192.168.10.236:82/wap-1.0/my.html";
private String H5_Url = "http://192.168.10.236:82/wap-1.0/ticket.html";

我在一个 activity 中new 了三个 fragment 进行切换（上面是url），但是就是第一个默认的显示，其他都是空白。然后我把第二个fragment 的h5的url换成csdn的地址，可以显示，但是我把我的第二个url放到浏览器，浏览器也是可以显示的。这个问题好奇怪，请作者帮忙解答一下！谢谢

**Comment by Y-JH** [comment]
这三个页面的切换，我使用的是 hide() 和 show() 方法实现的

**Comment by Justson** [comment]
` mAgentWeb.getWebLifeCycle().onPause()`去掉，如果还不显示， 那就是 Fragment 基本使用问题了。

**Comment by Y-JH** [comment]
问题已经找到，不过没有试作者的方案；
我的方案是，之前使用的hide()和show()显示，进行fragment 的切换，四个页面有三个不会显示。
然后经过多次的尝试，发现，使用viewpager 内嵌fragment 进行切换，问题就解决了！！
再次谢谢作者！
