### ISSUE TITLE
setAgentWebParent()无意间传了个null进去，导致其他布局都不显示了

### ISSUE THREAD

**Issue by aengui** [Justson/AgentWeb#197]
效果如标题所说。经过一番波折，最后发现源码中对null进行了处理，位置在com/just/library/DefaultWebCreator.java:106。大致意思是说，如果你传了一个null的ViewGroup进去，那么就把包含了WebView的FrameLayout当作contentView，所以你自己写的布局文件就不会显示了。
鄙人学艺不精，找到问题所在也花了许久。当然首要原因是我代码写的不好才传了null过去，其次作者这么处理的使用场景是啥，我至今未想明白，不过应该有其道理。如果这能算上一个特性的话，在使用说明里加个友情提示也是极好的。如果抛个空指针异常，也许瞬间就定位到错误代码了，当然我也不知道抛异常是不是合适。最后，以上纯属个人见解，希望能帮助到大家，同时也希望作者能够解除我的困惑。

**Comment by Justson** [comment]
如你所说，如果开发者想尽可能减少视图的层级，父控件可不传，我应该加载`Nullable`注解,非常感谢你的反馈。
