### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by wtt945482445** [Justson/AgentWeb#198]
在AgentWeb中加载高德地图无法捕获到对于的权限，百度的可以，请指教

**Comment by wtt945482445** [comment]
情况是这样的，我在6.0手机上高德地图定位无法提示申请权限对话框，拦截权限的方法无法捕获到，但是百度和百度地图都可以，能够给用户提示，
在6.0以下版本高德地图可以定位，没有问题，请帮我解释这个问题，我认为这可能是高德地图对用权限的把控更加严格于其他

**Comment by Justson** [comment]
你好 ， 高德地位需要集成高德SDK辅助定位，详细请查看[高德](http://lbs.amap.com/api/android-location-sdk/guide/android-location/assistant-location)

**Comment by wtt945482445** [comment]
非常感谢
