### ISSUE TITLE
无法与CoordinatorLayout结合使用.

### ISSUE THREAD

**Issue by qyliuyawei** [Justson/AgentWeb#207]
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <android.support.v4.widget.NestedScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:fillViewport="true">

        <FrameLayout
            android:id="@+id/web_fl"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

    </android.support.v4.widget.NestedScrollView>

    <include layout="@layout/global_framelayout" />

</android.support.design.widget.CoordinatorLayout>

布局如上所示,无法实现滑动联动,请问有解决办法吗?(<include layout="@layout/global_framelayout" />向下滑动)

**Comment by animus198656** [comment]
我也遇到这个问题，解决了吗？

**Comment by xingfude123** [comment]
https://github.com/Tijn1314/NestedScrollWebView/blob/master/nestedscrollwebview/src/main/java/com/example/nestedscrollwebview/NestedScrollWebView.java,使用它可以更好的解决嵌套问题

**Comment by lyawei** [comment]
邮件已收到，我会仔细查阅。
