### ISSUE TITLE
网页的<selec>标签打不开   点了没反应

### ISSUE THREAD

**Issue by implistarry** [Justson/AgentWeb#21]
网页的<selec>标签打不开   点了没反应

**Comment by implistarry** [comment]
Ok了  你的readme有小坑啊

**Comment by Justson** [comment]
还请指出 ， 感谢

**Comment by implistarry** [comment]
我没有看到有写可以自己传WebView进去,还可以自定义。  

> AgentWeb 是一个高度封装的 Android WebView ，简单易用 ， 带有进度条 、 支持文件上传 、 下载 、 简化 Javascript 通信 、 链式调用 、 加强 Web 安全的库 。

看这个字面意思, 之前还以为里面用的是已经封装好了WebView  &settings,不能自定义的

**Comment by Justson** [comment]
谢谢反馈 ， 已经 fixed  select 标签无反应情况 。
