### ISSUE TITLE
Android8.0 notification

### ISSUE THREAD

**Issue by LeonShannon** [Justson/AgentWeb#211]
Android8.0
因为新的API,下载没有通知栏.
会有一个toast弹框,developer warning for package"包名"Failed to post notification on channel "null
see log for more details

**Comment by Justson** [comment]
截图，或者提供Gif说明下吗？ 使用的是 AgentWeb 最新版吗？

**Comment by LeonShannon** [comment]
Developer warning for package “xxx.xxx.xxx” 
Failed to post notification on channel “12345” 
See log for more details
![screenshot_20171229-115405](https://user-images.githubusercontent.com/24221796/34592501-75dcfa3c-f1ff-11e7-98d8-c764bba0af7a.jpg)
只有是最新版是这样,我在用2.0.1的时候是正常显示的
