### ISSUE TITLE
下载地址重定向，导致下载的文件不是需要的文件

### ISSUE THREAD

**Issue by zhuyulinliu** [Justson/AgentWeb#215]
声明我是新手。
      我用你的demo把一个url改为http://www.87lou.com，这是一个种子文件分享网站，下载的.torrent文件大小正常情况应该是几十kb, 但是用你的代码下载下来的每个.torrent文件都是6.18k ,显然下载的东西并不是最后需要的东西。
       我用手机自带的浏览器（华为手机），QQ浏览器下载都没有问题.
       我之前是使用原生的webView+DownloadManager在弄这个，和用你的代码问题一样，原因是下载的时候传给DownloadManager的url不是文件的绝对路径，并且那个url单独访问的时候的提示会未登录而不是去下载文件，我不知道怎么解决。
       还有一个小问题，我在你的代码里面找了很久都没找到设置文件下载路径的地方。（我可能眼瞎）

**Comment by Justson** [comment]
不是库的问题 ， issue 我关了。
