### ISSUE TITLE
自定义错误布局时为什么会出现页面默认的提示信息?(效果图如下, 附Demo链接)

### ISSUE THREAD

**Issue by imjackzhao** [Justson/AgentWeb#217]
![error](https://user-images.githubusercontent.com/20088500/34552251-60bf471c-f15b-11e7-8582-1865765742ec.png)

Demo链接(百度网盘): https://pan.baidu.com/s/1kVAFHQJ

**Comment by Justson** [comment]
` compile 'com.just.agentweb:agentweb:3.1.0-alpha'`
