### ISSUE TITLE
AgentWeb如何post请求url？

### ISSUE THREAD

**Issue by changshuai7** [Justson/AgentWeb#220]
如题，框架并未开放此接口。

**Comment by Justson** [comment]
` mAgentWeb.getLoader().postUrl();`

**Comment by changshuai7** [comment]
谢谢

**Comment by Justson** [comment]
不客气

**Comment by changshuai7** [comment]
楼主，还是没有实现post访问，能指导一下吗。
我执行AgentWeb初始化以后：
   mAgentWeb = AgentWeb.with(this)
                .setAgentWebParent((ViewGroup) view, new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT))
                .setIndicatorColorWithHeight(-1, 2)
                .setAgentWebWebSettings(getSettings())
                .setWebViewClient(mNABridgeWebViewClient)
                .setWebChromeClient(mWebChromeClient) //WebChromeClient
                .setPermissionInterceptor(mPermissionInterceptor) //权限拦截 2.0.0 加入。
                .setReceivedTitleCallback(mCallback)//标题回调。
                .setSecurityType(AgentWeb.SecurityType.strict) 
                .addDownLoadResultListener(mDownLoadResultListener)//下载回调
                .setMainFrameErrorView(R.layout.web_layout_error, -1) 
                .openParallelDownload()//打开并行下载 , 默认串行下载
                .setNotifyIcon(R.mipmap.download)
                .setOpenOtherPageWays(DefaultWebClient.OpenOtherPageWays.ASK)
                .interceptUnkownScheme() //拦截找不到相关页面的Scheme AgentWeb 3.0.0 加入。
                .createAgentWeb()//创建AgentWeb
                .ready()//设置 WebSettings
               .go(getUrl()); 

 mAgentWeb.getLoader().postUrl("http://www.qq.com",null);


go这个方法如何替换成postUrl呢？或者是用其他的方式？

**Comment by Justson** [comment]
```
go传入null ， 如go(null) ;
mAgentWeb.getLoader().postUrl("http://www.qq.com",null);
```

**Comment by juicelover** [comment]
需要更新了吧
go传入null ， 如go(null) ;
mAgentWeb.getUrlLoader().postUrl("http://www.qq.com",null);
