### ISSUE TITLE
此build模式中有太多的内部代理类，导致agentweb对象的很多功能被屏蔽了，建议好好整理一下

### ISSUE THREAD

**Issue by ZepLee** [Justson/AgentWeb#226]

**Comment by Justson** [comment]
比如说呢？

**Comment by ZepLee** [comment]
比如想获取Agentweb的对象必须走到go方法才行。中间的PreAgentWeb，CommonAgentBuilder，都没有很多方法，主要的方法又都在Agentweb类封装的，而很多前置设置都需要在go之前执行。

**Comment by ZepLee** [comment]
ready方法基本没有起到作用，ready的时候返回agentweb对象也可以吧？然后就可以在需要的时候在go（url）了

**Comment by Justson** [comment]
感觉 AgentWeb 有哪些地方设计不合理的， 欢迎 PR 过来哈。
