### ISSUE TITLE
没有提供webview的posturl方法

### ISSUE THREAD

**Issue by ZepLee** [Justson/AgentWeb#229]

**Comment by Justson** [comment]
`mAgentWeb.getLoader().postUrl();`

**Comment by ZepLee** [comment]
可否给个demo的链接呢，agentweb对象只有当执行了go方法之后才能获取到，go的时候已经跳转网页了，怎么再调用posturl呢

**Comment by Justson** [comment]
仓库里面的 `Sample`

**Comment by Justson** [comment]
`go("");`可以传入空值

**Comment by ZepLee** [comment]
还有这种操作，了解了

**Comment by ZepLee** [comment]
为什么不提供一个和go同级别的方法呢~，一般人实在找不到~

**Comment by ZepLee** [comment]
作者你好，如果使用go("")会直接跳转到一个白板，再次go（url）返回的时候会先返回到白板，怎么解决呢？
