### ISSUE TITLE
下载的异常

### ISSUE THREAD

**Issue by daiwuzhou** [Justson/AgentWeb#230]
java.lang.IllegalAccessError: Field 'android.support.v4.app.NotificationCompat$Builder.mNotification' is inaccessible to class 'com.just.library.Notify'

**Comment by Justson** [comment]
AgentWeb 版本

**Comment by daiwuzhou** [comment]
2.01

**Comment by Justson** [comment]
请升级下库 3.1.0

**Comment by daiwuzhou** [comment]
解决了，谢谢。那个下载提示底部的黑色的提示可以去掉么？

**Comment by Justson** [comment]
重写下`AgentWebUIController#showMessage`， 过滤一下就好了.
