### ISSUE TITLE
请问怎么使用chrome调试

### ISSUE THREAD

**Issue by chenghe** [Justson/AgentWeb#231]
这是我的初始化，发现Chrome无法调试JS页面，请问是什么配置没有设置吗？（是DEBUG版本）        

mAgentWeb = AgentWeb.with(this)//
                .setAgentWebParent(llWeb,
                        new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,
                                ViewGroup.LayoutParams.MATCH_PARENT))//传入AgentWeb的父控件
                .useDefaultIndicator()
                .setIndicatorColorWithHeight(-1, 2)//设置进度条颜色与高度-1为默认值，高度为2，单位为dp
                .setReceivedTitleCallback(mCallback)
                .setSecurityType(AgentWeb.SecurityType.strict) //严格模式
                .setMainFrameErrorView(R.layout.agentweb_error_page, -1)
                .openParallelDownload()//打开并行下载 , 默认串行下载
                .setNotifyIcon(R.mipmap.download) //下载图标
                .interceptUnkownScheme() //拦截找不到相关页面的Scheme
                .createAgentWeb()//创建AgentWeb
                .ready()//设置 WebSettings
                .go(url); //WebView载入该url地址的页面并显示

**Comment by Justson** [comment]
```java
if (Build.VERSION.SDK_INT >=Build.VERSION_CODES.KITKAT) {

            mAgentWeb.getWebCreator().getWebView().setWebContentsDebuggingEnabled(true);

 }
```

**Comment by cxl086** [comment]
```
if (Build.VERSION.SDK_INT >=Build.VERSION_CODES.KITKAT) {
           Web.setWebContentsDebuggingEnabled(true);
 }
```

setWebContentsDebuggingEnabled是static的，直接调用就行
