### ISSUE TITLE
加载页面之前如何设置websettings

### ISSUE THREAD

**Issue by wshx21** [Justson/AgentWeb#238]

**Comment by wshx21** [comment]
加载页面之前如何设置websettings

**Comment by wshx21** [comment]
settings.setDomStorageEnabled(true);

**Comment by wshx21** [comment]
老哥你的完全使用api 根本点不出来方法

**Comment by Justson** [comment]
[自定义 WebSettings](https://github.com/Justson/AgentWeb/wiki/WebSettings-%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AE%BE%E7%BD%AE)
