### ISSUE TITLE
如何支持callBack回掉呢？

### ISSUE THREAD

**Issue by Gaobz** [Justson/AgentWeb#24]

**Comment by Justson** [comment]
什么回调呢 ?

**Comment by Gaobz** [comment]
如jsBridge的回掉功能

**Comment by Justson** [comment]
暂时不支持哦 。

**Comment by Justson** [comment]
Android  4.4 以上支持 Js 返回数据  。

**Comment by ericktang** [comment]
就是如何实现这样的功能，比如扫描二维码，在Android有函数负责二维码扫描，扫描之后回调JS传入的函数，JS这样写：

`var scanQRCode = function(){
    window.android.scanQRCode(function(content){
          alert("扫描结果是："+content);
   });
}
`
在Android里面，这个函数该怎么写？

**Comment by cervy** [comment]
直接用webview加载JS

**Comment by ericktang** [comment]
webview不支持javascript的callback回调，真心是不好用。git搜索 JsBridge，版主能否参考一下集成进去啊。
