### ISSUE TITLE
input标签文件上传问题

### ISSUE THREAD

**Issue by main404** [Justson/AgentWeb#243]
input标签文件上传，文件管理器中部分图片获取不到（demo也获取不到），比如最近的图片获取不到。

**Comment by kairsath** [comment]
同样的问题 据了解是7.0权限原因

**Comment by main404** [comment]
你解决了吗 ？

**Comment by kairsath** [comment]
加我企鹅2832390607

**Comment by JamesLiAndroid** [comment]
@kairsath 你那边解决了吗？我这边也是，路径能读取，但是上传图片文件到页面的时候，发现不行

**Comment by androidflying** [comment]
同样的问题,红米 note3 6.0.1；
@Justson 求解决

**Comment by androidflying** [comment]
目前解决方案是修改源码：ActionActivity中realOpenFileChooser()方法

**Comment by Movement123** [comment]
我也遇到同样的问题

**Comment by LXLYHM** [comment]
我也遇到了同样问题，请问有人解决了吗？

**Comment by LXLYHM** [comment]
> 目前解决方案是修改源码：ActionActivity中realOpenFileChooser()方法

这个方法里面怎么改？能帮忙贴一下吗？
