### ISSUE TITLE
是否可以增加打开其他应用监听功能

### ISSUE THREAD

**Issue by EngrZhou** [Justson/AgentWeb#247]
是否可以增加`setOpenOtherPageWaysListener`功能，方便在离开时，宿主能及时知晓。
另建议`setOpenOtherPageWays(DefaultWebClient.OpenOtherPageWays.ASK)`时候，可以自定义Dialog样式

**Comment by Justson** [comment]
可以自定义`Dialog` ，详细请看`AgentWebUIController`

**Comment by EngrZhou** [comment]
@Justson 感谢，已经看到了，如此可以自己实现回调了。谢谢指点！

**Comment by EngrZhou** [comment]
你好，`DefaultWebClient.java`的第303-306行。
```java
        if (url.startsWith(INTENT_SCHEME)) { //Intent scheme
            handleIntentUrl(url);
            return true;
        }
```
这个 `intent:// `scheme不作为 跳转对话框弹框的标准是有意设计的吗？
```java
 private boolean handleOtherScheme(String url) {
      ...
 }
```
只有在调用除了`intent://` `weixin://wap/pay?` `alipays://`之外的scheme才做跳转弹窗提醒处理。
比如 `intent://play.app.goo.gl/?link=https://play.google.com/store/apps/details?id%3Dcom.com.android.chrome`
这个链接 同样是能打开GooglePlay的。但是这样打开GooglePlay的情况是没有进行弹窗拦截提醒的。
