### ISSUE TITLE
不支持直接加载一段html吗？必须是一个url?另外设置useragent 必须自己获取到webview 去设置吗？

### ISSUE THREAD

**Issue by tracybai7989** [Justson/AgentWeb#249]
如题，没找到怎么设置。

**Comment by tracybai7989** [comment]
不好意思  看到了

**Comment by zhaoren** [comment]
。。怎么设置useragent

**Comment by tracybai7989** [comment]
mAgentWeb.getAgentWebSettings().getWebSettings().setUserAgentString("agentweb");

https://open.weixin.qq.com/connect/oauth2/authorize?appid=wxc43a4974a9baf4f7&response_type=code&scope=snsapi_base&redirect_uri=https://m.exmail.qq.com/cgi-bin/login&state=@addr_mainpage#wechat_redirect

**Comment by tracybai7989** [comment]
mAgentWeb.getAgentWebSettings().getWebSettings().setUserAgentString("agentweb");

https://open.weixin.qq.com/connect/oauth2/authorize?appid=wxc43a4974a9baf4f7&response_type=code&scope=snsapi_base&redirect_uri=https://m.exmail.qq.com/cgi-bin/login&state=@addr_mainpage#wechat_redirect
---- 原始邮件 ----
