### ISSUE TITLE
agentWebx5 在4.3的三星机器上滑动卡顿

### ISSUE THREAD

**Issue by mAndroidNovice** [Justson/AgentWeb#250]
http://web.qukantianxia.com/showArticle/730727?token=9c531456c9f347a22835638e98de4d58&os=1&r=0.5941194248413867
这个是测试的连接
测试机型的信息: 型号: GT-N7102

**Comment by Justson** [comment]
该 Issue 与本库无关，我关闭了， 有问题请到 AgentWebX5 库上提问。
