### ISSUE TITLE
AgentWeb对网页的弹出式窗口的兼容

### ISSUE THREAD

**Issue by protectedMan** [Justson/AgentWeb#255]
http://www.xzggzy.com.cn/xzwebnew/allweb/
这个页面在用AgentWeb打开是这样的
![image](https://user-images.githubusercontent.com/17565737/35796738-74f319d8-0a98-11e8-8efd-f2a045b6f85e.png)
在电脑端是这样的（很明显是弹出了一个网页，把原来的覆盖掉了）
![image](https://user-images.githubusercontent.com/17565737/35796825-be48a2a6-0a98-11e8-906b-7c85b84f1553.png)

**Comment by protectedMan** [comment]
补充，chrome可以拦截弹出式窗口
![image](https://user-images.githubusercontent.com/17565737/35796925-12c35f2e-0a99-11e8-9b70-3c22f37f827f.png)

**Comment by Justson** [comment]
请自行实现`WebChromeClient#onJsAlert`方法
