### ISSUE TITLE
页面跳转时,无法获得URL

### ISSUE THREAD

**Issue by heiyeliuying** [Justson/AgentWeb#256]
```
private val mWebViewClient = object : WebViewClient() {
        override fun shouldOverrideUrlLoading(view: WebView?, url: String?): Boolean {
            Log.e("请求链接","url="+url);
            return super.shouldOverrideUrlLoading(view, url)
       } }
```

```
mAgentWeb = AgentWeb.with(this)//传入Activity or Fragment
                .setAgentWebParent(mContentView as RelativeLayout, RelativeLayout.LayoutParams(-1, -1))//传入AgentWeb 的父控件 ，如果父控件为 RelativeLayout ， 那么第二参数需要传入 RelativeLayout.LayoutParams ,第一个参数和第二个参数应该对应。
                .useDefaultIndicator()// 使用默认进度条
                .setWebViewClient(mWebViewClient)
                .setWebChromeClient(mWebChromeClient)
                .createAgentWeb()
                .ready()
                .go("https://v.qq.com")
```

在以上的代码中,无法正常的 LOG

**Comment by Justson** [comment]
检查下是否被混淆了。

**Comment by heiyeliuying** [comment]
我的代码没有做任何的混淆. 我把版本从 beta降到稳定版本后,该问题就消失了. 应该是 beta 版本中的问题.

**Comment by alinainai** [comment]
@Override
        public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request) {
            String url;
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                url = request.getUrl().toString();
            } else {
                url = request.toString();
            }
            if (gotoRedirection(url))
                return true;
            view.loadUrl(url);
            return true;
        }

        @Override
        public boolean shouldOverrideUrlLoading(WebView view, String url) {
            if (gotoRedirection(url))
                return true;
            view.loadUrl(url);
            return true;
        }
这样处理

**Comment by alinainai** [comment]
两个方法都写上
`private WebViewClient mWebViewClient = new WebViewClient() {
        @Override
        public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request) {
            String url;
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                url = request.getUrl().toString();
            } else {
                url = request.toString();
            }
            if (gotoRedirection(url))
                return true;
            view.loadUrl(url);
            return true;
        }

        @Override
        public boolean shouldOverrideUrlLoading(WebView view, String url) {
            if (gotoRedirection(url))
                return true;
            view.loadUrl(url);
            return true;
        }
    };`

**Comment by alinainai** [comment]
private WebViewClient mWebViewClient = new WebViewClient() {
        @Override
        public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request) {
            String url;
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                url = request.getUrl().toString();
            } else {
                url = request.toString();
            }
            if (gotoRedirection(url))
                return true;
            view.loadUrl(url);
            return true;
        }

        @Override
        public boolean shouldOverrideUrlLoading(WebView view, String url) {
            if (gotoRedirection(url))
                return true;
            view.loadUrl(url);
            return true;
        }
    };

**Comment by alinainai** [comment]
`private WebViewClient mWebViewClient = new WebViewClient() {
        @Override
        public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request) {
            String url;
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                url = request.getUrl().toString();
            } else {
                url = request.toString();
            }
            if (gotoRedirection(url))
                return true;
            view.loadUrl(url);
            return true;
        }

        @Override
        public boolean shouldOverrideUrlLoading(WebView view, String url) {
            if (gotoRedirection(url))
                return true;
            view.loadUrl(url);
            return true;
        }
    };`
