### ISSUE TITLE
页面未加载完成就销毁webview会打开外部浏览器

### ISSUE THREAD

**Issue by xuzhou4520** [Justson/AgentWeb#258]
fragment中使用agentWeb,当我在onPageStarted中截获目标连接后，会启动新的Fragment并结束当前的；但是截获的目标连接居然会拉起外部浏览器

**Comment by Justson** [comment]
`onPageStarted` 是无法拦截目标链接的，请使用`shouldOverrideUrlLoading`拦截目标链接。
