### ISSUE TITLE
建议sample工程和library工程做拆分，拆分为两个Repository

### ISSUE THREAD

**Issue by drivedreams** [Justson/AgentWeb#26]
最近需要使用webview做一些复杂点的展示，就发现了您的开源工程。首先感谢您的分享！我想把您的library工程作为一个module嵌入到我的工程中，但是我发现我拷贝后就比较难与您的代码同步。还有一种选择是使用compile，但是这样的话一旦遇到问题不能及时修改。如果把library作为一个单独的module（一个单独的repository），再在sample repository中通过忽略library repository的git消除冲突的git校验。这样如果使用过程中发现问题可以及时修改，如果解决问题也可以把解决方案反馈给您

**Comment by Justson** [comment]
很感谢你的建议 ， 但是这么做不利于仓库管理和更新 。
