### ISSUE TITLE
请教一下AgenWeb是如何设计权限请求的呢？

### ISSUE THREAD

**Issue by zengcanxiang** [Justson/AgentWeb#261]
我通过阅读源码发现，实现PermissionInterceptor是通过发射判断是否DefaultDownloadImpl类，然后设置到这个里面，但是没有找到设置到这个里面的PermissionInterceptor是如何被调用，如何判断是否权限是否存在是否要申请？

**Comment by Justson** [comment]
`AgentWeb` 有自己权限机制 ， 当触发下载的时候，需要 Storage 权限 ，会自动申请权限。
#### `PermissionInterceptor ` 的设计用于做权限过滤。
举个例子
- `PermissionInterceptor` 能达到 url1 允许授权， url2 拒绝授权的效果。
- 当然也存在其他用途，例如把用户拒绝的权限拦截下，对拒绝的权限做 Rationale 。

**Comment by zengcanxiang** [comment]
@Justson 对对对，我就是想了解一下，AgentWeb如何对权限进行处理的。阅读源码，没有get到AgentWeb处理权限的地方在哪里。PermissionInterceptor是具体处理某一个权限或者某一个url对应的权限的操作，那么触发这一个操作是实现在哪里呢？

我只在`DefaultDownloadImpl`里看到有`mPermissionListener.intercept(url, AgentWebPermissions.STORAGE, "download")` 其他的地方没有找到

**Comment by Justson** [comment]
Android Studio  `Find in path` 功能能帮到你。
