### ISSUE TITLE
这个链接下载的时候文件大小一直是0B

### ISSUE THREAD

**Issue by LeonShannon** [Justson/AgentWeb#266]
http://cdn.360taojin.com/resource/get/fid/5a78345ae87bbd64a309a1c6.apk
别的可以.目前这个怎么下载都是0B.然后就会自动打开.提示解析包出错.
用downloadmanager下载可以正常打开.

**Comment by Justson** [comment]
`contentLength` 响应为不正确，这边测试为-1
