### ISSUE TITLE
魅族崩溃

### ISSUE THREAD

**Issue by mzyq** [Justson/AgentWeb#269]
手机信息
[{
	"brandName": "魅族",
	"failMsg": "// CRASH: com.neisha.ppzu (pid 14752)\n// Short Msg: java.lang.IllegalStateException\n// Long Msg: java.lang.IllegalStateException: Unable to create layer for WebView @37f3a77, size 1080x14427 exceeds max size 8192\n// Build Label: Meizu/M1621/M1621:7.0/NRD90M/1514175933:user/release-keys\n// Build Changelist: 1514175933\n// Build Time: 1514176402000\n// java.lang.IllegalStateException: Unable to create layer for WebView @37f3a77, size 1080x14427 exceeds max size 8192\n// \tat android.os.MessageQueue.nativePollOnce(Native Method)\n// \tat android.os.MessageQueue.next(MessageQueue.java:328)\n// \tat android.os.Looper.loop(Looper.java:148)\n// \tat android.app.ActivityThread.main(ActivityThread.java:6406)\n// \tat java.lang.reflect.Method.invoke(Native Method)\n// \tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)\n// \tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)\n// \n",
	"modelName": "meizu_M5 Note",
	"osVersion": "Flyme 6.2.5.0A"
}]

代码
`
  mAgentWeb = AgentWeb.with(this)
                .setAgentWebParent(webContainer, new ViewGroup.LayoutParams(-1, -1))
                .closeProgressBar()
                .setSecurityType(AgentWeb.SecurityType.strict)
                .interceptUnkownScheme()
                .createAgentWeb()
                .ready()
                .go(url);
`

**Comment by Justson** [comment]
`webContainer `为 `ScrollView `?

**Comment by mzyq** [comment]
商品详情页 ScrollView是最外层，
`
<FrameLayout
                android:id="@+id/webContainer"
                android:layout_width="match_parent"
                android:layout_height="match_parent"/>
`

**Comment by Justson** [comment]
#189

**Comment by mzyq** [comment]
谢谢
