### ISSUE TITLE
没有主动跳转页面的方法吗?

### ISSUE THREAD

**Issue by heiyeliuying** [Justson/AgentWeb#274]
我的场景是这样的. 
首先go(A)访问,然后 A 里有一些页面存在于 android 交互的逻辑(例如弹出一个地址选择框), 然后用户选择了 地址后,我需要重定向到页面 B. 
现在的问题是,我通过
  mAgentWeb.webCreator.webView.loadUrl(response.url);
或者
mAgentWeb.urlLoader.loadUrl(response.url) 
这两种方式都会出现跳转页面后. 点击回退时,页面加载就不正常了.

**Comment by Justson** [comment]
方便写成个小Demo上传到GitHub上，让我尝试下吗？

**Comment by heiyeliuying** [comment]
已经找到问题了.是因为mAgentWeb 的生命周期的问题. 需要在 Fragment或者 Activity 的生命周期中调用对应的方法才可以.
