### ISSUE TITLE
下拉回弹有滑动冲突

### ISSUE THREAD

**Issue by changshuai7** [Justson/AgentWeb#275]
如题，当H5设置下拉回弹以后，会有滑动冲突。
举个例子，这是我们公司的一个H5地址：https://hyd.hengchang6.com/jsd/static/html/zhongyidaiLoan/index.html
H5页面中间有个选择城市的控件。
此链接在微信、QQ中打开，城市选择的控件和下拉回弹不冲突，但是在AgentWeb中却有冲突。

**Comment by Justson** [comment]
参照`AutoHidenToolbarActivity`

**Comment by cdcdec** [comment]
这个找到办法解决了吗？@changshuai7
