### ISSUE TITLE
无法兼容https://m.bilibili.com/index.html(哔哩哔哩)和http://m.yinyuetai.com/(音悦台)这两个网站

### ISSUE THREAD

**Issue by heiyeliuying** [Justson/AgentWeb#276]
在浏览器输入这两个网址时,显示的均为哔哩哔哩和音悦台的移动适配网页. 
但是当使用 AgentWeb 访问这两个地址时,总是会自动跳转到 PC 的适配上. 是不是 UserAgent 的问题啊?找了半天,没有找到对应的解决方案. 
跪求修复.

**Comment by heiyeliuying** [comment]
难道大家都没有遇到这个问题吗

**Comment by 357847847** [comment]
尝试使用一下。getAgentWeb().agentWebSettings.webSettings.useWideViewPort = true
我是用得kotlin 主要设置setting的useWideViewPort属性

**Comment by dpatrongomez** [comment]
> 
> 
> 尝试使用一下。getAgentWeb().agentWebSettings.webSettings.useWideViewPort = true
> 我是用得kotlin 主要设置setting的useWideViewPort属性

How can I use it?

**Comment by manburenshenglu** [comment]
> 尝试使用一下。getAgentWeb().agentWebSettings.webSettings.useWideViewPort = true
> 我是用得kotlin 主要设置setting的useWideViewPort属性

我设置了还是没效果啊

**Comment by ieliwb** [comment]
有人解决了吗？bilibili是自适应字体大小的，被放大了

**Comment by Justson** [comment]
useWideViewPort 有一定的兼容问题。
