### ISSUE TITLE
返回上级页面直接退出，alert对话框显示不出来（急、急、急）

### ISSUE THREAD

**Issue by AbrahamCaiJin** [Justson/AgentWeb#279]
我用Activity加载html网页，返回上级页面直接退出，alert对话框显示不出来，网页端是有的。有点急

**Comment by AbrahamCaiJin** [comment]
@Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (!mAgentWeb.back()){
//            this.finish();
        }
        return true;
    }

这段代码是退出到登录页面，不加的直接退出app，我用的Activity，麻烦你了

**Comment by AbrahamCaiJin** [comment]
测试了，不行，混淆加不加都一样

**Comment by Justson** [comment]
方便留下个链接吗？
