### ISSUE TITLE
反馈问题

### ISSUE THREAD

**Issue by TCQQ** [Justson/AgentWeb#28]
1. 如何修改通过WebView下载文件的路径？
2. 我重复调用OnCreat下的方法想实现刷新界面不起作用，如何刷新当前WebView界面？

**Comment by Justson** [comment]
非常感谢您的反馈 ！
1.  下载路径暂时无法修改的 。 (下载完成回调地址 ，下个版本支持)
2. `mAgentWeb.getLoader().reload();`刷新界面
