### ISSUE TITLE
6.0的机子 上传图片报错了

### ISSUE THREAD

**Issue by yummyChina** [Justson/AgentWeb#280]
在6.0的机子上几乎全挂，报错基本类似都是Cannot open content uri

Cannot open content uri: content://com.android.providers.media.documents/document/image%3A14
                                                                     java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{7f52263 4529:com.xxx.xxx/u0a60} (pid=4529, uid=10060) requires android.permission.MANAGE_DOCUMENTS or android.permission.MANAGE_DOCUMENTS
                                                                         at android.os.Parcel.readException(Parcel.java:1599)
                                                                         at android.os.Parcel.readException(Parcel.java:1552)
                                                                         at 

小米4:

com.dysoft.newmobile W/ContentUriUtils: Cannot open content uri: content://com.miui.gallery.open/raw/%2Fstorage%2Femulated%2F0%2Fphotodemo%2Fimage%2F171123132238.jpg
                                                                     java.lang.SecurityException: Permission Denial: reading com.miui.gallery.provider.GalleryOpenProvider uri content://com.miui.gallery.open/raw/%2Fstorage%2Femulated%2F0%2Fphotodemo%2Fimage%2F171123132238.jpg from pid=3311, uid=10230 requires the provider be exported, or grantUriPermission()

**Comment by wuqi713** [comment]
我的也是 但是权限好像都给了 奇怪。

**Comment by Justson** [comment]
### 问题起因
这个是兼容性问题，各个手机厂商返回文件路径都不一致，而 ContentUriUtils 又无法处理该Uri，导致文件在路径转化的时候出错。
### 解决方案
##### 自定义文件选择器
如果你应用用了图片选择器 ，而你 WebView 的内容又单纯的只想获取图片， 可以考虑使用图片选择器来解决，例如知乎的 Matisse。

### 相关几个疑问
##### 提高 AgentWeb-FileChooser 的兼容性吗？
有人说为什么不提高 AgentWeb-FileChooser 的兼容性 ，比如说针对各个厂商来做路径转化 ， 这种方案不是不行， 只是通过硬编码和大量工作量的方式来适配，实现起来太不灵活，而且适配也很有限制，所以保持了当前现在这种状态。

##### AgentWeb-FileChooser  为什么不内置文件能力
1、 AgentWeb 本身是高度灵活的，用户可以从`MiddlewareWebChromeBase`入手去实现自己的文件选择。
2、市面上有完整的文件选择， 不想重造轮子。
3、个人感觉系统文件管理系统足够优秀，没有重造轮子的必要。

### 最后
展望未来，Android 系统兼容性会慢慢起来。
