### ISSUE TITLE
WebChromeClientDelegate中onJsAlert到底从哪里弹出个dialog？

### ISSUE THREAD

**Issue by CH-Augustine** [Justson/AgentWeb#287]
private WebChromeClientDelegate webChromeClientDelegate = new WebChromeClientDelegate(new WebChromeClient()){
        @Override
        public void onReceivedTitle(WebView view, String title) {
            super.onReceivedTitle(view, title);
            contentTitleTv.setText(title);
        }

        @Override
        public boolean onJsAlert(WebView view, String url, String message, JsResult result) {
            Log.e(this.getClass().getSimpleName(),"message:::"+message);
            return super.onJsAlert(view, url, message, result);
        }

    };
onJsAlert根本捕获不到，而且也没有找到Dialog在哪里，默认的Toast也找不到！

**Comment by CH-Augustine** [comment]
AgentWeb.java
741 行 -- 744行
		public CommonBuilder setAgentWebUIController(@Nullable AgentWebUIControllerImplBase agentWebUIController) {
			this.mAgentBuilder.mAgentWebUIController = agentWebUIController;
			return this;
		}

为啥非让我传一个AgentWebUIControllerImplBase ？不应该是AbsAgentWebUIController吗？

**Comment by Justson** [comment]
`DefaultUIController#onJsAlert`
