### ISSUE TITLE
当html里面有ajax请求，或者iframe里面有ajax请求的时候，cookie无法同步

### ISSUE THREAD

**Issue by rex26** [Justson/AgentWeb#289]
场景：
html里面用到了 jQuery的post方法，以及用iframe弹窗里面用ajax加载树。

现象/问题：
执行ajax展示的控件显示为空白，iframe的话会直接跳转到登录界面；应该是cookie没有同步成功的问题。

**Comment by Justson** [comment]
1、 是否涉及跨域。
2、移动端通过 AgentWeb 访问 Cookie 正常吗
3、手动加上`cookie`访问正常吗？例如`document.cookie`

**Comment by rex26** [comment]
sorry,  后台问题。。。。。我哭
