### ISSUE TITLE
url带有参数时，taost参数给用户看到了，安全性瞬间下降，就因为这个又要换库，真的是日了uzi

### ISSUE THREAD

**Issue by MyFisherTiger** [Justson/AgentWeb#301]

**Comment by Justson** [comment]
文明。

**Comment by Justson** [comment]
Toast 显示参数 ， 是什么意思， 方便贴下代码，或者上传下DEMO吗？

**Comment by MyFisherTiger** [comment]
好像不能发送图片啊，就是说我的url带有参数，如https：//www.asfaf.com/asfaf.html?userID=xxx,然后第一次进入该页面的时候，Toast一个弹窗，吧xxx显示出来了

**Comment by Justson** [comment]
截图，日志， 代码？

**Comment by MyFisherTiger** [comment]
这种参数不应该弹出对话给用户看到吧，搞得我是有点无奈，不过你这么快回我真是没想到，给你一个赞，给你两个图片链接吧：https://pan.baidu.com/s/15v6QSXylnBMAATXIyDKe6g
第二个：https://pan.baidu.com/s/1rAzyOOtMbyVFu8D9aJxmug

**Comment by MyFisherTiger** [comment]
`String url=webViewUrl+openId;
        mAgentWeb = AgentWeb.with(this)
                .setAgentWebParent(mLinearLayout, new LinearLayout.LayoutParams(-1, -1))
                .useDefaultIndicator()
                .createAgentWeb()
                .ready()
                .go(url);`

**Comment by Justson** [comment]
AgentWeb 所有 Toast 都会回调这个方法，`AbsAgentWebUIController#onShowMessage` 你检查下， 做下过滤可以了。

**Comment by MyFisherTiger** [comment]
这样重写onShowMessage方法不行，还用什么其他的拦截方法？`public class MyWebUIController extends AgentWebUIControllerImplBase {
        @Override
        public void onShowMessage(String message, String from) {
            return;
            //super.onShowMessage(message, from);

        }
    }`
` mAgentWeb = AgentWeb.with(this)
                .setAgentWebParent(mLinearLayout, new LinearLayout.LayoutParams(-1, -1))
                .useDefaultIndicator()
                .setAgentWebUIController(new MyWebUIController())
                .createAgentWeb()
                .ready()
                .go(url);`

**Comment by MyFisherTiger** [comment]
我建议把这种拦截，添加到read me里，有时间在仔细研究一下源码0.0

**Comment by MyFisherTiger** [comment]
补充：我上面的那种处理是没有生效的

**Comment by Justson** [comment]
没有生效，说明不是AgentWeb 内部的弹窗， 你可以单纯是 WebVIew 试下。

**Comment by MyFisherTiger** [comment]
我使用单纯的webview试过了，没有弹，而且使用AgentWeb，当没有参数的时候，是不弹的，当有参数时就弹出来了

**Comment by MyFisherTiger** [comment]
基本锁定是AgentWeb内部弹的，所以有点束手无策

**Comment by Justson** [comment]
那麻烦您把链接发下

**Comment by MyFisherTiger** [comment]
https://checkin-1256368824.file.myqcloud.com/html/homepage.html?openid=

**Comment by MyFisherTiger** [comment]
要接上相应的openid，可以随便接，错的也会显示

**Comment by MyFisherTiger** [comment]
与阅读源码直接，导入源码的库，然后注释掉Toast的代码，后面就不再弹了，说明之前重写onShowMessage是没有生效的，我暂时是这样解决了，后面期待你那边更好的解决办法吧，让拦截生效当然是最好的

**Comment by Justson** [comment]
你注释的代码块是， 麻烦发一下， 我看一下问题。

**Comment by MyFisherTiger** [comment]
AgentWebUtils这个类里面的，我只是不显示而已，并没有做到拦截
`static void toastShowShort(Context context, String msg) {

		/*if (mToast == null) {
			mToast = Toast.makeText(context.getApplicationContext(), msg, Toast.LENGTH_SHORT);
		} else {
			mToast.setText(msg);
		}
		mToast.show();*/

	}`

**Comment by Justson** [comment]
```
/**
 * @author cenxiaozhong
 * @date 2017/12/8
 * @since 3.0.0
 */
public class DefaultDesignUIController extends DefaultUIController {


	private BottomSheetDialog mBottomSheetDialog;
	private static final int RECYCLERVIEW_ID = 0x1001;
	private Activity mActivity = null;
	private WebParentLayout mWebParentLayout;
	private LayoutInflater mLayoutInflater;

	@Override
	public void onJsAlert(WebView view, String url, String message) {
		Log.i("Info", "onJsAlert msg:" + message);
		onJsAlertInternal(view, message);

	}
....省略
}
```


```
Info: onJsAlert msg:12345
```

你们前端测试代码没删吧 
JavaScript
```
alert(openId)
```

**Comment by MyFisherTiger** [comment]
看样子是js那块调用了，所以没生效，我让前段检查一下看看

**Comment by MyFisherTiger** [comment]
还真是啊，0.0，想得不够全面@_@
