### ISSUE TITLE
跨域问题怎么办?

### ISSUE THREAD

**Issue by LiYuXx** [Justson/AgentWeb#303]
我想设置这些
webSettings.setAllowFileAccessFromFileURLs(true);
webSettings.setAllowContentAccess(true);
webSettings.setAllowUniversalAccessFromFileURLs(true);

**Comment by Justson** [comment]
[自定义Settings](https://github.com/Justson/AgentWeb/wiki/WebSettings-%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AE%BE%E7%BD%AE)
