### ISSUE TITLE
结束agentweb,还有什么地方需要关闭吗，希望告诉我下0

### ISSUE THREAD

**Issue by FaithOo** [Justson/AgentWeb#304]
关闭时:
if (null != mAgentWeb) {
            mAgentWeb.clearWebCache();
            mAgentWeb.getAgentWebSettings().getWebSettings().setJavaScriptEnabled(false);
            AgentWebConfig.removeSessionCookies();
            mAgentWeb.getWebLifeCycle().onDestroy();
            mWebChromeClient=null;
            mWebViewClient=null;
            mAgentWeb = null;
        }
打开:
if (null == mAgentWeb) {//
            mAgentWeb = AgentWeb.with(this)
                    .setAgentWebParent(mWeb_rl, new RelativeLayout.LayoutParams(LayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT))//
                    .useDefaultIndicator()//
                    .defaultProgressBarColor()
                    .setWebChromeClient(mWebChromeClient)
                    .setWebViewClient(mWebViewClient)
                    .interceptUnkownScheme()
                    .createAgentWeb()
                    .ready()
                    .go(htmlPath);

        mAgentWeb.getAgentWebSettings().getWebSettings().setUserAgentString("");//android
        mAgentWeb.getAgentWebSettings().getWebSettings().setJavaScriptEnabled(true);
        mAgentWeb.getJsInterfaceHolder().addJavaObject("parent", new AndroidInterface());
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {mAgentWeb.getAgentWebSettings().getWebSettings().setMixedContentMode(WebSettings.MIXED_CONTENT_ALWAYS_ALLOW);
        }
        }

**Comment by Justson** [comment]
请看项目中的`Sample ` 。
