### ISSUE TITLE
错误提示页面出现的频率过高

### ISSUE THREAD

**Issue by ysk152** [Justson/AgentWeb#305]
onReceivedHttpError  这种网页404或500的的应该替换成 网页加载失败界面
但是 onReceivedError(有两个回调)  这种有可能只是某个网页的某个内部资源出错 没有必要直接盖上网页加载失败的界面吧？
onReceivedError  出错有可能只是内部某个资源302了 结果整个页面覆盖个错误页面是不是不太合适？

**Comment by Justson** [comment]
只有当MainFrame出错，才会显示错误页。
