### ISSUE TITLE
没集成alipay的话,不打算把里面相关代码删了吗

### ISSUE THREAD

**Issue by luxiao0314** [Justson/AgentWeb#306]
private boolean isAlipay(final WebView view, String url) {

		try {

			Activity mActivity = null;
			if ((mActivity = mWeakReference.get()) == null) {
				return false;
			}
			/**
			 * 推荐采用的新的二合一接口(payInterceptorWithUrl),只需调用一次
			 */
			if (mPayTask == null) {
				Class clazz = Class.forName("com.alipay.sdk.app.PayTask");
				Constructor<?> mConstructor = clazz.getConstructor(Activity.class);
				mPayTask = mConstructor.newInstance(mActivity);
			}
			final PayTask task = (PayTask) mPayTask;
			boolean isIntercepted = task.payInterceptorWithUrl(url, true, new H5PayCallback() {
				@Override
				public void onPayResult(final H5PayResultModel result) {
					final String url = result.getReturnUrl();
					if (!TextUtils.isEmpty(url)) {
						AgentWebUtils.runInUiThread(new Runnable() {
							@Override
							public void run() {
								view.loadUrl(url);
							}
						});
					}
				}
			});
			if (isIntercepted) {
				LogUtils.i(TAG, "alipay-isIntercepted:" + isIntercepted + "  url:" + url);
			}
			return isIntercepted;
		} catch (Throwable ignore) {
			if (AgentWebConfig.DEBUG) {
				ignore.printStackTrace();
			}
		}
		return false;
	}

**Comment by Justson** [comment]
不打算， 支付算常用功能。 如果您不需要该功能， 可以直接依赖项目， 把这部分代码删掉，不影响使用。
