### ISSUE TITLE
SIGSEGV(SEGV_MAPERR)

### ISSUE THREAD

**Issue by huangchenggang** [Justson/AgentWeb#309]
#00 pc 00207c28 /system/lib/libwebviewchromium.so [armeabi-v7a]
--
2 #01 pc 0043bd6b /system/lib/libwebviewchromium.so [armeabi-v7a]
3 #02 pc 00499a47 /system/lib/libwebviewchromium.so [armeabi-v7a]
4 #03 pc 0049d4f9 /system/lib/libwebviewchromium.so [armeabi-v7a]
5 #04 pc 00496d6b /system/lib/libwebviewchromium.so [armeabi-v7a]
6 #05 pc 00492ea7 /system/lib/libwebviewchromium.so [armeabi-v7a]
7 #06 pc 00fb2b65 /system/lib/libwebviewchromium.so [armeabi-v7a]
8 #07 pc 00fb29d3 /system/lib/libwebviewchromium.so [armeabi-v7a]
9 #08 pc 00239967 /system/lib/libwebviewchromium.so [armeabi-v7a]
10 #09 pc 0021c56d /system/lib/libwebviewchromium.so [armeabi-v7a]
11 #10 pc 0021d969 /system/lib/libwebviewchromium.so [armeabi-v7a]
12 #11 pc 0021dd43 /system/lib/libwebviewchromium.so [armeabi-v7a]
13 #12 pc 00234813 /system/lib/libwebviewchromium.so (Java_com_android_org_chromium_base_SystemMessageHandler_nativeDoRunLoopOnce+18) [armeabi-v7a]
14 #13 pc 0001ab43 /system/app/webview/arm/webview.odex (oatdata+105283) [armeabi]
15 java:
16 com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
17 android.os.Handler.dispatchMessage(Handler.java:102)
18 android.os.Looper.loop(Looper.java:135)
19 android.app.ActivityThread.main(ActivityThread.java:5413)
20 java.lang.reflect.Method.invoke(Native Method)
21 java.lang.reflect.Method.invoke(Method.java:372)
22 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:927)
23 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:722)

芝麻信用授权后倒计时页面点返回按钮，应用闪退一次

**Comment by hnty545** [comment]
我也检测到有这个崩溃日志，但是不是芝麻信用，不知道发生的情况，请问后来怎么解决的呢

**Comment by Corey3213** [comment]
这个最后是怎么解决的？

**Comment by ideamutou** [comment]
这个怎么关了那？
