### ISSUE TITLE
某些下载连接会触发下载异常

### ISSUE THREAD

**Issue by protectedMan** [Justson/AgentWeb#314]
![image](https://user-images.githubusercontent.com/17565737/39036526-5d515752-44b0-11e8-87e0-371178b5fa28.png)

初步统计，这种链接（特征是末尾不带文件后缀的）会触发下载异常: http://ggzy.sqzwfw.gov.cn/WebBuilderDS/WebbuilderMIS/attach/downloadZtbAttach.jspx?attachGuid=af982055-3d76-4b00-b5ab-36dee1f90b11&appUrlFlag=sqztb&siteGuid=7eb5f7f1-9041-43ad-8e13-8fcb82ea831a
-------------------------------
这种是正常的。
http://www.xzggzy.com.cn/xzwebnew/AttachStorage/a5ac80ee-4113-4c01-a362-d02b7e0609a1/%e6%8b%9b%e6%a0%87%e6%96%87%e4%bb%b6%e6%ad%a3%e6%96%87.pdf

**Comment by protectedMan** [comment]
![image](https://user-images.githubusercontent.com/17565737/39036696-e40ade4e-44b0-11e8-9ecf-1f37d9e4e71d.png)

**Comment by Justson** [comment]
与文件名无关， 暂时不支持分块传输。

**Comment by troytian1986** [comment]
我也遇到这种，应该怎么处理？很多下载链接是返回数据流的，而不是直接指向文件的
