### ISSUE TITLE
webview生命周期方法对其他库的影响

### ISSUE THREAD

**Issue by hnty545** [Justson/AgentWeb#324]
agentweb说明里提到用webview生命周期方法来省电，但是如果有其他库用到了webview，而agentweb里调pause以后，在其他库没有调resume，就会无法完全加载。
也就是说所有用到webview的库要么都调用生命周期，要么都不调用，如果有一个调用，其他库就会受影响，请问这个问题怎么解决呢？

@Override
    protected void onPause() {
        mAgentWeb.getWebLifeCycle().onPause(); 
        super.onPause();

    }

    @Override
    protected void onResume() {
        mAgentWeb.getWebLifeCycle().onResume();
        super.onResume();
    }
    @Override
    public void onDestroyView() {
        mAgentWeb.getWebLifeCycle().onDestroy();
        super.onDestroyView();
    }

**Comment by hnty545** [comment]
我知道怎么回事了，agentweb的onPause里调用了pauseTimers，这个方法会对所有webview造成影响

**Comment by HolickABC** [comment]
是的  我也遇到这个问题了   因为webview暂停了
