### ISSUE TITLE
1.调用本地图片选择并上传问题   2.新版本为啥页面被放大了。。

### ISSUE THREAD

**Issue by burro630** [Justson/AgentWeb#326]
值得肯定的是，AgentWeb的运行速度貌似快了些。
1.问题如标题所述，拍照上传正常，选择图片H5页面展示正常，提交的时候会提示找不到路径、或者说权限问题！！ 研究了半天，发现获取到的uri，需要进行转换的。安卓4.4以前和4.4以后获取方式不一样。我已经做了修改，可以正常使用。希望作者关注一下这块，防止别人入坑 
（具体修改位置是FileUpLoadChooserImpl下 private Uri[] processData(Intent data) 方法内）
2.我取的2.0.1版本显示正常的，为何最新版本h5显示辣么大。原生的webview也是正常的。不知道中间经历了什么，还是什么地方配置有问题。最终选了2.0.1版本

最后 感谢作者辛勤付出！

**Comment by hnty545** [comment]
您好！能分享一下文件处理的那一段代码吗，万分感谢！
@burro630

**Comment by hnty545** [comment]
#326

**Comment by burro630** [comment]
不好意思 没有注意邮箱
这是processData（）下的一段代码：  
 if (!TextUtils.isEmpty(target)) {
            String path=FileUtils.getPath(BaseApplication.getAppContext(),Uri.parse(target));
            File file = new File(path);
           Uri fileUri = Uri.fromFile(file);
            return datas = new Uri[]{fileUri};
        }
主要是第二行的getPath（）转换方法，获取文件的实际地址，然后重新转成uri代替之前的。
getPath（）方法也是参考网上的，这是链接
https://www.2cto.com/kf/201502/376975.html
