### ISSUE TITLE
RealDownLoader下载的时候onProgressUpdate直接崩掉

### ISSUE THREAD

**Issue by tianyingzhong** [Justson/AgentWeb#333]
报错信息如下：
java.lang.NoSuchFieldError: No instance field mNotification of type Landroid/app/Notification; in class Landroid/support/v4/app/NotificationCompat$d;

原因是：
 public boolean hasDeleteContent(){
        return cBuilder.mNotification.deleteIntent!=null;
 }
这个方法会报错，因为cBuilder（NotificationCompat.Builder）里的mNotification不是public类型的

**Comment by Justson** [comment]
请使用最新版。
