### ISSUE TITLE
filechooser库的选择器上传文件报权限不足

### ISSUE THREAD

**Issue by hnty545** [Justson/AgentWeb#334]
添加filechooser库上传文件使用默认的处理，在选择器选一张图片的时候

05-11 14:47:19.135 31251-31300/? D/OpenGLRenderer: endAllStagingAnimators on 0x55a4a0b000 (ListView) with handle 0x55a4a28d20
05-11 14:47:19.155 1407-2491/? W/ActivityManager: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{13ad408e 696:com.just.agentweb.sample/u0a106} (pid=696, uid=10106) requires android.permission.MANAGE_DOCUMENTS or android.permission.MANAGE_DOCUMENTS
05-11 14:47:19.155 696-894/? W/System.err: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{13ad408e 696:com.just.agentweb.sample/u0a106} (pid=696, uid=10106) requires android.permission.MANAGE_DOCUMENTS or android.permission.MANAGE_DOCUMENTS
05-11 14:47:19.155 696-894/? W/System.err:     at android.os.Parcel.readException(Parcel.java:1574)
05-11 14:47:19.155 696-894/? W/System.err:     at android.os.Parcel.readException(Parcel.java:1527)
05-11 14:47:19.155 696-894/? W/System.err:     at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:3447)
05-11 14:47:19.155 696-894/? W/System.err:     at android.app.ActivityThread.acquireProvider(ActivityThread.java:4757)
05-11 14:47:19.155 696-894/? W/System.err:     at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2522)
05-11 14:47:19.155 696-894/? W/System.err:     at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1454)
05-11 14:47:19.155 696-894/? W/System.err:     at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1074)
05-11 14:47:19.155 696-894/? W/System.err:     at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:931)
05-11 14:47:19.155 696-894/? W/System.err:     at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:788)
05-11 14:47:19.155 696-894/? W/System.err:     at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:743)
05-11 14:47:19.155 696-894/? W/System.err:     at com.android.org.chromium.base.ContentUriUtils.getParcelFileDescriptor(ContentUriUtils.java:97)
05-11 14:47:19.155 696-894/? W/System.err:     at com.android.org.chromium.base.ContentUriUtils.contentUriExists(ContentUriUtils.java:77)
05-11 14:47:19.155 696-894/? A/chromium: [FATAL:jni_android.cc(269)] Check failed: false. Please include Java exception stack in crash report
05-11 14:47:19.155 696-894/? A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 894 (Chrome_FileThre)

**Comment by hnty545** [comment]
另一台是这个提示

05-11 15:09:14.978 14548-14548/com.woyinqianbao.zhifu.fx.dev.debug I/InputMethodManager: handleMessage: MSG_SET_ACTIVE true, was false
05-11 15:09:14.989 14548-14689/com.woyinqianbao.zhifu.fx.dev.debug W/ContentUriUtils: Cannot open content uri: content://com.android.providers.media.documents/document/image%3A495026
                                                                                      java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaDocumentsProvider uri content://com.android.providers.media.documents/document/image%3A495026 from pid=14548, uid=10761 requires android.permission.MANAGE_DOCUMENTS, or grantUriPermission()
                                                                                          at android.os.Parcel.readException(Parcel.java:1556)
                                                                                          at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
                                                                                          at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
                                                                                          at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:691)
                                                                                          at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1151)
                                                                                          at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:975)
                                                                                          at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:832)
                                                                                          at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:787)
                                                                                          at org.chromium.base.ContentUriUtils.getParcelFileDescriptor(ContentUriUtils.java:109)
                                                                                          at org.chromium.base.ContentUriUtils.openContentUriForRead(ContentUriUtils.java:62)
05-11 15:09:14.998 14548-14689/com.woyinqianbao.zhifu.fx.dev.debug W/ContentUriUtils: Cannot open content uri: content://com.android.providers.media.documents/document/image%3A495026
                                                                                      java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaDocumentsProvider uri content://com.android.providers.media.documents/document/image%3A495026 from pid=14548, uid=10761 requires android.permission.MANAGE_DOCUMENTS, or grantUriPermission()
                                                                                          at android.os.Parcel.readException(Parcel.java:1556)
                                                                                          at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
                                                                                          at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
                                                                                          at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:691)
                                                                                          at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1151)
                                                                                          at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:975)
                                                                                          at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:832)
                                                                                          at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:787)
                                                                                          at org.chromium.base.ContentUriUtils.getParcelFileDescriptor(ContentUriUtils.java:109)
                                                                                          at org.chromium.base.ContentUriUtils.contentUriExists(ContentUriUtils.java:78)

**Comment by hnty545** [comment]
一台vivo一台oppo，都是5.1系统

**Comment by EternalSoySauce** [comment]
我这也是，已经添加android.permission.MANAGE_DOCUMENTS了，三星s8+ 7.0

**Comment by hnty545** [comment]
我查了没用，安卓5以上获取文件的路径不能直接用，应该算这个库的bug，导致安卓5以上的选择本地文件不可用

**Comment by hnty545** [comment]
这个问题用demo一样，不是权限问题，就是文件路径问题，估计要重写他那个处理方法

**Comment by hnty545** [comment]
#326

**Comment by EternalSoySauce** [comment]
@hnty545 翻到了我以前某个项目的uri适配，那个是从相册选择video的，昨天我电脑坏了新代码还没来得及上传没办法测试，兄弟你可以按这个思路改下试试看行不行得通。

public static Uri fitVideoUriFromAlbum(Uri uri) {
        String path = uri.toString();
        String slash = "%2F";
        String colon = "%3A";
        String baseUri = "content://media/external/video/media/";
        if (path.contains(slash)) {
            int signIndex = path.lastIndexOf(slash);
            int slashIndex = path.indexOf("/", signIndex);
            String videoId = slashIndex == -1 ? path.substring(signIndex + slash.length()) : path.substring(signIndex + slash.length(), slashIndex);
            return Uri.parse(baseUri + videoId);
        } else if (path.contains(colon)) {
            int signIndex = path.lastIndexOf(colon);
            int slashIndex = path.indexOf("/", signIndex);
            String videoId = slashIndex == -1 ? path.substring(signIndex + colon.length()) : path.substring(signIndex + colon.length(), slashIndex);
            return Uri.parse(baseUri + videoId);
        } else {
            return uri;
        }
    }

**Comment by hnty545** [comment]
我这样处理的，用他定义的代理方式，集成MiddlewareWebChromeBase重写onShowFileChooser，自己写一个ValueCallback<Uri[]>，在里面调用com.just.agentweb.AgentWebUtils.uriToPath来转地址，再用FileChooserParams回写回去
他其实里面就有uriToPath方法处理得很好了，只是没有去调用，不知道为什么
@EternalSoySauce

**Comment by yummyChina** [comment]
你的方法解决问题了没@hnty545

**Comment by EternalSoySauce** [comment]
电脑终于修好了== 
hnty545那个方法没改明白，不过确实修改#326说的那个 processData()方法就行了，我这个项目是需要选择图片，用我贴的那段适配video的代码改成image是可以用的，作者可以试试把这个方法里的uri适配一下

**Comment by hnty545** [comment]
@EternalSoySauce 和你那段相似的网络上也很多，我开始也是自己写的，但是看过com.just.agentweb.AgentWebUtils.uriToPath作者这个类之后我发现他的逻辑是一致的，并且看样子处理得更好，可以看看
@yummyChina

**Comment by hnty545** [comment]
代码是这样的

@Override
    @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
    public boolean onShowFileChooser(WebView webView, ValueCallback<Uri[]> filePathCallback, FileChooserParams fileChooserParams) {
        logService.d(TAG, "onShowFileChooser,openFileChooser>=5.0");
        return AgentWebUtils.onShowFileChooser(TAG, activity, agentWeb.getPermissionInterceptor(), webView, filePathCallback, fileChooserParams);
    }

——————————
public class AgentWebUtils {

    @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
    public static boolean onShowFileChooser(final String TAG, final Activity activity, PermissionInterceptor permissionInterceptor, WebView webView, final ValueCallback<Uri[]> filePathCallback, WebChromeClient.FileChooserParams fileChooserParams) {
        if (activity == null || activity.isFinishing() || webView == null) {
            return false;
        }
        ValueCallback<Uri[]> _filePathCallback = new ValueCallback<Uri[]>() {
            @Override
            public void onReceiveValue(Uri[] value) {
                if (value == null || value.length == 0) {
                    AppEnvService.getInstance().mLogService.d(TAG, "onReceiveValue.value=null or empty");
                    filePathCallback.onReceiveValue(null);
                    return;
                }
                try {
                    String[] path = com.just.agentweb.AgentWebUtils.uriToPath(activity, value);
                    File file;
                    for (int i = 0; i < value.length; i++) {
                        file = new File(path[i]);
                        value[i] = Uri.fromFile(file);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
                filePathCallback.onReceiveValue(value);
            }
        };
        return showFileChooserCompat(TAG, activity,
                webView,
                _filePathCallback,
                fileChooserParams,
                permissionInterceptor,
                null,
                null,
                null
        );
    }

    @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
    private static boolean showFileChooserCompat(String TAG, Activity activity,
                                                 WebView webView,
                                                 ValueCallback<Uri[]> valueCallbacks,
                                                 WebChromeClient.FileChooserParams fileChooserParams,
                                                 PermissionInterceptor permissionInterceptor,
                                                 ValueCallback valueCallback,
                                                 String mimeType,
                                                 Handler.Callback jsChannelCallback
    ) {
        try {
            Class<?> clz = Class.forName("com.just.agentweb.filechooser.FileChooser");
            Object mFileChooser$Builder = clz.getDeclaredMethod("newBuilder",
                    Activity.class, WebView.class)
                    .invoke(null, activity, webView);
            clz = mFileChooser$Builder.getClass();
            Method mMethod = null;
            if (valueCallbacks != null) {
                mMethod = clz.getDeclaredMethod("setUriValueCallbacks", ValueCallback.class);
                mMethod.setAccessible(true);
                mMethod.invoke(mFileChooser$Builder, valueCallbacks);
            }

            if (fileChooserParams != null) {
                mMethod = clz.getDeclaredMethod("setFileChooserParams", WebChromeClient.FileChooserParams.class);
                mMethod.setAccessible(true);
                mMethod.invoke(mFileChooser$Builder, fileChooserParams);
            }

            if (valueCallback != null) {
                mMethod = clz.getDeclaredMethod("setUriValueCallback", ValueCallback.class);
                mMethod.setAccessible(true);
                mMethod.invoke(mFileChooser$Builder, valueCallback);
            }


            if (!TextUtils.isEmpty(mimeType)) {
                mMethod = clz.getDeclaredMethod("setAcceptType", String.class);
                mMethod.setAccessible(true);
                mMethod.invoke(mFileChooser$Builder, mimeType);
            }

            if (jsChannelCallback != null) {
                mMethod = clz.getDeclaredMethod("setJsChannelCallback", Handler.Callback.class);
                mMethod.setAccessible(true);
                mMethod.invoke(mFileChooser$Builder, jsChannelCallback);
            }


            mMethod = clz.getDeclaredMethod("setPermissionInterceptor", PermissionInterceptor.class);
            mMethod.setAccessible(true);
            mMethod.invoke(mFileChooser$Builder, permissionInterceptor);

            mMethod = clz.getDeclaredMethod("build");
            mMethod.setAccessible(true);
            Object mFileChooser = mMethod.invoke(mFileChooser$Builder);

            mMethod = mFileChooser.getClass().getDeclaredMethod("openFileChooser");
            mMethod.setAccessible(true);
            mMethod.invoke(mFileChooser);

        } catch (Throwable throwable) {
            if (LogUtils.isDebug()) {
                throwable.printStackTrace();
            }
            if (valueCallbacks != null) {
                AppEnvService.getInstance().mLogService.d(TAG, "onReceiveValue empty");
                return false;
            }
            if (valueCallback != null) {
                valueCallback.onReceiveValue(null);
            }
        }
        return true;
    }
}

**Comment by EternalSoySauce** [comment]
@hnty545 按你这种做法用他的Utils确实不错，也还是只需要改那个processData()
private Uri[] processData(Intent data) {
        Uri[] datas = null;
        if (data == null) {
            return datas;
        }
        String target = data.getDataString();
        if (!TextUtils.isEmpty(target)) {
            String[] path = AgentWebUtils.uriToPath(mActivity, new Uri[]{Uri.parse(target)});
            datas = new Uri[path.length];
            File file;
            for (int i = 0; i < path.length; i++) {
                file = new File(path[i]);
                datas[i] = Uri.fromFile(file);
            }
            return datas;
        }
        ClipData mClipData = data.getClipData();
        if (mClipData != null && mClipData.getItemCount() > 0) {
            datas = new Uri[mClipData.getItemCount()];
            for (int i = 0; i < mClipData.getItemCount(); i++) {

                ClipData.Item mItem = mClipData.getItemAt(i);
                datas[i] = mItem.getUri();

            }
        }
        return datas;
    }

**Comment by EternalSoySauce** [comment]
这样改动比较小，就改了if (!TextUtils.isEmpty(target)) {}里边的内容

**Comment by hnty545** [comment]
我没加入他的源码。。是载入的库

**Comment by kslr** [comment]
引用 https://github.com/Justson/AgentWeb/issues/280
使用第三方选择器

**Comment by hnty545** [comment]
他库里有这个类，但很多方法私有的，我拿出来用了

**Comment by parcool** [comment]
@EternalSoySauce 方法亲测可行。

**Comment by yummyChina** [comment]
如果仅仅是图片的话是可以适配的，但是如果是要支持文件选择（不限制文件类型），好像还是没有解决方案，感觉文件 还是要通过http进行传输，然后作js交互，仅仅是onFileChooser()感觉解决不了问题

**Comment by EternalSoySauce** [comment]
@yummyChina parcool应该说的是下边我改processData的那个方法，不是上边单独适配图片的
