### ISSUE TITLE
生成debug apk，安装后报错

### ISSUE THREAD

**Issue by VeronicaRen** [Justson/AgentWeb#336]
直接连as调试没有问题，一旦打包成apk，无论是debug还是release，都会崩溃并报错：
com.just.agentweb.JsInterfaceObjectException: this object has not offer method javascript to call , please check addJavascriptInterface annotation was be added
尝试过修改混淆信息，但是没有用

**Comment by Justson** [comment]
注入类，没有加入`@JavascriptInterface`

**Comment by qiusunshine** [comment]
原因可能是没有加入agentweb的混淆，有可能你已经解决了，给后来人提供参考。
