### ISSUE TITLE
ActionActivity 小米读取本地图片提示没有权限

### ISSUE THREAD

**Issue by shanyaodan** [Justson/AgentWeb#340]
需要添加下面代码就没问题了

   if (Build.VERSION.SDK_INT <19) {
                mIntent.setAction(Intent.ACTION_GET_CONTENT);
            }else {
                mIntent.setAction(Intent.ACTION_OPEN_DOCUMENT);
            }

**Comment by callmenero** [comment]
你好，我也碰到相同的问题，请问在哪里添加呢

**Comment by shanyaodan** [comment]
要在源码里面改，
