### ISSUE TITLE
无法滑动，滑动冲突

### ISSUE THREAD

**Issue by lmdiloveu** [Justson/AgentWeb#345]
加载的h5页面高度是变化的，刚加载的h5页面只有一个div，然后h5页面的js会请求接口获取数据，添加更多的div，这个时候就无法上拉了
![image](https://user-images.githubusercontent.com/8290718/40535237-1699b790-603b-11e8-98de-6dd362a1f29f.png)
如果给h5页面设置固定高度，上拉之后，再下拉就不行了！

**Comment by LiChangXing** [comment]
解决了吗  我也遇到这种问题
