### ISSUE TITLE
打开今日头条链接（toutiao.com）首页被字体放大了

### ISSUE THREAD

**Issue by Ordosbxy** [Justson/AgentWeb#346]
暂时就发现今日头条的首页字体被放大了， 其他地址使用AgentWeb打开支持， 不知道是为什么？

**Comment by Ordosbxy** [comment]
使用AgentWeb 3.1.0版本不会出现这个问题， 是更新到4.0.0版本后出现的。

**Comment by zhengfuwang** [comment]
4.0.2 版本也还存在这个问题， 重置下 UserAgent 就好了

**Comment by krcdxnh** [comment]
> 4.0.2 版本也还存在这个问题， 重置下 UserAgent 就好了

怎么重置
