### ISSUE TITLE
白屏

### ISSUE THREAD

**Issue by ZhiQiangCoding** [Justson/AgentWeb#347]
大神，加载vue出现白屏，而XWalkView有时白屏有时可以显示；

**Comment by Zhangxd77** [comment]
请问你解决了吗？？

**Comment by ZhiQiangCoding** [comment]
@a512509050 @Zhangxd77 没有，暂时使用加载一个进度条解决，还在找解决方案，你们有找到解决方案么

**Comment by owou123** [comment]
解决了吗，同样的链接，在4.4系统的手机上才出现白屏
