### ISSUE TITLE
onShowFileChooser 报错

### ISSUE THREAD

**Issue by Cornflower1991** [Justson/AgentWeb#35]
E/dalvikvm: Could not find class 'android.webkit.WebChromeClient$FileChooserParams', referenced from method com.just.library.DefaultChromeClient.onShowFileChooser
E/dalvikvm: Could not find class 'org.greenrobot.greendao.database.DatabaseOpenHelper$EncryptedHelper', referenced from method org.greenrobot.greendao.database.DatabaseOpenHelper.checkEncryptedHelper
E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering

**Comment by Justson** [comment]
`onShowFileChooser ` 找不到类？ 系统版本是多少呢？
