### ISSUE TITLE
android8.0的dispatchEvent事件页面跳转无效

### ISSUE THREAD

**Issue by qalong** [Justson/AgentWeb#352]
在开发过程中发现淘宝的一个页面上网页跳转有问题。https://h5.m.taobao.com/mtb/address.html

后来排查是js触发click事件页面跳转，在ndroid5.1的webview上正常，但是在android8.0上就会无响应。也不走shouldoverrideurl方法。

```
//js示例
var link = document.getElementById( 'link_to_click' ),
event = document.createEvent( 'HTMLEvents' );
event.initEvent( 'click', true, true );
link.dispatchEvent( event );
```

**Comment by jiaguoxinzhi** [comment]
var evt = doc.createEvent("HTMLEvents");//doc.createEvent("Events");// 
                        // 初始化 事件
                        evt.initEvent("BrigeReady", false, false);
                        //evt.eventType = 'message';
                        // 触发, 事件
                        doc.dispatchEvent(evt);
                        alert("dispatch");

我在android 5.1上执行上边的js无法触发 BrigeReady 事件 是哪里设置问题吗？
