### ISSUE TITLE
Android 小米4.4系统部分网页加载不出来

### ISSUE THREAD

**Issue by zhangtuodd** [Justson/AgentWeb#353]
linkUrl ： "http://hd.dev.cloud-young.cn/hdweb/lottery/#/prizedraw/OOP9EdrNC4IAqvOu"
 agentWeb = AgentWeb.with(this)
                .setAgentWebParent(webLayout, new LinearLayout.LayoutParams(-1, -1))
                .useDefaultIndicator(getResources().getColor(R.color.module_biz_activity_33394c), 1)
                .createAgentWeb()
                .ready()
                .go(linkUrl);
        WebSettings webSettings = agentWeb.getAgentWebSettings().getWebSettings();
        webSettings.setDomStorageEnabled(true);
        webSettings.setJavaScriptEnabled(true);
        webLayout.setBackgroundColor(Color.parseColor("#80000000"));
        agentWeb.getWebCreator().getWebParentLayout();

**Comment by zhangtuodd** [comment]
希望作者关注并给予提示！

**Comment by Zhangxd77** [comment]
你好，请问你怎么解决的啊

**Comment by zhangtuodd** [comment]
改用腾讯X5适配的
