### ISSUE TITLE
上方进度条未取消？加载到90%左右

### ISSUE THREAD

**Issue by jinhuizxc** [Justson/AgentWeb#355]
mAgentWeb = AgentWeb.with(this)
                .setAgentWebParent((LinearLayout) view, new LinearLayout.LayoutParams(-1, -1))                
                .useDefaultIndicator()
                .createAgentWeb()
                .ready()
                .go("http://www.jd.com");

url为自己的项目url，内容加载出来了，但是进度条未能取消，请问怎么取消进度条，谢谢，在线等！

**Comment by tt328307109** [comment]
请问解决了吗

**Comment by YxmCute** [comment]
> 请问解决了吗

我也遇到了，感觉是自己哪里写错了，当又找不到。

**Comment by tt328307109** [comment]
![image](https://user-images.githubusercontent.com/16999478/59733514-b6b07e80-9280-11e9-8623-ad3dc7a7f90a.png)
我的这个，这一行取消注释就解决了

**Comment by jinhuizxc** [comment]
将作者源码中的代码片段复制进去也可以解决：
 mAgentWeb = AgentWeb.with(this)
                .setAgentWebParent(linearLayout, new LinearLayout.LayoutParams(-1, -1))
                .useDefaultIndicator()
                .setWebChromeClient(mWebChromeClient)
                .setWebViewClient(mWebViewClient)
                .setMainFrameErrorView(R.layout.agentweb_error_page, -1)
                .setSecurityType(AgentWeb.SecurityType.STRICT_CHECK)
//                .setWebLayout(new WebLayout(this))
                .setOpenOtherPageWays(DefaultWebClient.OpenOtherPageWays.ASK)//打开其他应用时，弹窗咨询用户是否前往其他应用
                .interceptUnkownUrl() //拦截找不到相关页面的Scheme
                .createAgentWeb()
                .ready()
                .go(url);
