### ISSUE TITLE
点击进入新的web页面 然后返回后需要动态设置title  不然还是上个页面的title

### ISSUE THREAD

**Issue by perfunctory** [Justson/AgentWeb#36]

**Comment by Justson** [comment]
目前title是通过回调设置的 。 现在是返回页面，接口没有回调 ？

**Comment by a512509050** [comment]
1.2.3版本 返回页面接口没有回调应该怎么办

**Comment by a512509050** [comment]
我用了一个曲线救国的方法
`private List<String> mWebTitles = new ArrayList<>();`
`private ChromeClientCallbackManager.ReceivedTitleCallback mCallback = new ChromeClientCallbackManager.ReceivedTitleCallback() {
        @Override
        public void onReceivedTitle(WebView view, String title) {
            mWebTitles.add(title);
            toolbarTitle.setText(title);
        }
    };`
`@Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (mAgentWeb.handleKeyEvent(keyCode, event)) {
            if (mWebTitles.size() > 1) {
                mWebTitles.remove(mWebTitles.size() - 1);
                toolbarTitle.setText(mWebTitles.get(mWebTitles.size() - 1));
            }
            return true;
        }
        return super.onKeyDown(keyCode, event);
    }`

**Comment by zichen-jiao** [comment]
我的做法是在ILoader接口类中增加getTitle()接口。并在LoaderImpl中进行实现。
```
public interface ILoader {
…………
  String getTitle();
}

```

在LoaderImpl中实现

```
public class LoaderImpl implements ILoader {
…………
@Override
  public String getTitle() {
    return mWebView.getTitle();
  }
}
```

然后再WebViewClient->onPageFinished中进行主动调用。
