### ISSUE TITLE
混淆后无法显示网页

### ISSUE THREAD

**Issue by wmjwmj828** [Justson/AgentWeb#366]
-keep class com.just.agentweb.** {
    *;
}
-dontwarn com.just.agentweb.**

混淆规则加了。就很简单的在activity用agentWeb显示网页，混淆后就是无法加载
        AgentWeb.with(this)
                .setAgentWebParent(mLlContainer, new LinearLayout.LayoutParams(-1, -1))
                .useDefaultIndicator(getResources().getColor(R.color.light_blue))
                .setMainFrameErrorView(R.layout.agentweb_error_page, -1)
                .interceptUnkownUrl()
                .createAgentWeb()
                .ready()
                .go(url);

还需要加什么规则？那个Java注入类的规则没看懂，能解释下吗

**Comment by wmjwmj828** [comment]
不是混淆问题

**Comment by dary123** [comment]
我也是一样，不加混淆能显示
