### ISSUE TITLE
如何与SwipeRefreshLayout结合，使用AgentWebView吗

### ISSUE THREAD

**Issue by KKaKa** [Justson/AgentWeb#368]
如何与SwipeRefreshLayout结合下拉刷新页面时解决下拉动作的冲突

**Comment by Justson** [comment]
### Sample 有

**Comment by ooftf** [comment]
> ### Sample 有
Sample中没有找到，能否给个链接？

**Comment by abellee** [comment]
> ### Sample 有

你可以把这种无意义的回答 直接改成具体的链接
