### ISSUE TITLE
无法唤起支付宝app

### ISSUE THREAD

**Issue by TracyEminem** [Justson/AgentWeb#369]
示例app中，唯品会中选择支付宝支付无法唤起，支付宝app已经登陆。。。换了两台手机都是不可以，都是网页支付的支付宝

**Comment by TracyEminem** [comment]
好吧，看了下项目的很多issues下面作者都是没有回复，是不打算维护这个项目了吗？

**Comment by furochan** [comment]
> 示例app中，唯品会中选择支付宝支付无法唤起，支付宝app已经登陆。。。换了两台手机都是不可以，都是网页支付的支付宝

拦截url可以解决调不起支付宝app问题
