### ISSUE TITLE
你好，有什么方法可以监听到url的hash改变吗

### ISSUE THREAD

**Issue by HolickABC** [Justson/AgentWeb#37]
shouldOverrideUrlLoading()  这个拦截不到。。。

**Comment by Justson** [comment]
shouldOverrideUrlLoading() 您的意思是该方法不回调吗？

**Comment by HolickABC** [comment]
是的  然后我和前端的同事用js调用android的方法曲线解决了

**Comment by Justson** [comment]
shouldOverrideUrlLoading 该方法不是每次页面发生变化都会回调的哦。
