### ISSUE TITLE
下载安装判断版本有问题

### ISSUE THREAD

**Issue by Ahuanghaifeng** [Justson/AgentWeb#38]
AgentWebUtils里面getIntentCompat方法 if (Build.VERSION.SDK_INT >= 24) 这样才没问题。你之前的写法是在夜神模拟器上点击安装崩溃。
public static Intent getIntentCompat(Context context, File file) {
        Intent mIntent = null;
        LogUtils.i("Info", "getIntentCompat  :" + context.getApplicationInfo().targetSdkVersion);
        if (Build.VERSION.SDK_INT >= 24) {

            mIntent = new Intent(Intent.ACTION_VIEW);
            mIntent.setDataAndType(FileProvider.getUriForFile(context, context.getPackageName() + ".AgentWebFileProvider", file), "application/vnd.android.package-archive");
            mIntent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
        } else {

            mIntent = AgentWebUtils.getFileIntent(file);
        }

        return mIntent;
    }

**Comment by Justson** [comment]
请使用新版本
