### ISSUE TITLE
请教一下如何实现表单自动记忆账户

### ISSUE THREAD

**Issue by kslr** [Justson/AgentWeb#392]
我注意到每隔一段时间打开页面都需要重新填写账户，也没有自动填充。
这是我的代码
```java
mAgentWeb = AgentWeb.with(this)
                .setAgentWebParent(mLinearLayout, new LinearLayout.LayoutParams(-1, -1))
                .useDefaultIndicator()
                .setWebChromeClient(mWebChromeClient)
                .setPermissionInterceptor(mPermissionInterceptor)
                .createAgentWeb()
                .ready()
                .go("https://www.demo.com");
```
我应该从哪里下手？

**Comment by kslr** [comment]
我注意到如果允许了存储权限，那么就会保留回话状态了，难道是cookie关闭后被丢失的原因？

**Comment by AbrahamCaiJin** [comment]
请问你的解决了吗？

**Comment by kslr** [comment]
你好 @AbrahamCaiJin 

我发现webview在API18以后都不支持保存密码了。

https://github.com/Justson/AgentWeb/blob/master/agentweb-core/src/main/java/com/just/agentweb/AbsAgentWebSettings.java#L74
https://developer.android.com/reference/android/webkit/WebSettings#setSavePassword(boolean)
