### ISSUE TITLE
嵌套scrollview

### ISSUE THREAD

**Issue by sdgtwsf0115** [Justson/AgentWeb#396]
scrollview能不能嵌套agentweb,试了下如果webview嵌套到scrollview中,就显示不出来了,有没有方法可以嵌套,thanks

**Comment by zcm-hu** [comment]
我也遇到了同样的问题，请问下 你的解决了吗

**Comment by sdgtwsf0115** [comment]
使用agentWeb.setWebLayout(IWebLayout)方法可以实现webview跟随scrollview滑动, 但是我把webview加载的url设置成163或百度等网页,高度是自适应,但加载自己项目中的webview高度不会自适应,弹出框的位置是位于手机屏幕的中心,不会位于webview的中心,  不知道这个是我们的h5页面设置问题还是webview需要设置什么东西,暂时没有解决这个问题

**Comment by 505541778** [comment]
怎么解决的  ???

**Comment by 505541778** [comment]
@sdgtwsf0115 
mDuckWebView = AgentWeb.with(this)
                .setAgentWebParent((LinearLayout) mDuckWebviewParent, new LinearLayout.LayoutParams(-1, -1))
                .useDefaultIndicator()
                .setWebLayout(new IWebLayout() {
                    @NonNull
                    @Override
                    public ViewGroup getLayout() {
                        return null;
                    }

                    @Nullable
                    @Override
                    public WebView getWebView() {
                        return null;
                    }
                })
                .setWebChromeClient(mWebChromeClient)
                .setWebViewClient(mWebViewClient)
                .createAgentWeb()
                .ready()
                .go(TextUtils.isEmpty(getUrl) ? "http://192.168.3.43:8888/test-debug/test-zalyjs.html" : getUrl);
                .setWebViewClient(mWebViewClient)
                .createAgentWeb()
                .ready()
                .go(url);

**Comment by 505541778** [comment]
这样吗??

**Comment by 505541778** [comment]
但是这样 会报错啊  The specified child already has a parent. You must call removeView() on the child’s parent first.

**Comment by zcm-hu** [comment]
@505541778  你的IWebLayout实现类写错了吧
`public class AgentLayout implements IWebLayout<WebView, RelativeLayout> {

    private View mParentView;

    public AgentLayout(Context context) {
        mParentView = LayoutInflater.from(context).inflate(R.layout.layout_editor_agent, null);
    }

    @Override
    public RelativeLayout getLayout() {
        return (RelativeLayout) mParentView;
    }

    @Override
    public WebView getWebView() {
        return mParentView.findViewById(R.id.editor_view);
    }
}`

**Comment by LiChangXing** [comment]
能不能给个完整的  我用的 炸不对

**Comment by wangsong1991** [comment]
能跟recyclerview联动吗？Scrollview嵌套webview+recyclerview。
