### ISSUE TITLE
如何重置url里面的内容？

### ISSUE THREAD

**Issue by FynnJason** [Justson/AgentWeb#398]
问题描述：登录淘宝网页，返回退出activity，再进入，还是已登录的状态，请问怎么清除cookies？

**Comment by bananaCaptain** [comment]
@FynnJason 请问解决了没有，我也有这个需求，有人能解答一下怎样处理最好不？感谢

**Comment by Justson** [comment]
`AgentWebConfig.removeSessionCookies();`
