### ISSUE TITLE
设置useragent后，jsbridge不能交互了

### ISSUE THREAD

**Issue by lvandroid** [Justson/AgentWeb#403]
如题：EasyWebActivity 
  @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);
        this.context = this;
        setContentView(R.layout.activity_web);

        mAgentWeb.getAgentWebSettings().getWebSettings().setUserAgentString(USER_AGENT);
}

  mBridgeWebView.registerHandler() 注册的方法没有执行回调，如果不设置useragent就可以

**Comment by Justson** [comment]
建议
```
mWebSettings.setUserAgentString(getWebSettings()
				.getUserAgentString()
				.concat(USERAGENT_AGENTWEB)
				.concat(USERAGENT_UC)
		);
```

**Comment by walker113** [comment]
这样设置也是不行的？还有别的方式吗？
