### ISSUE TITLE
打开手机相册，只能打开一次，第二次调用打开手机相册失败

### ISSUE THREAD

**Issue by zhangyoupan** [Justson/AgentWeb#41]
红米2  系统5.1.1  AgentWeb版本1.2.4

**Comment by Justson** [comment]
系统版本 ， 手机型号 ，AgentWeb版本方便贴一下吗 ？

**Comment by HolickABC** [comment]
注意在onActivityResult里面加上这句代码：
agentWeb.uploadFileResult(requestCode, resultCode, data);
否则就会出现你这种情况，别问我怎么知道的。。。

**Comment by Justson** [comment]
楼上正解

**Comment by krcdxnh** [comment]
> 注意在onActivityResult里面加上这句代码：
> agentWeb.uploadFileResult(requestCode, resultCode, data);
> 否则就会出现你这种情况，别问我怎么知道的。。。
到底怎么用，求解
