### ISSUE TITLE
Failed resolution of: Lcom/alipay/sdk/app/H5PayCallback

### ISSUE THREAD

**Issue by 512439130** [Justson/AgentWeb#411]
DefaultWebClient貌似缺少包

**Comment by 512439130** [comment]
import com.alipay.sdk.app.H5PayCallback;
import com.alipay.sdk.app.PayTask;
import com.alipay.sdk.util.H5PayResultModel;

**Comment by 512439130** [comment]
找到了，要下载你sample中的libs下的文件alipaySdk-20170922.jar并导入

**Comment by Justson** [comment]
正常日志，可忽略 ， 忽略方式把Debug模式关掉可以了。
