### ISSUE TITLE
No WebView installed

### ISSUE THREAD

**Issue by piitw** [Justson/AgentWeb#414]
反馈一个问题：

android.webkit.WebViewFactory$MissingWebViewPackageException
Failed to load WebView provider: No WebView installed
com.just.agentweb.DefaultWebCreator.createWebView(DefaultWebCreator.java:240)

java.lang.RuntimeException:Unable to start activity ComponentInfo{---/---}: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed

android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3167)
Caused by:
android.webkit.WebViewFactory$MissingWebViewPackageException:Failed to load WebView provider: No WebView installed

设备：华为 CLT AL01  
版本：8.1

**Comment by bakkiraju** [comment]
Seeing the same issue, any idea on how to work around this

**Comment by Sole2016** [comment]
+1

**Comment by ChanNagihong** [comment]
+1

**Comment by methods2014** [comment]
try this
public class MyWebView extends WebView {

    @Override
    public void setOverScrollMode(int mode) {
        try {
            super.setOverScrollMode(mode);
        } catch (Exception e) {
            if (e.getMessage() != null && e.getMessage().contains("Failed to load WebView provider: No WebView installed")) {
                e.printStackTrace();
            } else {
                throw e;
            }
        }
    }
}

https://stackoverflow.com/questions/46048912/android-failed-to-load-webview-provider-no-webview-installed

**Comment by liweiGe** [comment]
![image](https://user-images.githubusercontent.com/25901728/117522583-d8d35700-afe6-11eb-8c04-1981f444e0ff.png)
应该是在该 LollipopFixedWebView 基类里改才对
