### ISSUE TITLE
下载apk文件，但是文件存在的话不会再次下载新的apk文件，而是直接跳转旧的apk文件安装页面，请问怎么每次下载都覆盖原本的文件？

### ISSUE THREAD

**Issue by LXLYHM** [Justson/AgentWeb#421]
您好，还有个问题：跟着demo写的下载apk文件，但是文件存在的话不会再次下载新的apk文件，而是直接跳转旧的apk文件安装页面，请问怎么每次下载都覆盖原本的文件？

**Comment by LXLYHM** [comment]
您好，发现是vivo androidV8.1.0一进入页面不会弹出权限允许框，所以一直是没权限，导致没法下载文件，请问怎么解决

**Comment by Justson** [comment]
Sample `extra.setOpenBreakPointDownload(true) ` 了解下
