### ISSUE TITLE
android8.0下载文件，声音会一直响

### ISSUE THREAD

**Issue by winner3811** [Justson/AgentWeb#425]
android8.0下载文件，声音会一直响，麻烦管理员看下怎么解决
一直响直到下载完成才没有声音，这样很烦人

**Comment by djjackylei** [comment]
同样碰到这个问题

**Comment by animus198656** [comment]
碰到同样的问题，你们解决了吗

**Comment by Justson** [comment]
[dev](https://github.com/Justson/AgentWeb/tree/dev) 已修复相关问题 ， 有兴趣的可以尝尝鲜。

**Comment by xu33liang33** [comment]
> [dev](https://github.com/Justson/AgentWeb/tree/dev) 已修复相关问题 ， 有兴趣的可以尝尝鲜。

4.0.2版本还是有 这个问题～能抽个方法关掉声音 吗？为啥我看到的 dev分支 的 东西比clone的少呢？

**Comment by xu33liang33** [comment]
> [dev](https://github.com/Justson/AgentWeb/tree/dev) 已修复相关问题 ， 有兴趣的可以尝尝鲜。

DownloadNotifier的80行～开启的声音～dev没看到相关文件呢～有抽出去了吗？

**Comment by Justson** [comment]
4.0.3 fixed
