### ISSUE TITLE
在Activity上通过Button设置不同的URL

### ISSUE THREAD

**Issue by L-bo** [Justson/AgentWeb#432]
在Activity上有两个Button,Button下面是webView,点击Button设置不同的url,但是下方的WebView不刷新,只能显示第一次默认显示的界面,AgentWebConfig.clearDiskCache(this);清理了缓存也不好用

**Comment by Justson** [comment]
检查下是否 是`mAgentWeb.getWebLifeCycle().onPause();` 影响了刷新

**Comment by L-bo** [comment]
将这行代码注释掉了也不刷新

**Comment by L-bo** [comment]
AgentWebConfig.clearDiskCache(this);如果使用了这行代码清理缓存退出的时候会闪屏
