### ISSUE TITLE
找不到AliPay

### ISSUE THREAD

**Issue by Ayvytr** [Justson/AgentWeb#434]
I/zygote: Rejecting re-init on previously-failed class java.lang.Class<com.just.agentweb.DefaultWebClient$1>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/alipay/sdk/app/H5PayCallback;
I/zygote:     at com.just.agentweb.DefaultWebClient$Builder com.just.agentweb.DefaultWebClient.createBuilder() (DefaultWebClient.java:622)
I/zygote:     at android.webkit.WebViewClient com.just.agentweb.AgentWeb.getWebViewClient() (AgentWeb.java:403)
I/zygote:     at com.just.agentweb.AgentWeb com.just.agentweb.AgentWeb.ready() (AgentWeb.java:457)
I/zygote:     at com.just.agentweb.AgentWeb com.just.agentweb.AgentWeb.access$3100(com.just.agentweb.AgentWeb) (AgentWeb.java:43)
I/zygote:     at com.just.agentweb.AgentWeb$PreAgentWeb com.just.agentweb.AgentWeb$PreAgentWeb.ready() (AgentWeb.java:325)
I/zygote:     at void com.ayvytr.webview.WebViewActivity.initAgentWeb() (WebViewActivity.java:70)
I/zygote:     at void com.ayvytr.webview.WebViewActivity.initView(android.os.Bundle) (WebViewActivity.java:83)
I/zygote:     at void com.ayvytr.mvp.BaseMvpActivity.onCreate(android.os.Bundle) (BaseMvpActivity.java:27)
I/zygote:     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7009)
I/zygote:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7000)
I/zygote:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1214)
I/zygote:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2731)
I/zygote:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2856)
I/zygote:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/zygote:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1589)
I/zygote:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
I/zygote:     at void android.os.Looper.loop() (Looper.java:164)
I/zygote:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
I/zygote:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
I/zygote:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
I/zygote: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.alipay.sdk.app.H5PayCallback" on path: DexPathList[[zip file "/data/app/com.ayvytr.gank-3aMca-CQllfod6teoc1YAw==/base.apk"],nativeLibraryDirectories=[/data/app/com.ayvytr.gank-3aMca-CQllfod6teoc1YAw==/lib/x86, /system/lib, /vendor/lib]]
I/zygote:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
I/zygote:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/zygote:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/zygote:     at com.just.agentweb.DefaultWebClient$Builder com.just.agentweb.DefaultWebClient.createBuilder() (DefaultWebClient.java:622)
I/zygote:     at android.webkit.WebViewClient com.just.agentweb.AgentWeb.getWebViewClient() (AgentWeb.java:403)
I/zygote:     at com.just.agentweb.AgentWeb com.just.agentweb.AgentWeb.ready() (AgentWeb.java:457)
I/zygote:     at com.just.agentweb.AgentWeb com.just.agentweb.AgentWeb.access$3100(com.just.agentweb.AgentWeb) (AgentWeb.java:43)
I/zygote:     at com.just.agentweb.AgentWeb$PreAgentWeb com.just.agentweb.AgentWeb$PreAgentWeb.ready() (AgentWeb.java:325)
I/zygote:     at void com.ayvytr.webview.WebViewActivity.initAgentWeb() (WebViewActivity.java:70)
I/zygote:     at void com.ayvytr.webview.WebViewActivity.initView(android.os.Bundle) (WebViewActivity.java:83)
I/zygote:     at void com.ayvytr.mvp.BaseMvpActivity.onCreate(android.os.Bundle) (BaseMvpActivity.java:27)
I/zygote:     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7009)
I/zygote:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7000)
I/zygote:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1214)
I/zygote:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2731)
I/zygote:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2856)
I/zygote:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/zygote:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1589)
I/zygote:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
I/zygote:     at void android.os.Looper.loop() (Looper.java:164)
I/zygote:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
I/zygote:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
I/zygote:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
I/zygote: Rejecting re-init on previously-failed class java.lang.Class<com.just.agentweb.DefaultWebClient$1>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/alipay/sdk/app/H5PayCallback;
I/zygote:     at com.just.agentweb.DefaultWebClient$Builder com.just.agentweb.DefaultWebClient.createBuilder() (DefaultWebClient.java:622)
I/zygote:     at android.webkit.WebViewClient com.just.agentweb.AgentWeb.getWebViewClient() (AgentWeb.java:403)
I/zygote:     at com.just.agentweb.AgentWeb com.just.agentweb.AgentWeb.ready() (AgentWeb.java:457)
I/zygote:     at com.just.agentweb.AgentWeb com.just.agentweb.AgentWeb.access$3100(com.just.agentweb.AgentWeb) (AgentWeb.java:43)
I/zygote:     at com.just.agentweb.AgentWeb$PreAgentWeb com.just.agentweb.AgentWeb$PreAgentWeb.ready() (AgentWeb.java:325)
I/zygote:     at void com.ayvytr.webview.WebViewActivity.initAgentWeb() (WebViewActivity.java:70)
I/zygote:     at void com.ayvytr.webview.WebViewActivity.initView(android.os.Bundle) (WebViewActivity.java:83)
I/zygote:     at void com.ayvytr.mvp.BaseMvpActivity.onCreate(android.os.Bundle) (BaseMvpActivity.java:27)
I/zygote:     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7009)
I/zygote:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7000)
I/zygote:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1214)
I/zygote:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2731)
I/zygote:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2856)
I/zygote:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/zygote:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1589)
I/zygote:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
I/zygote:     at void android.os.Looper.loop() (Looper.java:164)
I/zygote:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
I/zygote:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
I/zygote:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
I/zygote: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.alipay.sdk.app.H5PayCallback" on path: DexPathList[[zip file "/data/app/com.ayvytr.gank-3aMca-CQllfod6teoc1YAw==/base.apk"],nativeLibraryDirectories=[/data/app/com.ayvytr.gank-3aMca-CQllfod6teoc1YAw==/lib/x86, /system/lib, /vendor/lib]]
I/zygote:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
I/zygote:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/zygote:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/zygote:     at com.just.agentweb.DefaultWebClient$Builder com.just.agentweb.DefaultWebClient.createBuilder() (DefaultWebClient.java:622)
I/zygote:     at android.webkit.WebViewClient com.just.agentweb.AgentWeb.getWebViewClient() (AgentWeb.java:403)
I/zygote:     at com.just.agentweb.AgentWeb com.just.agentweb.AgentWeb.ready() (AgentWeb.java:457)
I/zygote:     at com.just.agentweb.AgentWeb com.just.agentweb.AgentWeb.access$3100(com.just.agentweb.AgentWeb) (AgentWeb.java:43)
I/zygote:     at com.just.agentweb.AgentWeb$PreAgentWeb com.just.agentweb.AgentWeb$PreAgentWeb.ready() (AgentWeb.java:325)
I/zygote:     at void com.ayvytr.webview.WebViewActivity.initAgentWeb() (WebViewActivity.java:70)
I/zygote:     at void com.ayvytr.webview.WebViewActivity.initView(android.os.Bundle) (WebViewActivity.java:83)
I/zygote:     at void com.ayvytr.mvp.BaseMvpActivity.onCreate(android.os.Bundle) (BaseMvpActivity.java:27)
I/zygote:     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7009)
I/zygote:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7000)
I/zygote:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1214)
I/zygote:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2731)
I/zygote:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2856)
I/zygote:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/zygote:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1589)
I/zygote:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
I/zygote:     at void android.os.Looper.loop() (Looper.java:164)
I/zygote:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
I/zygote:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
I/zygote:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
I/zygote: Rejecting re-init on previously-failed class java.lang.Class<com.just.agentweb.DefaultWebClient$1>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/alipay/sdk/app/H5PayCallback;
I/zygote:     at com.just.agentweb.DefaultWebClient$Builder com.just.agentweb.DefaultWebClient.createBuilder() (DefaultWebClient.java:622)
I/zygote:     at android.webkit.WebViewClient com.just.agentweb.AgentWeb.getWebViewClient() (AgentWeb.java:403)
I/zygote:     at com.just.agentweb.AgentWeb com.just.agentweb.AgentWeb.ready() (AgentWeb.java:457)
I/zygote:     at com.just.agentweb.AgentWeb com.just.agentweb.AgentWeb.access$3100(com.just.agentweb.AgentWeb) (AgentWeb.java:43)
I/zygote:     at com.just.agentweb.AgentWeb$PreAgentWeb com.just.agentweb.AgentWeb$PreAgentWeb.ready() (AgentWeb.java:325)
I/zygote:     at void com.ayvytr.webview.WebViewActivity.initAgentWeb() (WebViewActivity.java:70)
I/zygote:     at void com.ayvytr.webview.WebViewActivity.initView(android.os.Bundle) (WebViewActivity.java:83)
I/zygote:     at void com.ayvytr.mvp.BaseMvpActivity.onCreate(android.os.Bundle) (BaseMvpActivity.java:27)
I/zygote:     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7009)
I/zygote:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7000)
I/zygote:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1214)
I/zygote:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2731)
I/zygote:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2856)
I/zygote:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/zygote:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1589)
I/zygote:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
I/zygote:     at void android.os.Looper.loop() (Looper.java:164)
I/zygote:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
I/zygote:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
I/zygote:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)
I/zygote: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.alipay.sdk.app.H5PayCallback" on path: DexPathList[[zip file "/data/app/com.ayvytr.gank-3aMca-CQllfod6teoc1YAw==/base.apk"],nativeLibraryDirectories=[/data/app/com.ayvytr.gank-3aMca-CQllfod6teoc1YAw==/lib/x86, /system/lib, /vendor/lib]]
I/zygote:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
I/zygote:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/zygote:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/zygote:     at com.just.agentweb.DefaultWebClient$Builder com.just.agentweb.DefaultWebClient.createBuilder() (DefaultWebClient.java:622)
I/zygote:     at android.webkit.WebViewClient com.just.agentweb.AgentWeb.getWebViewClient() (AgentWeb.java:403)
I/zygote:     at com.just.agentweb.AgentWeb com.just.agentweb.AgentWeb.ready() (AgentWeb.java:457)
I/zygote:     at com.just.agentweb.AgentWeb com.just.agentweb.AgentWeb.access$3100(com.just.agentweb.AgentWeb) (AgentWeb.java:43)
I/zygote:     at com.just.agentweb.AgentWeb$PreAgentWeb com.just.agentweb.AgentWeb$PreAgentWeb.ready() (AgentWeb.java:325)
I/zygote:     at void com.ayvytr.webview.WebViewActivity.initAgentWeb() (WebViewActivity.java:70)
I/zygote:     at void com.ayvytr.webview.WebViewActivity.initView(android.os.Bundle) (WebViewActivity.java:83)
I/zygote:     at void com.ayvytr.mvp.BaseMvpActivity.onCreate(android.os.Bundle) (BaseMvpActivity.java:27)
I/zygote:     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7009)
I/zygote:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7000)
I/zygote:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1214)
I/zygote:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2731)
I/zygote:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2856)
I/zygote:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/zygote:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1589)
I/zygote:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
I/zygote:     at void android.os.Looper.loop() (Looper.java:164)
I/zygote:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6494)
I/zygote:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
I/zygote:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:807)

**Comment by Justson** [comment]
正常日志
