### ISSUE TITLE
Bug 反馈

### ISSUE THREAD

**Issue by piitw** [Justson/AgentWeb#436]
调用agentWeb.clearWebCache();
报错：
 java.lang.OutOfMemoryError
EnsureLocalCapacity
com.just.agentweb.AgentWebUtils.clearWebViewAllCache(AgentWebUtils.java:443)

设备机型
小米 MIX 2

系统版本
Android 8.0.0,level 26

ROM
XiaoMi/MIUI

CPU架构
arm64-v8a

**Comment by Apeplan** [comment]
前后台状态：前台
设备机型：三星 SM G9500
系统版本：Android 8.0.0,level 26
ROM：samsung/dreamqltezc
CPU架构：arm64-v8a

也遇到了同样的问题
