### ISSUE TITLE
建议暴露一个loadData方法

### ISSUE THREAD

**Issue by EricMo** [Justson/AgentWeb#443]
虽然在创建AgentWeb以后，可以通过mAgentWeb.urlLoader.loadData来加载html源码。
`mAgentWeb.urlLoader.loadData(webDataSource, "text/html; charset=UTF-8", null)`
但是由于AgentWeb的对象是通过go()方法来暴露的。
```
public static class PreAgentWeb {
		private AgentWeb mAgentWeb;
		private boolean isReady = false;

		PreAgentWeb(AgentWeb agentWeb) {
			this.mAgentWeb = agentWeb;
		}


		public PreAgentWeb ready() {
			if (!isReady) {
				mAgentWeb.ready();
				isReady = true;
			}
			return this;
		}

		public AgentWeb go(@Nullable String url) {
			if (!isReady) {
				ready();
			}
			return mAgentWeb.go(url);
		}


	}
```
于是现在就存在一个问题，我想加载html源码，我就必须先go("")（产生A页面）一次获取到AgentWeb对象，然后再调用loadData去加载源码（产生B页面）。虽然在视觉上面没问题，但是我点击返回的时候，他会从B页面返回到空白的A页面，这样不怎么友好。
时间上面有点紧，源码没看仔细，如果说错了，还是希望指正一下。

**Comment by gavinxxxxxx** [comment]
+1

**Comment by wu21731** [comment]
同问

**Comment by zealot2002** [comment]
+1

**Comment by Justson** [comment]
下个版本

**Comment by czhmike123** [comment]
暂时解决办法:从PreAgent 中用反射获取到AgentWeb对象,不走go(url),就不会出现这个问题

**Comment by EricMo** [comment]
@czhmike123 这也是个办法，我是直接把源码clone下来，然后自己暴露个方法。
既然作者说下个版本会考虑，我先把这个issue close了。

**Comment by StayZeal** [comment]
下个版本什么时候出啊？

**Comment by hailongfeng** [comment]
+1，我也用的这个方式，小米手机出现中文乱码的现象

**Comment by bill198907** [comment]
+1

**Comment by AdminQQZ** [comment]
哎呀，我就疑惑，为什么返回最后一层有一个空白！！！！我还以为与jetpack compose声明周期有问题
