### ISSUE TITLE
我需要在每个url的请求中添加自定义head数据

### ISSUE THREAD

**Issue by cschenzz** [Justson/AgentWeb#446]
比如我需要在一个app访问的页面添加token校验码到head头,这样服务器可以验证请求的页面是否授权
现在AgentWeb支持设置Head内容吗?

**Comment by ITzhangyan** [comment]
@cschenzz 请问解决了么？如何添加token到head

**Comment by cschenzz** [comment]
没有解决,我直接用原始的webview了

**Comment by LEMON521** [comment]
@cschenzz @ITzhangyan 
重写
WebViewClient.shouldInterceptRequest
在WebResourceRequest里面添加
