### ISSUE TITLE
不支持 accept="image/*" capture="camera" 打开相机

### ISSUE THREAD

**Issue by zxq9133** [Justson/AgentWeb#46]
大概看了下代码，发现onShowFileChooser 里的 FileChooserParams 也没有capture属性，只有个captureEnabled。这种的不能打开相机的要怎么处理，我看用UC浏览器可以打开，是不是跟浏览器内核有关？

**Comment by Justson** [comment]
非常感谢你的反馈，input 标签 type=file ，打开文件选择器是合适的 ，  但是挺多人有打开相机的需求 ，后续可能会加入该功能。

**Comment by huanghaobiu** [comment]
这个功能其实挺多的内勤的app或者安全限定的app需要这个功能的，我们现在有个需求就是只能拍照，不能选择图片，安全部门的要求
