### ISSUE TITLE
Call requires API level 21, android.webkit.WebResourceRequest#getUrl()

### ISSUE THREAD

**Issue by hanxuhui** [Justson/AgentWeb#47]
AgentWebFragment类中内部类WebViewClient中方法
        @Override
        public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request) {
            return shouldOverrideUrlLoading(view, request.getUrl() + "");
        }
报错，只支持21以上的、

**Comment by Justson** [comment]
编译报错吗？
