### ISSUE TITLE
奇酷 8861-A01 android  5.1 API-22 白屏

### ISSUE THREAD

**Issue by native2012** [Justson/AgentWeb#475]
奇酷 8861-A01 android  5.1 API-22 白屏  加载不出来不知道为什么！  H5 是VUe写的，

**Comment by yc654084303** [comment]
我也遇到拉，魅蓝m1 api22

**Comment by yc654084303** [comment]
请问解决啦嘛

**Comment by iteyelmp** [comment]
同问，前几天都正常的，突然就不行了。浏览器等等打开都正常，但是AgentWeb打开一片空白。在sample里面写死地址打开也是空白。

**Comment by ZxGump** [comment]
同问,h5页面加载不出来,比如:https://h5.vip.youku.com/
