### ISSUE TITLE
百度统计可视化圈选埋点sdk和AgetnWeb一起用出现不走mWebChromeClient事件，请问怎么解决？

### ISSUE THREAD

**Issue by LXLYHM** [Justson/AgentWeb#477]
百度统计SDK使用这句话：StatService.trackWebView(getContext(), mWebView, mWebChromeClient);影响了AgetnWeb的加载进度条useDefaultIndicator不消失，一直存在。更过分的是文件上传库com.just.agentweb:filechooser:4.0.2也没反应了，但是两个库都是必须要用的，请问能不能有办法解决？

**Comment by LXLYHM** [comment]
可视化圈选sdk安卓接入步骤：https://mtj.baidu.com/static/userguide/book/chapter4/circle.html

**Comment by xm2017** [comment]
你看自己是不是重写 这个方法时没有returm super？因为父类中有判断，子类重写就不再处理。

**Comment by LXLYHM** [comment]
后面没用百度统计了，冲突比较麻烦。谢谢大佬抽空回复我

**Comment by LXLYHM** [comment]
大佬，后台使用layui.upload，调取不到com.just.agentweb:filechooser:4.0.2中的文件和相机弹窗，这有办法解决吗？
