### ISSUE TITLE
文件上传时的requestCode

### ISSUE THREAD

**Issue by XYScience** [Justson/AgentWeb#49]
你好，文件上传时，选择一个文件比如图片后，会在onActivityResult里调用uploadFileResult上传图片，那这个requestCode是多少呢？是否可以暴露出来？

**Comment by Justson** [comment]
您好 ， 这个问题自己打印一下得到的答案是否更加快速呢 ？  `private static final int REQUEST_CODE = 0x254;`

**Comment by XYScience** [comment]
谢谢。我通过你的源码找到这个code。我是想为什么不能把 REQUEST_CODE 的作用域改为public呢？
