### ISSUE TITLE
use agentweb to open 'onlinemictest.com', no authority when trying to Record

### ISSUE THREAD

**Issue by cacorot** [Justson/AgentWeb#494]
1. open "onlinemictest.com"
2. click to start recording
3. it gives me 'Microphone not authorizated. Please check your media permissions settings'
When I use a browser to open it and click, a dialog will pop-up telling me to choose 'allow'. But no response in agentWeb.
I have tried to add permissions in AndroidManifest.xml. But still not available, could you please give me some advices.

**Comment by cacorot** [comment]
I have addressed this issue, thank you for your watching.

    public WebChromeClient webviewClient = new WebChromeClient() {
        @Override
        public void onPermissionRequest(final PermissionRequest request) {
            myRequest = request;
            for (String permission : request.getResources()) {
                switch (permission) {
                    case "android.webkit.resource.AUDIO_CAPTURE": {
                        askForPermission(request.getOrigin().toString(), Manifest.permission.RECORD_AUDIO, MY_PERMISSIONS_REQUEST_RECORD_AUDIO);
                        break;
                    }
                    case "android.webkit.resource.VIDEO_CAPTURE": {
                        askForPermission(request.getOrigin().toString(), Manifest.permission.CAMERA, MY_PERMISSIONS_REQUEST_CAMERA);
                        break;
                    }
                }
            }
        }
    };

**Comment by loyilin** [comment]
+1
