### ISSUE TITLE
如何取消上部进度条 

### ISSUE THREAD

**Issue by Danniel-yan** [Justson/AgentWeb#497]
如何取消上部进度条

**Comment by s102213039** [comment]
.useDefaultIndicator(int color, int height_dp)  把height_dp設成0就可以了

**Comment by Danniel-yan** [comment]
好的 谢谢回复发自我的iPhone------------------ 原始邮件 ------------------发件人: Y.Y. Chiu  <notifications@github.com>发送时间: 2019年3月5日 13:47收件人: Justson/AgentWeb <AgentWeb@noreply.github.com>抄送: Daniel_yan <yshr1991@163.com>, Author <author@noreply.github.com>主题: 回复：[Justson/AgentWeb] 如何取消上部进度条  (#497).useDefaultIndicator(int color, int height_dp)  把height_dp設成0就可以了

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Justson/AgentWeb","title":"Justson/AgentWeb","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Justson/AgentWeb"}},"updates":{"snippets":[{"icon":"PERSON","message":"@s102213039 in #497: .useDefaultIndicator(int color, int height_dp)  把height_dp設成0就可以了"}],"action":{"name":"View Issue","url":"https://github.com/Justson/AgentWeb/issues/497#issuecomment-469547427"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Justson/AgentWeb/issues/497#issuecomment-469547427",
"url": "https://github.com/Justson/AgentWeb/issues/497#issuecomment-469547427",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by xm2017** [comment]
我也遇到了 你看看是不是重写中间件的onprogresschange方法，没有return  super？？这个库在父类有判断是否重写该方法，有就不处理默认设置
