### ISSUE TITLE
请问agentweb不能在一个activity页面二次加载吗？

### ISSUE THREAD

**Issue by AbrahamCaiJin** [Justson/AgentWeb#501]
activity第一次加载mAgentWeb = AgentWeb.with(this)
                                    .setAgentWebParent(linearLayout, new LinearLayout.LayoutParams(-1, -1))
                                    .useDefaultIndicator()
                                    .createAgentWeb()
                                    .ready()
                                    .go(Url);
然后用户在操作网页一段时间后，点击activity的首页按钮，我用的是同样的方法来加载，没反应

**Comment by AbrahamCaiJin** [comment]
然后我是这样才能重新加载：mAgentWeb.getWebCreator().getWebView().loadUrl(homeUrl);

**Comment by Justson** [comment]
新版的`get()`方法已暴露

**Comment by ChenJia-X** [comment]
请问，怎么能够清除之前加载的网页？
尝试了好几种方法都无效：
1. 判断是否canGoBack，如果可以则goBack，再加载
2. 使用loadUrl("about:blank")清除，再加载

加载url的方式分别尝试了
`webView.urlLoader.loadUrl(url)`
和
`webView.webCreator.webView.loadUrl(url)`
均无法实现先清除再加载的需求，同时使用loadUrl("about:blank")也无法清除网页。

还有一个奇怪的地方，第二次调用loadUrl(url)，会出现返回栈最上层的网页是第一次加载的网页，返回栈下层的是第二次加载的网页

**Comment by andoter0501** [comment]
解决了吗

**Comment by Tang3210** [comment]
我这边这样可以解决
mAgentWeb?.webCreator?.webView?.loadUrl(webUrl)
        lifecycleScope.launch {
            delay(200)
            mAgentWeb?.webCreator?.webView?.reload()
        }
