### ISSUE TITLE
H5如何调用Android本地文件 js写了没有反应

### ISSUE THREAD

**Issue by Danniel-yan** [Justson/AgentWeb#507]
H5如何调用Android本地文件 js写了没有反应

**Comment by penghao1** [comment]
最近我也出现了这个问题

**Comment by huangjianfeng1** [comment]
有解决办法没

**Comment by BeforeFuture** [comment]
按照作者的指示操作，
//Android 端 ， AndroidInterface 是一个注入类 ，里面有一个无参数方法：callAndroid
mAgentWeb.getJsInterfaceHolder().addJavaObject("**android**",new AndroidInterface(mAgentWeb,this));
这里面传入的“android”要和下面那个window.后面的一致。
//在 Js 里就能通过
window.**android**.callAndroid() //调用 Java 层的 AndroidInterface 类里 callAndroid 方法
然后callAndroid 方法也要一致，如果有传参数，就在callAndroid后面的（）里把参数加进去。
