### ISSUE TITLE
AgentWeb内嵌在RecycleView，此时播放视频不能全屏，已经按照WiKi设置也不行

### ISSUE THREAD

**Issue by wanlinruo** [Justson/AgentWeb#513]
首先感谢作者，这个WebView库是目前开源基本最好用的，感谢感谢。
问题如题，内嵌时候不能全屏，无论是b站视频还是优酷视频亦是如此。
但是当AgentWeb作为独立页面时候，按照WiKi设置是可以播放视频全屏的。
其中缘由希望大佬能解答，感谢感谢。 @Justson

**Comment by Justson** [comment]
不建议这样嵌套使用
