### ISSUE TITLE
android.view.WindowManager$BadTokenException 

### ISSUE THREAD

**Issue by a2203611** [Justson/AgentWeb#521]
具体报错的代码 ：Unable to add window -- token android.os.BinderProxy@9203665 is not valid; is your activity running?
com.just.agentweb.DefaultUIController.onOpenPagePrompt(DefaultUIController.java)
看了一下源码  onOpenPagePrompt showChooserInternal 这两个方法都没有对mactivity的判断  
 这个是不是应该修复一下    或者是应该怎么处理一下 项目一直存在这个问题 但是还没法复现！！！

**Comment by Justson** [comment]
已修复
