### ISSUE TITLE
在小米手机上中文显示乱码

### ISSUE THREAD

**Issue by hailongfeng** [Justson/AgentWeb#530]
这样直接使用，加载内容，不是URL的，agentWeb.getUrlLoader().loadData(introduce,"text/html","UTF-8");

**Comment by PiPiCaptain** [comment]
我也遇到这情况，公司十几台测试机，有一台测试机出现了这情况，其它都没问题

**Comment by PiPiCaptain** [comment]
@hailongfeng 我解决了，这个问题跟AgentWeb没什么关系。把 loadData 改为 loadDataWithBaseURL 就可以了。
