### ISSUE TITLE
怎么加载Html

### ISSUE THREAD

**Issue by YuLingRui** [Justson/AgentWeb#538]
private String mUrl = "http://192.168.88.30:9182/IMS/ims/previewOnline/2019/201904/1555642137093.html";
    private LinearLayout webLayout;
    private AgentWeb mAgentWeb;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        webLayout = findViewById(R.id.webview);
        NestedScrollAgentWebView webView = new NestedScrollAgentWebView(this);
        mAgentWeb = AgentWeb.with(this)
                .setAgentWebParent(webLayout, new LinearLayout.LayoutParams(-1, -1))//传入AgentWeb 的父控件 ，如果父控件为 RelativeLayout ， 那么第二参数需要传入 RelativeLayout.LayoutParams
                .useDefaultIndicator()
                .setWebView(webView)// 使用默认进度条
                .createAgentWeb()
                .go("");
        mAgentWeb.getUrlLoader().loadData(mUrl, "text/html; charset=UTF-8", null);
    }
我是这样写的。但是加载不出来。 请问有没有例子可以看看

**Comment by Justson** [comment]
看下'Sample'

**Comment by YuLingRui** [comment]
我看了Sample 都是加载一个url的，我把url换成了html后加载失败了。  我加载的html不是本地的。




------------------ 原始邮件 ------------------
发件人: "Justson"<notifications@github.com>;
发送时间: 2019年4月19日(星期五) 下午2:12
收件人: "Justson/AgentWeb"<AgentWeb@noreply.github.com>;
抄送: "安东尼"<1307444320@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Justson/AgentWeb] 怎么加载Html (#538)




看下'Sample'

**Comment by YuLingRui** [comment]
搞出来了。谢谢楼主------------------ 原始邮件 ------------------
发件人: "Justson"<notifications@github.com>
发送时间: 2019年4月19日(星期五) 下午2:12
收件人: "Justson/AgentWeb"<AgentWeb@noreply.github.com>;
抄送: "AntonyYu"<1307444320@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Justson/AgentWeb] 怎么加载Html (#538)



Closed #538.
 
&mdash;
