### ISSUE TITLE
使用自定义WebSettings后，加载url的时候会默认调用手机浏览器，请问怎么阻止这种情况？

### ISSUE THREAD

**Issue by Movement123** [Justson/AgentWeb#539]
public class CustomSettings extends AgentWebSettingsImpl  {

    @Override
    public IAgentWebSettings toSetting(WebView webView) {
        super.toSetting(webView);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
            // 通过 file url 加载的 Javascript 读取其他的本地文件 .建议关闭
            getWebSettings().setAllowFileAccessFromFileURLs(false);
            // 允许通过 file url 加载的 Javascript 可以访问其他的源，包括其他的文件和 http，https 等其他的源
            getWebSettings().setAllowUniversalAccessFromFileURLs(false);
        }
        return this;
    }

}
![4A11F4205DB5021C7832855CE8C40CF2](https://user-images.githubusercontent.com/11785562/56417813-ace1bd80-62c7-11e9-8977-5fff77bed7e4.jpg)

**Comment by kingning1** [comment]
你加这两项在源码里有，你如果想跨源最好在它go完之后
mAgentWeb.getAgentWebSettings().getWebSettings().setAllowFileAccessFromFileURLs(true);
这样绕过

**Comment by Movement123** [comment]
多谢指点
