### ISSUE TITLE
sample中的shouldOverrideUrlLoading方法怎么监听不到，原生webview是可以拦截到的，请问如何拦截点击的页面链接？

### ISSUE THREAD

**Issue by ZevShiShi** [Justson/AgentWeb#547]
如题

**Comment by ZevShiShi** [comment]
参考sample已解决

**Comment by changshuai7** [comment]
试了，最新的sample依然shouldOverrideUrlLoading方法怎么监听不到。。。。请问如何解决？

**Comment by ZevShiShi** [comment]
> 试了，最新的sample依然shouldOverrideUrlLoading方法怎么监听不到。。。。请问如何解决？

参考sample，通过这个MiddlewareWebClientBase来监听

**Comment by changshuai7** [comment]
环境：
1.最新的4.0.3-alpha
2.master分支的Sample
3.小米MAX2 Android7.1.1

Sample中。无论是.setWebViewClient(mWebViewClient)还是.useMiddlewareWebClient(getMiddlewareWebClient())，其中shouldOverrideUrlLoading(WebView view, String url) 方法始终监听不到，不执行。
刚试过了，sample就有这样问题。

**Comment by ZevShiShi** [comment]
> 环境：
> 1.最新的4.0.3-alpha
> 2.master分支的Sample
> 3.小米MAX2 Android7.1.1
> 
> Sample中。无论是.setWebViewClient(mWebViewClient)还是.useMiddlewareWebClient(getMiddlewareWebClient())，其中shouldOverrideUrlLoading(WebView view, String url) 方法始终监听不到，不执行。
> 刚试过了，sample就有这样问题。

getMiddlewareWebClient()用这个

**Comment by changshuai7** [comment]
我觉得这个应该是bug，更换回4.0.2以后一切正常。不过依然感谢。
