### ISSUE TITLE
shouldOverrideUrlLoading方法监听不到

### ISSUE THREAD

**Issue by changshuai7** [Justson/AgentWeb#552]
环境：
1.最新的4.0.3-alpha
2.master分支的Sample
3.小米MAX2 Android7.1.1

Sample中。无论是.setWebViewClient(mWebViewClient)还是.useMiddlewareWebClient(getMiddlewareWebClient())，其中shouldOverrideUrlLoading(WebView view, String url) 方法始终监听不到，不执行。这是什么问题呢？

**Comment by changshuai7** [comment]
我觉得这个应该是bug，更换回4.0.2以后一切正常。

**Comment by cdcdec** [comment]
如题，当H5设置下拉回弹以后，会有滑动冲突。
举个例子，这是我们公司的一个H5地址：https://hyd.hengchang6.com/jsd/static/html/zhongyidaiLoan/index.html
H5页面中间有个选择城市的控件。
此链接在微信、QQ中打开，城市选择的控件和下拉回弹不冲突，但是在AgentWeb中却有冲突。


这个问题找到解决办法了没有呀？

**Comment by nihaohebin** [comment]
> 我觉得这个应该是bug，更换回4.0.2以后一切正常。

这个有两个重载，高版本和低版本回调会不同。你看看。之前我也遇到过

**Comment by LnLooFa** [comment]
我也遇到了同样的问题..shouldOverrideUrlLoading方法不执行..走不到这个方法里面..2个不同参数的都打印了日志.都没走进去.最新版本(4.1.4)的...
