### ISSUE TITLE
自定义WebChromeClient和WebViewClient无效

### ISSUE THREAD

**Issue by Yuloran** [Justson/AgentWeb#563]
`.setWebChromeClient(mWebChromeClient).setWebViewClient(mWebViewClient)`
无效，因为源码的 DefaultWebChromeClient 没有对传入的 mWebChromeClient 进行任何调用。

规避方法：
`.useMiddlewareWebChrome(mWebChromeClient).useMiddlewareWebClient(mWebViewClient)`
这个会先调用 mWebChromeClient 中的方法，再调用父类的方法，这样就不影响进度条的绘制了

**Comment by Justson** [comment]
新版不支持 WebChromeClient和WebViewClient
