### ISSUE TITLE
重新加载页面后如何直接退出页面？

### ISSUE THREAD

**Issue by zhaoxiuyu** [Justson/AgentWeb#576]
我在返回的时候 使用的是下面的代码 ： 
        if (!mAgentWeb.back()) {
            WebViewActivity2.this.finish();
        }
在同一个网页内点击跳转 是可以 返回上一个页面的，直至退出页面，没问题。

现在的问题是 如果我重新加载 新的页面， 这个时候在返回 ，就是返回上一次加载的页面了，重新加载了网页 如何直接退出呢？
mAgentWeb.getUrlLoader().loadUrl(getUrl());

**Comment by Justson** [comment]
拦截

**Comment by zhaoxiuyu** [comment]
@Justson  怎么拦截？
