### ISSUE TITLE
HTC one X 4.1.1 京东商城网页布局错乱

### ISSUE THREAD

**Issue by xfmax** [Justson/AgentWeb#59]
![screenshot-2017-07-19_17 06 34 256](https://user-images.githubusercontent.com/11729753/28359420-b635ccfc-6ca4-11e7-995d-bb6e0db5559f.png)

**Comment by xfmax** [comment]
toSetting中的这句mWebSettings.setLayoutAlgorithm(android.webkit.WebSettings.LayoutAlgorithm.SINGLE_COLUMN);导致了布局错乱

**Comment by Justson** [comment]
非常感谢你的反馈 。 已经修复~
