### ISSUE TITLE
使用AgentWeb加载vue界面，输入框会被键盘遮挡

### ISSUE THREAD

**Issue by ych1147471053** [Justson/AgentWeb#593]
输入框如果低于键盘高度的时候，点击输入框将被遮挡，不能自动上移，需要手动向上滑动。

**Comment by zjw-swun** [comment]
@ych1147471053 https://www.imooc.com/article/284995

**Comment by zhangguannan** [comment]
> @ych1147471053 https://www.imooc.com/article/284995

无用
