### ISSUE TITLE
发现一个setMainFrameErrorView的bug

### ISSUE THREAD

**Issue by bailibaili** [Justson/AgentWeb#594]
首先断网，显示错误页面之后，再开启网络，点击刷新之后错误页面不会隐藏，以上

**Comment by ZevShiShi** [comment]
> 首先断网，显示错误页面之后，再开启网络，点击刷新之后错误页面不会隐藏，以上
我也有这种情况，请问你怎么解决的

**Comment by Justson** [comment]
super.onPageStarted(view, url, favicon); 加上

**Comment by bailibaili** [comment]
> super.onPageStarted(view, url, favicon); 加上

额，别关啊，亲测无效，不管是MiddlewareWebClientBase添加还是WebViewClient添加都没有作用

**Comment by Justson** [comment]
MiddlewareWebClientBase ,WebViewClient都要加上
```
super.onPageStarted(view, url, favicon);
```
输出log 看是不是onPageStart没有执行， 被中断了

**Comment by bailibaili** [comment]
![1565337415868](https://user-images.githubusercontent.com/17978389/62763580-7c17d500-babe-11e9-97e6-0cf25ec79211.jpg)
确实凉类都重写了，也都打印了日志
前两个是没网络时
后两个是启用网络后，而且实际内容已经请求到了，只不过被这个错误页面遮住了

**Comment by 17606677790** [comment]
我也遇到这个问题,现在有办法结局了吗?

**Comment by chuan1228** [comment]
我也是遇到这个问题了，用demo后测试onPageStart方法确实执行了，然后错误页面并没有消失

**Comment by owenxiao-AS** [comment]
> > super.onPageStarted（view，url，favicon）; 加上
> 
> 额，别关啊，亲测无效，不管是MiddlewareWebClientBase添加还是WebViewClient添加都没有作用
 .interceptUnkownUrl()这个加上试试

**Comment by ZevShiShi** [comment]
我升级到4.1.3就好了，把作者上面写的super都调用上就好了

**Comment by owenxiao-AS** [comment]
登录facebook  下一次打开自动登录并进入facebook主页  然后在webview  facebook的主界面返回几次才能返回到fragment 这个怎么回事啊

**Comment by ZevShiShi** [comment]
有重定向，你百度下把，有人解决过

**Comment by owenxiao-AS** [comment]
谢谢

> 有重置，你百度下把，有人解决过

找了好久  没看到啊

**Comment by ZevShiShi** [comment]
public void goBack() {
        if (getWebView() != null) {
            if (getWebView().canGoBack()) {
                getWebView().goBack();
            }
        }
    }

我是这样写的，没啥问题，之前b站点进去也是要点好几次才能返回，我这样写没问题

**Comment by owenxiao-AS** [comment]
> ```
> public void goBack() {
>     if (getWebView() != null) {
>         if (getWebView().canGoBack()) {
>             getWebView().goBack();
>         }
>     }
> }
> ```
> 
> 我是这样写的，没啥问题，之前b站点进去也是要点好几次才能返回，我这样写没问题，用webview对象就行

感谢感谢感谢！！！终于解决了啊  但是第二个if我要写成while  然后第一个if去判断url是否是首页

**Comment by owenxiao-AS** [comment]
你那样写  只会执行一次goback  我后面还有缓存页面的 要加个while

**Comment by ZevShiShi** [comment]
> 你那样写 只会执行一次goback 我后面还有缓存页面的 要加个while

我这样写没问题的，解决了就好

**Comment by owenxiao-AS** [comment]
感谢
