### ISSUE TITLE
setMainFrameErrorView网络恢复，错误页面不隐藏，但是能点击，怎么解决，能不能获取到setMainFrameErrorView 设置的view，来控制隐藏显示

### ISSUE THREAD

**Issue by ZevShiShi** [Justson/AgentWeb#599]

**Comment by bailibaili** [comment]
> _No description provided._

是bug，闲麻烦就禁用这个错误页面的功能吧，等作者修复吧

**Comment by ZevShiShi** [comment]
> > _No description provided._
> 
> 是bug，闲麻烦就禁用这个错误页面的功能吧，等作者修复吧
老哥你是怎么禁用的，不设置默认会显示一个错误页面

**Comment by bailibaili** [comment]
> > > _No description provided._
> > 
> > 
> > 是bug，闲麻烦就禁用这个错误页面的功能吧，等作者修复吧
> > 老哥你是怎么禁用的，不设置默认会显示一个错误页面

```
 //把这个重写了，还有在设置的时候不要设置那个错误页就行了
    @Nullable
    public AgentWebUIControllerImplBase getAgentWebUiController() {
        return new AgentWebUIControllerImplBase() {
            @Override
            public void onMainFrameError(WebView view, int errorCode, String description, String failingUrl) {

            }

        };
    }
```

**Comment by ZevShiShi** [comment]
> > > > _No description provided._
> > > 
> > > 
> > > 是bug，闲麻烦就禁用这个错误页面的功能吧，等作者修复吧
> > > 老哥你是怎么禁用的，不设置默认会显示一个错误页面
> 
> ```
>  //把这个重写了，还有在设置的时候不要设置那个错误页就行了
>     @Nullable
>     public AgentWebUIControllerImplBase getAgentWebUiController() {
>         return new AgentWebUIControllerImplBase() {
>             @Override
>             public void onMainFrameError(WebView view, int errorCode, String description, String failingUrl) {
> 
>             }
> 
>         };
>     }
> ```

ok谢了老哥

**Comment by RUDNI** [comment]
这个问题确实是，我这边好多用户反馈，看来只能等楼主修复了

**Comment by L-Kyle** [comment]
哎  碰到这问题跟踪源码找到原因想改  关键作者的代码格式。。要么修饰符不加public 要么类直接final了 是不想外界调用吗  只能down源码了

**Comment by Justson** [comment]
```
@Override
        public void onPageStarted(WebView view, String url, Bitmap favicon) {
            super.onPageStarted(view, url, favicon);
            Log.i(TAG, "mUrl:" + url + " onPageStarted  target:" + getUrl());
            timer.put(url, System.currentTimeMillis());
            if (url.equals(getUrl())) {
                pageNavigator(View.GONE);
            } else {
                pageNavigator(View.VISIBLE);
            }
        }
```
super.onPageStarted(view, url, favicon); 加上即可，Sample 上遗漏了

**Comment by bird4913** [comment]
这个问题有解决方案吗

**Comment by tanshion** [comment]
@Override
        public void onPageStarted(WebView view, String url, Bitmap favicon) {
            super.onPageStarted(view, url, favicon);
            Log.i(TAG, "mUrl:" + url + " onPageStarted  target:" + getUrl());
            timer.put(url, System.currentTimeMillis());
            if (url.equals(getUrl())) {
                pageNavigator(View.GONE);
            } else {
                pageNavigator(View.VISIBLE);
            }
        }

这段代码加上以后，问题并没有解决
