### ISSUE TITLE
加载时的背景

### ISSUE THREAD

**Issue by wanghan5950** [Justson/AgentWeb#600]
请问，怎么设置加载时的背景颜色或布局？

**Comment by BeforeFuture** [comment]
可以用这个设置背景色：
 FrameLayout frameLayout = mAgentWeb.getWebCreator().getWebParentLayout();
frameLayout.setBackgroundColor(Color.TRANSPARENT);

**Comment by AndroidKid19** [comment]
public interface WebCreator extends IWebIndicator {
    WebCreator create();

    WebView getWebView();

    FrameLayout getWebParentLayout();
}

可以直接设置webview 背景

mAgentWeb.getWebCreator().getWebView().setBackgroundColor(）
