### ISSUE TITLE
怎样能自动滑动到顶部呢？

### ISSUE THREAD

**Issue by JusticeOfHeaven** [Justson/AgentWeb#606]
就是web浏览过程中，想自动滑动到顶部，有啥API可以调用到么

**Comment by BeforeFuture** [comment]
> 
> 
> 就是web浏览过程中，想自动滑动到顶部，有啥API可以调用到么

这个需求解决了吗？

**Comment by Justson** [comment]
注入JS

**Comment by JusticeOfHeaven** [comment]
> > 就是web浏览过程中，想自动滑动到顶部，有啥API可以调用到么
> 
> 这个需求解决了吗？

> agentWeb = AgentWeb.with(this)
                .setAgentWebParent(NestedScrollView, ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT))
                .closeIndicator()
                .createAgentWeb()
                .ready()
                .go(webUrl)

我是设置一个给 `AgentWebParent ` 设置为 `ScrollView`  ,然后就可以自己调用 `ScrollView` 去滚动了
