### ISSUE TITLE
还是弃用吧！！！sample能用，把代码原封不懂放到我的项目中，硬是解决不了进度条一直卡在90%哪里，而且加载的网页有些按钮点击不了！！！

### ISSUE THREAD

**Issue by darkcgd** [Justson/AgentWeb#608]
还是弃用吧！！！sample能用，把代码原封不懂放到我的项目中，硬是解决不了进度条一直卡在90%哪里，而且加载的网页有些按钮点击不了！！！

**Comment by BeforeFuture** [comment]
你把原来的进度条隐藏掉，自己放一个progressBar进去，然后根据进度自己更新progress。

**Comment by Justson** [comment]
这种情况多半是网页内部某个资源下载异常，并非库问题。

**Comment by AdminQQZ** [comment]
为毛，常见问题，作者只关闭问题，而不解答。虽然说是常见问题，但是大部分人遇见了。

**Comment by Justson** [comment]
[#711](https://github.com/Justson/AgentWeb/issues/711) 这种问题，真的不想回答了， 这是基础问题，但凡愿意看下代码，或者Sample ， 都不至于来这里提issue ， 这里不提供教学。伸手党真可怕！

**Comment by AdminQQZ** [comment]
前端
window.android.getUserInfo("获取用户信息");
 这个你在sarmple 有写吗? 接收返回值

**Comment by ZacharyTech** [comment]
开源项目没有义务为你解决问题,  白嫖还要喷
