### ISSUE TITLE
如何隐藏或取消顶部进度条？

### ISSUE THREAD

**Issue by BeforeFuture** [Justson/AgentWeb#610]
试着调用 mAgentWeb.getIndicatorController().offerIndicator().hide(); 方法，进度条没有隐藏掉；
另外看到已关闭的issues中有说使用“.useDefaultIndicator(int color, int height_dp) 把height_dp設成0”，但是没有找到这个方法；
另一个已关闭的issues中有说“可以用closeIndicator()方法隐藏进度条”，也没有找到该方法；
请问，该如何操作，才能隐藏或取消顶部的进度条？

**Comment by BeforeFuture** [comment]
已经解决了。

**Comment by HulkCheung** [comment]
> 已经解决了。

兄弟，怎么取消的？

**Comment by BeforeFuture** [comment]
> 
> 
> > 已经解决了。
> 
> 兄弟，怎么取消的？


初始化的时候，高度设置为0。
