### ISSUE TITLE
无法全屏、进度条不走完、无法选择文件等等问题，很可能是和百度统计有关！！！

### ISSUE THREAD

**Issue by darkcgd** [Justson/AgentWeb#612]
全屏视频播放

android:hardwareAccelerated="true"
android:configChanges="orientation|screenSize"

按照作者说的 全屏视频播放 在清单文件设置了加速和全屏设置，为何还是不起作用？

**Comment by darkcgd** [comment]
找到了一部分原因 是因为WebChromeClient没回调，但不知道为何不回调？研究了很久，现在还没找到原因

**Comment by darkcgd** [comment]
找到原因了 https://github.com/Justson/AgentWeb/issues/65#issuecomment-317159482 原来是这个：
找到为什么不调用了，因为加入了百度可视化统计StatService.autoTrace(this, true, true);这一句，就啥都不调用了，两title都不出来了，看来这个百度统计有毒。

但是我项目中要用到百度统计，这可咋整？

**Comment by darkcgd** [comment]
最终解决方案：
https://mtj.baidu.com/static/userguide/book/android/adconfig/circle/circle.html 我们看百度统计，
3、Java代码配置-入口代码

开启自动埋点，调用如下代码即可：

Method1：（新增API，推荐使用此调起自动埋点功能）
// 自动埋点，建议在Application中调用。否则可能造成部分页面遗漏，无法完整统计。
StatService.autoTrace(Context context)  

Method2：
// 自动埋点，建议在Application中调用。否则可能造成部分页面遗漏，无法完整统计。
// @param autoTrace：如果设置为true，打开自动埋点；反之关闭
// @param autoTrackWebview：
// 如果设置为true，则自动track所有webview，如果有对webview绑定WebChromeClient，
// 为避免影响APP本身回调，请调用trackWebView接口；
// 如果设置为false，则不自动track webview，如需对特定webview进行统计，需要对特定
// webview调用trackWebView()即可。
StatService.autoTrace(Context context, boolean autoTrace, boolean autoTrackWebview)  
4、Java代码配置-webview统计
对于webview自动埋点统计，还需要调用如下代码：

// 适用于自动埋点版本，用于对webview加载的h5页面进行自动统计；需要在载入页面前调用，
// 建议在webview初始化时刻调用
// chromeClient，如果有设置的WebChromeClient，则需要将对象传入，否则影响本身回调
StatService.trackWebView(Context context, WebView webview, WebChromeClient chromeClient)

也就是说，如果StatService.autoTrace(this, true, true); 最后一个参数设置为true，那么百度统计将会影响到我们重写WebChromeClient本身回调，也就是本库作者辛苦写的WebChromeClient，将没意义了，所以大家一定要记住这个坑。。。。

**Comment by Justson** [comment]
感谢填坑，Sample 有注明
> WebViewClient ， 与 WebView 使用一致 ，但是请勿获取WebView调用setWebViewClient(xx)方法了,会覆盖AgentWeb DefaultWebClient,同时相应的中间件也会失效。
