### ISSUE TITLE
不支持带blob:http开头的下载链接

### ISSUE THREAD

**Issue by yangkan816** [Justson/AgentWeb#617]
我加载的页面有个按钮的下载链接地址  blob:http://192.168.90.61:19087/04464e33-756c-4118-9f93-57319feb6e36  下载就会失败，看log 提示的是新建文件夹失败。这个需要怎么去处理

**Comment by Justson** [comment]
网页打不开?

**Comment by yangkan816** [comment]
原始网页中有个按钮，点击是下载功能。但是这个下载链接是blob:http开头的。点击按钮不起作用。看log提示的新建文件夹失败

**Comment by Justson** [comment]
那会不会是权限问题

**Comment by yangkan816** [comment]
不是权限问题

**Comment by yangkan816** [comment]
我试过正常的http链接是可以下载的。但是这个带blob的，URI.parse（url）调用getpath（）的时候返回的是null，所以得到的file为null，所以在log中提示"新建文件夹失败"。我用的这个库的版本是4.0.2。
