### ISSUE TITLE
4.0.3beat 加载进度条卡住不消失

### ISSUE THREAD

**Issue by moneeWong** [Justson/AgentWeb#618]
4.0.3beat 加载进度条卡住不消失

**Comment by moneeWong** [comment]
你好 最新版的4.1.2仍然有这个问题 android7.0

**Comment by moneeWong** [comment]
![1565577817(1)](https://user-images.githubusercontent.com/17845920/62843705-7ef90c80-bcee-11e9-9670-4920c44935e8.jpg)

**Comment by moneeWong** [comment]
已解决，问题出现在 重写WebViewClient，使用demo中的即可
![image](https://user-images.githubusercontent.com/17845920/62846659-7f040700-bd04-11e9-957b-0ba3f9e73eef.png)

**Comment by MisterBowie** [comment]
如果重写了WebChromeClient  onProgressChanged方法的 super.onProgressChanged(view, newProgress);不能被注释掉

**Comment by AdminQQZ** [comment]
> onProgressChanged

没有效果
