### ISSUE TITLE
同一个链接，如何再次加载

### ISSUE THREAD

**Issue by yangfeng1994** [Justson/AgentWeb#621]
加载了一个网页后，再操作其他界面，返回这个界面，在URL上拼接一些东西，再重新加载这个网页，请问怎么样做才行？试了调用mAgentWeb.urlLoader.loadUrl()不能重新加载网页

**Comment by sbwhy** [comment]
我也碰到这个问题，请问怎么解决的

**Comment by renhuan** [comment]
> 我也碰到这个问题，请问怎么解决的

怎么解决的
