### ISSUE TITLE
shouldOverrideUrlLoading 不能拦截

### ISSUE THREAD

**Issue by wenmou** [Justson/AgentWeb#630]
shouldOverrideUrlLoading 不能拦截

**Comment by Justson** [comment]
贴代码

**Comment by wenmou** [comment]
@Override
    protected WebViewClient getWebViewClient() {
        return new WebViewClient() {
            @Override
            public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request) {
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                    KLog.d(request.getUrl());
                }
                return true;
            }

            @Override
            public void onPageStarted(WebView view, String url, Bitmap favicon) {
                currentUrl = url;
                super.onPageStarted(view, url, favicon);
                KLog.e(url);
            }
        };
    }

log


[ (PullNewActivity.java:137)#onPageStarted ] http://192.168.20.2:50201
 [ (TTAdManagerHolder.java:259)#onRewardVideoCached ] loadRewardVideoAdonRewardVideoCached


第一次不会拦截，第二个url才会 拦截

**Comment by Justson** [comment]
第一个url 不拦截，是正常的， 不拦截的情况下，  `super.shouldOverrideUrlLoading`  要加上

**Comment by wenmou** [comment]
那这个界面的广告不是屏蔽不了啦





------------------ 原始邮件 ------------------
发件人: "Justson"<notifications@github.com>; 
发送时间: 2019年8月30日(星期五) 下午3:40
收件人: "Justson/AgentWeb"<AgentWeb@noreply.github.com>; 
抄送: "╭wen眸"<835866862@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Justson/AgentWeb] shouldOverrideUrlLoading 不能拦截 (#630)




第一个url 不拦截，是正常的， 不拦截的情况下，  super.shouldOverrideUrlLoading  要加上
