### ISSUE TITLE
通过Gradle安装报错

### ISSUE THREAD

**Issue by tsun424** [Justson/AgentWeb#64]
在gradle中安装，同步后报错，具体报错见如些截图，原因应该是我的support库版本比library中的版本高。
`compile 'com.android.support:appcompat-v7:26.+'`
<img width="1126" alt="screen shot 2017-07-21 at 10 21 31 pm" src="https://user-images.githubusercontent.com/14896917/28459770-05caf4c6-6e63-11e7-89aa-345612220e37.png">

**Comment by Justson** [comment]
贴一下日志吗？
