### ISSUE TITLE
4.1.2的downloader组件依赖问题

### ISSUE THREAD

**Issue by wankey** [Justson/AgentWeb#643]
1. agentweb从4.0.2升级到4.1.2之后，依赖的download组件从com.just.agentweb:download:4.0.2变成了com.download.library:Downloader:4.1.2，这一点没有在README中说明，导致使用4.1.2的agentWeb之后，用户点击网页中的下载按钮会崩溃。

2. readme中说download组件是可选项，但实际上现在的情况是agentweb对它有强依赖，没有导入就会崩溃

3. 崩溃信息
```
Caused by:
 java.lang.ClassNotFoundException:Didn't find class "com.download.library.DownloadImpl" on path: DexPathList[[zip file "/data/app/com.game.motionelf-P6FhEKvPKutQpNPkeyGEXQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.game.motionelf-P6FhEKvPKutQpNPkeyGEXQ==/lib/arm64, /data/app/com.game.motionelf-P6FhEKvPKutQpNPkeyGEXQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
java.lang.ClassLoader.loadClass(ClassLoader.java:379)
java.lang.ClassLoader.loadClass(ClassLoader.java:312)
com.just.agentweb.DefaultDownloadImpl.createResourceRequest(SourceFile:1)
com.just.agentweb.DefaultDownloadImpl.onDownloadStartInternal(SourceFile:4)
com.just.agentweb.DefaultDownloadImpl$1.run(SourceFile:1)
```

**Comment by Justson** [comment]
是的， 将在下版修复这个问题。
临时修复方案 `mAgentWeb.webCreator.webView.setDownloadListener(null)`将DefaultDownloadImpl覆盖掉。

**Comment by wankey** [comment]
> 是的， 将在下版修复这个问题。
> 临时修复方案 `mAgentWeb.webCreator.webView.setDownloadListener(null)`将DefaultDownloadImpl覆盖掉。

设置为null之后，不会崩溃了，但是功能就没了，会显示网页出错信息，走不进shouldOverrideUrlLoading里

**Comment by Justson** [comment]
当然你也可以自己实现DownloadListener

**Comment by Justson** [comment]
V4.1.3 已修复

**Comment by zhangguannan** [comment]
我依赖的v5.0.0-alpha也是这个问题，没有引入download组件。vivo y51A版本5.1.1
