### ISSUE TITLE
监测到大部分5.1的手机出现android.content.res.Resources$NotFoundException: String resource ID #0x2040003

### ISSUE THREAD

**Issue by Devinmzt** [Justson/AgentWeb#646]
java.lang.RuntimeException:Unable to start activity ComponentInfo{com.shusheng.JoJoRead/com.hxdsw.common.webview.WebViewActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x2040003
--
2 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2404)
3 ......
4 Caused by:
5 android.content.res.Resources$NotFoundException:String resource ID #0x2040003
6 android.content.res.Resources.getText(Resources.java:318)
7 android.content.res.VivoResources.getText(VivoResources.java:123)
8 android.content.res.Resources.getString(Resources.java:404)
9 com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:694)
10 com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:618)
11 com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:631)
12 com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:780)
13 com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:619)
14 com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:556)
15 com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:312)
16 com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:96)
17 com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:264)
18 com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:123)
19 com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:110)
20 com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
21 com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:107)
22 com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:261)
23 android.webkit.WebView.<init>(WebView.java:554)
24 android.webkit.WebView.<init>(WebView.java:489)
25 android.webkit.WebView.<init>(WebView.java:472)
26 android.webkit.WebView.<init>(WebView.java:459)
27 android.webkit.WebView.<init>(WebView.java:449)
28 com.just.agentweb.DefaultWebCreator.createWebView(DefaultWebCreator.java:232)
29 com.just.agentweb.DefaultWebCreator.createLayout(DefaultWebCreator.java:177)
30 com.just.agentweb.DefaultWebCreator.create(DefaultWebCreator.java:154)
31 com.just.agentweb.DefaultWebCreator.create(DefaultWebCreator.java:34)
32 com.just.agentweb.AgentWeb.<init>(AgentWeb.java:195)
33 com.just.agentweb.AgentWeb.<init>(AgentWeb.java:43)
34 com.just.agentweb.AgentWeb$AgentBuilder.buildAgentWeb(AgentWeb.java:548)
35 com.just.agentweb.AgentWeb$AgentBuilder.access$3700(AgentWeb.java:482)
36 com.just.agentweb.AgentWeb$CommonBuilder.createAgentWeb(AgentWeb.java:687)
37 com.shusheng.commonres.webview.WebViewActivity.initData(WebViewActivity.java:111)
38 com.jess.arms.base.BaseActivity.onCreate(BaseActivity.java:105)
39 com.shusheng.commonsdk.base.JojoBaseActivity.onCreate(JojoBaseActivity.java:51)
40 android.app.Activity.performCreate(Activity.java:6083)
41 android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1115)
42 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2357)
43 android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
44 android.app.ActivityThread.access$900(ActivityThread.java:175)
45 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
46 android.os.Handler.dispatchMessage(Handler.java:102)
47 android.os.Looper.loop(Looper.java:135)
48 android.app.ActivityThread.main(ActivityThread.java:5418)
49 java.lang.reflect.Method.invoke(Native Method)
50 java.lang.reflect.Method.invoke(Method.java:372)
51 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
52 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by liyujiang-gzu** [comment]
#636 参见这个解决方案：
```java
    private static Context getFixedContext(Context context) {
        if (Build.VERSION.SDK_INT >= 21 && Build.VERSION.SDK_INT < 23) // Android Lollipop 5.0 & 5.1
            return context.createConfigurationContext(new Configuration());
        return context;
    }

```

**Comment by KAICW** [comment]
现在4.1.2有解决这个问题吗？

**Comment by xing634325131** [comment]
@liyujiang-gzu  这样会导致webview.getContext的返回ContextImpl对象，而非之前的Activity对象

**Comment by liyujiang-gzu** [comment]
> 现在4.1.2有解决这个问题吗？目前发现大部分都是出现在5.1的手机

4.1.2不包含已修复5.1的那部分代码，等待作者发布4.1.3看看

**Comment by liyujiang-gzu** [comment]
> @liyujiang-gzu 这样会导致webview.getContext的返回ContextImpl对象，而非之前的Activity对象

参阅[这个PR#655](https://github.com/Justson/AgentWeb/pull/655)
