### ISSUE TITLE
从无网络显示错误页面再打开网络重新加载时，在setMainFrameErrorView设置的错误页面根本不隐藏

### ISSUE THREAD

**Issue by fadedHYC** [Justson/AgentWeb#653]
从无网络显示错误页面再打开网络重新加载时，在setMainFrameErrorView设置的错误页面根本不隐藏
.setMainFrameErrorView(R.layout.recreation_error_layout, R.id.recreation_try)

**Comment by fddlpz** [comment]
我也遇到这种问题了，我手动隐藏，但是会闪一下。。。

**Comment by A451323699** [comment]
> private WebViewClient mWebViewClient=new WebViewClient(){
> @override
> public void onPageStarted(WebView view, String url, Bitmap favicon) {
> //加上下面这句就行了
> super.onPageStarted(view,url,favicon);
> 
> ```
>        //do you  work
>     }
> };
> ```

你好 这不是加载的监听吗， 我加了这句话 要 写什么操作呢？  在方法内 重新在写一次加载吗？

**Comment by A451323699** [comment]
> 从无网络显示错误页面再打开网络重新加载时，在setMainFrameErrorView设置的错误页面根本不隐藏
> .setMainFrameErrorView(R.layout.recreation_error_layout, R.id.recreation_try)

你这个问题  解决了吗 兄弟
