### ISSUE TITLE
HttpHeaders 保存header问题

### ISSUE THREAD

**Issue by tankai2525** [Justson/AgentWeb#659]
private String subBaseUrl(String originUrl) {
		if (TextUtils.isEmpty(originUrl)) {
			return originUrl;
		}
		int index = originUrl.indexOf("?");
		if (index <= 0) {
			return originUrl;
		}
		String subBaseUrl = originUrl.substring(0, index);
		return subBaseUrl;
	}

这个方法为啥是 ? 截止
为啥不是第三根 反斜线截止
在使用additionalHttpHeader(Url.BASE_URL, getHeaders())
请求多路径的链接http://xxx.base.com/system/message_sys 怎么拿得到header

**Comment by Justson** [comment]
```
    private String subBaseUrl(String originUrl) {
        if (TextUtils.isEmpty(originUrl)) {
            return originUrl;
        }
        Uri originUri = Uri.parse(originUrl);
        return originUri.getScheme() + "://" + originUri.getAuthority();
    }
```
感谢反馈
