### ISSUE TITLE
建议增加更加直观的getWebView接口

### ISSUE THREAD

**Issue by ericktang** [Justson/AgentWeb#66]
AgentWeb确实方便，但是开始使用的时候想找到WebView，搞了半天，看程序原来藏在mAgentWeb.getWebCreator().get()这里，这个接口直接使用get似乎不太直观，初入者真心不好找到，建议在AgetWeb中加个接口，比如getWebView()什么的。

**Comment by Justson** [comment]
感谢你的建议 。
