### ISSUE TITLE
请问一下作者，想要把你的项目打包成jar在项目中使用，怎么打包？

### ISSUE THREAD

**Issue by BeforeFuture** [Justson/AgentWeb#662]
请问一下作者，想要把你的项目打包成jar在项目中使用，怎么打包？
因为我的项目后续会打包成aar给别人使用，没办法直接进行gradle依赖。
试了百度的github库转jar方法，都失败了，提示没有pom.xml文件。

**Comment by Justson** [comment]
aar 解压，不就是资源文件和jar包?
