### ISSUE TITLE
Android 8.0网页打不开,是什么问题呢

### ISSUE THREAD

**Issue by onlywsw** [Justson/AgentWeb#669]
mAgentWeb = AgentWeb.with(this)
                .setAgentWebParent(container!!, LinearLayout.LayoutParams(-1, -1))
                .useDefaultIndicator()
                .setWebChromeClient(mWebChromeClient)
                //.setWebViewClient(mWebViewClient)
                .setMainFrameErrorView(R.layout.agentweb_error_page, -1)
                .setSecurityType(AgentWeb.SecurityType.STRICT_CHECK)
                .setWebLayout(WebLayout(this))
                .setOpenOtherPageWays(DefaultWebClient.OpenOtherPageWays.ASK)//打开其他应用时，弹窗咨询用户是否前往其他应用
                .interceptUnkownUrl() //拦截找不到相关页面的Scheme
                .createAgentWeb()
                .ready()
                .go("https://m.jd.com/")
        mAgentWeb.jsInterfaceHolder.addJavaObject("android", AndroidInterface(mAgentWeb, this@RelationChartActivity))

**Comment by Justson** [comment]
直接运行Sample?

**Comment by onlywsw** [comment]
这是自己的代码,在sample中运行是ok的,也没发现什么不一样的地方

**Comment by Justson** [comment]
检查权限网络等问题吧， 目测不是上面代码问题
