### ISSUE TITLE
agentweb点击上传图片，无法调起

### ISSUE THREAD

**Issue by createBean** [Justson/AgentWeb#671]
api 'com.just.agentweb:filechooser:4.1.2'// (可选)
已经加了这个依赖，但是点第三方H5的图片上传按钮，点了没反应。 是不是还要加其他操作？
麻烦大佬告知告知 谢谢

**Comment by Justson** [comment]
客户端只负责选择文件，上传属于前端问题。

**Comment by createBean** [comment]
问题是我用的淘宝的链接，里面有上传按钮，点击按钮根本没反应


| |
singleleft
|
|
邮箱：singleleft@163.com
|

Signature is customized by Netease Mail Master

在2019年11月01日 09:40，Justson 写道：

客户端只负责选择文件，上传属于前端问题。
