### ISSUE TITLE
关于进度条的问题，我统一回答一下

### ISSUE THREAD

**Issue by songjian931798** [Justson/AgentWeb#673]

**Comment by songjian931798** [comment]
遇到问题，坚决不了，就看源码嘛。作者在写例子的时候还是要照顾下复制粘贴的人。他们不会动脑子的。把代码粘过去，能解决就万事大吉，解决不了，就开始喷。
解决：private com.just.agentweb.WebChromeClient mWebChromeClient=new WebChromeClient(){
        @Override
        public void onProgressChanged(WebView view, int newProgress) {
            super.onProgressChanged(view,newProgress);
        }
    };
加上调父类的方法 super.onProgressChanged(view,newProgress);

**Comment by AdminQQZ** [comment]
![image](https://user-images.githubusercontent.com/12959954/71715377-1f8dcb80-2e4c-11ea-886f-e9feb6c70177.png)
这进度条本来就有问题。

作者在写 demo时候是把这个注释掉的。当然开源是好事，你喷开发者拿着源码，出现问题不会看源码，你不知道国内行情？都做了百分之80%工作了，把进度条的问题，完善一下。有什么问题？就说国内开发者不动脑袋？
   @Override
        public void onProgressChanged(WebView view, int newProgress) {
            //   super.onProgressChanged(view, newProgress);
        }
