### ISSUE TITLE
debug模式 一切正常 一打包生成apk就提示  网页提示出错啦！点击空白处刷新~

### ISSUE THREAD

**Issue by yang0000meng** [Justson/AgentWeb#674]
debug模式 一切正常 一打包生成apk 就提示  
网页提示出错啦！点击空白处刷新~
是什么原因呢

**Comment by yang0000meng** [comment]
找到一个原因是https证书的原因，怎经禁止https报错呢

已加 这个还是不管用。
  @Override
        public void onReceivedSslError(WebView view, SslErrorHandler handler, SslError error) {
            handler.proceed();
            super.onReceivedSslError(view, handler, error);
        }

**Comment by zhiwei1990** [comment]
> 找到一个原因是https证书的原因，怎经禁止https报错呢
> 
> 已加 这个还是不管用。
> @override
> public void onReceivedSslError(WebView view, SslErrorHandler handler, SslError error) {
> handler.proceed();
> super.onReceivedSslError(view, handler, error);
> }

注释掉 super.onReceivedSslError(view, handler, error);试试看。

**Comment by yang0000meng** [comment]
注释了，就好了

**Comment by afunnyrainman** [comment]
private val mWebViewClient: WebViewClient = object : WebViewClient() {
        override fun onReceivedSslError(
            view: WebView?,
            handler: SslErrorHandler?,
            error: SslError?
        ) {
            Log.e("dxq","x")
        }
    }

我加了这个 去掉了super还是不行。debug一切正常,打包之后无法跳转到别的域名下的界面
