### ISSUE TITLE
targetSdkVersion 27以上加载网页失败，报错

### ISSUE THREAD

**Issue by tyl210110** [Justson/AgentWeb#675]
当targetSdkVersion 为28或者29的时候，加载网页失败报错！
测试网页地址：https://go1.tscckg.com:8222/Register.aspx?user=-1&zcid=FRHBAZHKBYJRGVGMBCGMFRBAIP

**Comment by kingwin0129** [comment]
Android系统出于安全性考虑，在Android P系统（Android API >= 28）的设备上，如果应用使用的是非加密的明文流量的http网络请求，则会导致该应用无法进行网络请求，https则不会受影响；同样的，如果应用嵌套了webview，webview也只能使用https请求。
