### ISSUE TITLE
能发一下4.1.3解决Android5.1的问题吗

### ISSUE THREAD

**Issue by TxcA** [Justson/AgentWeb#676]
目前4.1.2有 android.content.res.Resources$NotFoundException的兼容问题，我看代码已经更新，但是未同步到仓库。

**Comment by bannerkun** [comment]
我看也是

**Comment by badboy-tian** [comment]
我刚刚也遇到这个问题了, 请问解决了么

**Comment by TxcA** [comment]
> 我刚刚也遇到这个问题了, 请问解决了么

参照android.content.res.Resources$NotFoundException 临时解决方案 #677 解决了。

**Comment by badboy-tian** [comment]
@TxcA  谢谢 我试试

**Comment by LiShang007** [comment]
使用#677方法后，页面白屏

**Comment by liyujiang-gzu** [comment]
那几个常见的些问题我两个月前都[提PR解决过了](https://github.com/Justson/AgentWeb/pull/655)，但是不知道作者怎么不发布一个小版本到maven仓库。

**Comment by tokiii** [comment]
确实是个问题，必现闪退！

**Comment by Justson** [comment]
新版已发布
