### ISSUE TITLE
加载过慢点问题

### ISSUE THREAD

**Issue by Qiaoshi96** [Justson/AgentWeb#679]
不知道有没有人关注这个问题，就是agentWeb在测试机vivo6.0系统上加载一个页面需要3、4秒，我本来以为和手机硬件有关系，但是同样链接试了下QQ和钉钉钉内部打开，明显要比我的快，我不知道是不是我使用的有问题，还请大佬给的优化建议

**Comment by Justson** [comment]
页面速度跟很多因素有关，机器、页面缓存、内核、网络、还有页面本身 等等。
