### ISSUE TITLE
检测是否存在Webview组件系统隐藏接口漏洞

### ISSUE THREAD

**Issue by 17606677790** [Justson/AgentWeb#681]
威胁描述 | 在4.0至4.2的Android系统上，Webview会增加searchBoxJavaBridge_, accessibility, accessibilityTraversal.可导致攻击者可以向页面植入Javascript，通过反射在客户端中执行任意恶意代码
-- | --

使用系统自带方法removeJavascriptInterface方法删除这些接口

请问AgentWeb怎么调用removeJavascriptInterface方法的,万分感谢

**Comment by Justson** [comment]
AgentWeb 已经处理了。
