### ISSUE TITLE
加载白屏问题  

### ISSUE THREAD

**Issue by p-jie** [Justson/AgentWeb#687]
AgentWeb加载某些网页出现白屏问题
例如如下网址 再在一个activity打开该网页是没问题的  但是在下一个Activity再打开 就出问题了

这个是什么原因呢

http://h5.guohaozhongyi.com/?#/tribune/sendPost?dk=2

**Comment by Justson** [comment]
删除`mAgentWeb.webLifeCycle.onPause()`试试看

**Comment by p-jie** [comment]
删除mAgentWeb.webLifeCycle.onPause()后问题依旧没解决
