### ISSUE TITLE
网页加载不出来

### ISSUE THREAD

**Issue by lucky013** [Justson/AgentWeb#699]
Android 9以上的手机有部分网页加载不出来；比如http://ab.mobilegames365.cn/017/

**Comment by lucky013** [comment]
http://ab.mobilegames365.cn/017/

**Comment by lucky013** [comment]
这个网页：http://ab.mobilegames365.cn/017/

**Comment by winksz** [comment]
在AndroidMa'nifest中application中加如这 android:usesCleartextTraffic="true"
