### ISSUE TITLE
如何使用 loadDataWithBaseURL 这个方法？

### ISSUE THREAD

**Issue by MinchinWang** [Justson/AgentWeb#7]

**Comment by Justson** [comment]
```
mAgentWeb.getLoader().loadDataWithBaseURL(); mAgentWeb.getWebCreator().get().loadDataWithBaseURL();
```

**Comment by Justson** [comment]
```
mAgentWeb.getLoader().loadDataWithBaseURL();   //推荐
或者
mAgentWeb.getWebCreator().get().loadDataWithBaseURL();
```

**Comment by MinchinWang** [comment]
我现在是需要用 mAgentWeb.getLoader().loadDataWithBaseURL();

但是 mAgentWeb = AgentWeb.with(this)
                .setAgentWebParent(webviewLayout, new LinearLayout.LayoutParams(-1, -1))
                .useDefaultIndicator()// 使用默认进度条
                .defaultProgressBarColor()
                .createAgentWeb()// 使用默认进度条
                .ready()
                .go();

这样子初始化，因为我没用到go(url), 不想用go， 要怎么初始化？

**Comment by Justson** [comment]
新版本 ， go("") ;

**Comment by MinchinWang** [comment]
依赖     compile 'com.just.agentweb:agentweb:1.2.0'

然后
 mAgentWeb = AgentWeb.with(this)
                .setAgentWebParent(webviewLayout, new LinearLayout.LayoutParams(-1, -1))
                .useDefaultIndicator()// 使用默认进度条
                .defaultProgressBarColor()
                .createAgentWeb()// 使用默认进度条
                .ready().go("");
这样子么？

**Comment by Justson** [comment]
`mAgentWeb.getWebCreator().get().setVerticalScrollBarEnabled();`  //or
 `mAgentWeb.getWebCreator().get().setHorizontalScrollBarEnabled();`
` mAgentWeb.getWebCreator().get()`拿到的是 WebView  ， 这里可以进行你想要的操作 。
