### ISSUE TITLE
下载文件问题,具体看描述

### ISSUE THREAD

**Issue by LEMON521** [Justson/AgentWeb#700]
此为下载链接
https://h5.nuaa.edu.cn/app/info/oa/file?url=31264&filename=%E9%99%84%E4%BB%B63%EF%BC%9A%E5%8D%97%E4%BA%AC%E8%88%AA%E7%A9%BA%E8%88%AA%E5%A4%A9%E5%A4%A7%E5%AD%A6%E2%80%9C%E8%AF%BE%E7%A8%8B%E6%80%9D%E6%94%BF%E2%80%9D%E6%95%99%E5%AD%A6%E6%96%B9%E6%A1%88%E8%AE%BE%E8%AE%A1%E8%A1%A8.doc

只是把这个链接放到a标签里面,点击这个标签,捕获到的文件长度为0,下载失败,但是在电脑浏览器可以正常下载,请问需要对webview设置什么参数吗?

**Comment by Justson** [comment]
分块传输，agentweb 版本？

**Comment by LEMON521** [comment]
agentweb 版本 4.0.2
分块传输是...

**Comment by Justson** [comment]
用最新版
