### ISSUE TITLE
偶尔会请求以下链接,导致无法加载网页

### ISSUE THREAD

**Issue by LEMON521** [Justson/AgentWeb#702]
请问这是框架自己访问的吗,我没找到相关的东西

`WebResourceResponse http://47.103.72.172:10028/js/k.js?FKFN=Z
WebResourceResponse https://s.duoroumao.cn/yxs199.js
WebResourceResponse https://s.duoroumao.cn/yxs199.js
WebResourceResponse https://c.duoroumao.cn/js/hyhot.js
WebResourceResponse https://c.duoroumao.cn/js/hyapialltw.js
WebResourceResponse https://c.sntzq.com/init/proxy.html?v=1.2
WebResourceResponse https://n.35kds.com/Requestad
WebResourceResponse https://c.sntzq.com/html/cnzz.html#web_id=1277999643&_=v20190301
WebResourceResponse https://s22.cnzz.com/z_stat.php?id=1277999643&web_id=1277999643
WebResourceResponse https://c.cnzz.com/core.php?web_id=1277999643&t=z
WebResourceResponse https://z3.cnzz.com/stat.htm?id=1277999643&r=http%3A%2F%2Flogin2.nuaa.edu.cn%2Fsso%2Flogin%3Fx_jump_mark%3DNUAA_APP%26redirect_uri%3Dhttps%3A%2F%2Fehall.nuaa.edu.cn%2Ftaskcenter%2Fwechat%2Findex%3Fmembership%3Dinfoplus_enterprise&lg=zh-cn&ntime=none&cnzz_eid=718884750-1576461455-https%3A%2F%2Fehall.nuaa.edu.cn%2F&showp=393x786&p=https%3A%2F%2Fc.sntzq.com%2Fhtml%2Fcnzz.html%23web_id%3D1277999643%26_%3Dv20190301&t=cnzz%E7%BB%9F%E8%AE%A1&umuuid=16f0cbd01e548-0861e3344d5e09-4935280a-4b6a2-16f0cbd01e61ed&h=1&rnd=368204149
WebResourceResponse https://cnzz.mmstat.com/9.gif?abc=1&rnd=1574701244
WebResourceResponse https://c.sntzq.com/html/tmpl/bannerao.html#viewid=78f34979f2380e8dc0a8ab7cd3fde950&scale=1.178125&ext=%7B%22title%22%3A%22%E5%85%8D%E8%B4%B9%E5%B0%8F%E8%AF%B4%EF%BC%8C%E8%B6%8A%E7%9C%8B%E8%B6%8A%E5%A4%9A%22%2C%22desc%22%3A%22%E9%98%85%E8%AF%BB%E6%98%AF%E4%BB%B6%E5%BF%AB%E4%B9%90%E7%9A%84%E4%BA%8B%EF%BC%8C%E5%89%8D%E6%8F%90%E6%98%AF%EF%BC%8C%E4%BD%A0%E6%9C%89%E5%85%8D%E8%B4%B9%E7%9A%84%E7%B2%BE%E5%BD%A9%E5%86%85%E5%AE%B9%EF%BC%8C%E6%AF%94%E5%A6%82%E6%89%BE%E5%88%B0%E6%88%91%22%2C%22crt_type%22%3A%221%22%2C%22isApp%22%3Afalse%2C%22isFeeds%22%3Afalse%2C%22index%22%3A0%7D
WebResourceResponse https://c.sntzq.com/js/plugin/wp_v1.2.js
WebResourceResponse https://n.35kds.com/Exposead/index/?re=cmFkPTAmdXB2PTAmdXB2UGVyaW9kPTAmaXB2PTAmcHJ2dGVkPTAmaXNkbT0wJmlzX2xhc3Q9MCZibHR5cGU9MCZjX2RldmljZV9seD03NiZjX2RldmljZV9zej0zJm1vZGVsX2x4PTImc2NsPTAmaXNwPTEmZWxsPTAmaWNwPTEmc2NwPTEmcmNsPTAmZWNyPTAmY3RyPTEwMCZlbGM9MTAwJmNsYz0wJmFtZWRpdW1pZD0wJmFhZHZwbGFjZWlkPTc5MDQmaW51bT0xJnVzZXJpZD0yMjE2JmRzcF9pZD0wJm10ZT0xNTc2NDY2NzA4JnNpZ25hdHVyZT0zMzkwMDU1NDkwN2E1YzBkNmI2YWYwNGQ4MTVhMWZmYyZpcD0yMTguMjguMjU0Ljk4JnJkYj0xOSZyZWxhdGVkaWQ9MCZyZWxhdGVkdWlkPTAmdXJsX2tleT0wJm1pZD0yNTkwJnl4dmlld2lkPTc4ZjM0OTc5ZjIzODBlOGRjMGE4YWI3Y2QzZmRlOTUwJnByX2lkPTg4NyZhcHBpZD01ODE1JmFkdnBsYWNlaWQ9ODIwMSZ5eGFkdnR5cGU9MyZtdWlkdHlwZT0xJmFwaXR5cGU9MiZtb2RlPTEmZG9tYWlucz1iRzluYVc0eUxtNTFZV0V1WldSMUxtTnUmY2xpZW50X3JlcW51bT0xJnVhdHlwZT1VQyZ1c2VyY2tpZD0zMTg5NjAzNDMyJnl4anM9MSZjX3c9MzkzJmNfaD03ODYmdWNrMj0zMTg5NjAzNDMyJmlzQ3Jvc3NEb21haW49MCZzaG93dXJsPWFIUjBjRG92TDJ4dloybHVNaTV1ZFdGaExtVmtkUzVqYmk5emMyOHZiRzluYVc0L2VGOXFkVzF3WDIxaGNtczlUbFZCUVY5QlVGQW1jbVZrYVhKbFkzUmZkWEpwUFdoMGRIQnpPaTh2WldoaGJHd3ViblZoWVM1bFpIVXVZMjR2ZEdGemEyTmxiblJsY2k5M1pXTm9ZWFF2YVc1a1pYZy9iV1Z0WW1WeWMyaHBjRDFwYm1admNHeDFjMTlsYm5SbGNuQnlhWE5sJmFkc2l0ZT0xJnZ0dHlwZT0yJm5ldHdvcms9MSZuZXR3b3JrMj0xJmpzbG9hZD0xJnBybz0x&ih=1&asp=0.03
WebResourceResponse openapp.jdmobile://virtual?params={"category":"jump","des":"m","url":"https://u.jd.com/woiCMC","keplerID":"0","keplerFrom":"1","kepler_param":{"source":"kepler-open","otherData":{"mopenbp7":"0"},"channel":"8bfd09e186324410bd59504c345afd85"},"union_open":"union_cps"}
onPageStarted -- openapp.jdmobile://virtual?params={"category":"jump","des":"m","url":"https://u.jd.com/woiCMC","keplerID":"0","keplerFrom":"1","kepler_param":{"source":"kepler-open","otherData":{"mopenbp7":"0"},"channel":"8bfd09e186324410bd59504c345afd85"},"union_open":"union_cps"}
`

**Comment by Justson** [comment]
不是
