### ISSUE TITLE
打开网页莫名其妙调起了支付宝

### ISSUE THREAD

**Issue by HuZengKan** [Justson/AgentWeb#714]
网页：http://web.guangdianyun.tv/live/35516?uin=1791
有大佬知道应该怎么改吗？

**Comment by Justson** [comment]
网页内部执行了调起支付宝的动作呗， 客户端可以根据需求拦截

**Comment by HuZengKan** [comment]
> 
> 
> 网页内部执行了调起支付宝的动作呗， 客户端可以根据需求拦截

但是ios以及系统浏览器都能正常打开，不会跳转到支付宝
