### ISSUE TITLE
4.1.2升级4.1.3发生crash

### ISSUE THREAD

**Issue by ccflyy** [Justson/AgentWeb#730]
#26046 java.lang.NullPointerException
Attempt to invoke virtual method 'android.content.Context android.app.Activity.getApplicationContext()' on a null object reference

com.just.agentweb.DefaultDownloadImpl.<init>(DefaultDownloadImpl.java:74)

1 java.lang.RuntimeException:Unable to start activity ComponentInfo{com.test/com.test.activity.WebActivityPlus}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Activity.getApplicationContext()' on a null object reference
--
2 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2585)
3 ......
4 Caused by:
5 java.lang.NullPointerException:Attempt to invoke virtual method 'android.content.Context android.app.Activity.getApplicationContext()' on a null object reference
6 com.just.agentweb.DefaultDownloadImpl.<init>(DefaultDownloadImpl.java:74)
7 com.just.agentweb.DefaultDownloadImpl.create(DefaultDownloadImpl.java:244)
8 com.just.agentweb.AgentWebSettingsImpl.setDownloader(AgentWebSettingsImpl.java:44)
9 com.just.agentweb.AgentWeb.ready(AgentWeb.java:437)
10 com.just.agentweb.AgentWeb.access$3100(AgentWeb.java:43)
11 com.just.agentweb.AgentWeb$PreAgentWeb.ready(AgentWeb.java:314)
12 com.test.activity.WebActivityPlus.init(WebActivityPlus.java:153)
13 com.test.base.BaseActivity.onCreate(BaseActivity.java:17)
14 android.app.Activity.performCreate(Activity.java:6176)
15 android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1115)
16 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2532)
17 android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2659)
18 android.app.ActivityThread.access$900(ActivityThread.java:188)
19 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1521)
20 android.os.Handler.dispatchMessage(Handler.java:111)
21 android.os.Looper.loop(Looper.java:194)
22 android.app.ActivityThread.main(ActivityThread.java:5714)
23 java.lang.reflect.Method.invoke(Native Method)
24 java.lang.reflect.Method.invoke(Method.java:372)
25 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
26 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by Justson** [comment]
机型？

**Comment by ccflyy** [comment]
后台收到的，都是Android5.1

**Comment by ccflyy** [comment]
用个Android5.1的模拟器可以复现

**Comment by Justson** [comment]
4.1.3 重新发布了。

**Comment by 748297973** [comment]
> 4.1.3 重新发布了。

@Justson 还是会有

**Comment by TxcA** [comment]
@ccflyy @GXSZone #759 (4.1.3)com.just.agentweb.DefaultDownloadImpl.临时解决办法
