### ISSUE TITLE
切换会出现白屏

### ISSUE THREAD

**Issue by YUHAN-GUO** [Justson/AgentWeb#733]
来回切换时会出现白屏，（你在webView 界面加载中的时候，切到另一个界面，等的快出现内容的时候，在返回去就会有白屏现象，fragment之间的切换）
![Screenshot_2020-03-04-15-35-50-26](https://user-images.githubusercontent.com/43516357/75855792-fed2f980-5e2d-11ea-806f-f5d3a7456837.jpg)
[白屏操作示例.zip](https://github.com/Justson/AgentWeb/files/4285807/default.zip)

**Comment by lingrixin** [comment]
这个问题用什么解决方案？为什么关闭了？
