### ISSUE TITLE
没法用啊

### ISSUE THREAD

**Issue by WangLei20167** [Justson/AgentWeb#74]
本人菜鸟一个    大神能不能把教程写的简单一些
或者是用Android Studio做个简单的使用demo，你给的代码教程真的没法用啊，
就像下面的代码 mAgentWeb ，mCallback，mLinearLayout的声明获取对象都是怎么做的？？？
急急急
mAgentWeb = AgentWeb.with(this)//传入Activity
                .setAgentWebParent(mLinearLayout, new LinearLayout.LayoutParams(-1, -1))//传入AgentWeb 的父控件 ，如果父控件为 RelativeLayout ， 那么第二参数需要传入 RelativeLayout.LayoutParams
                .useDefaultIndicator()// 使用默认进度条
                .defaultProgressBarColor() // 使用默认进度条颜色
                .setReceivedTitleCallback(mCallback) //设置 Web 页面的 title 回调
                .createAgentWeb()//
                .ready()
                .go("http://www.jd.com");

**Comment by Justson** [comment]
请惨遭Sample

**Comment by Justson** [comment]
请参照sample
