### ISSUE TITLE
定位问题

### ISSUE THREAD

**Issue by ToxicR** [Justson/AgentWeb#75]
请教一下，我在Demo中使用AgentWeb加载一个H5页面（该页面有定位功能）。我在给了Demo定位权限，但是网页还是提醒我定位失败。但是在你给出的Demo中是可以定位的。请问这是为什么？

**Comment by ToxicR** [comment]
手机是安卓7.0，在加载Https的时候是没有这种问题，但是加载Http的时候会出现刚刚说的那种情况

**Comment by Justson** [comment]
参照 Sample 处理下 。
