### ISSUE TITLE
如何加载这个目录下的html 本地文件

### ISSUE THREAD

**Issue by yuzhongrong** [Justson/AgentWeb#750]
var temppath=File(path).toURI().toString()
        Logger.e("-------indexhtmlpath--->$temppath")
        mAgentWeb?.urlLoader?.loadUrl(temppath)
打印结果是：file:/storage/emulated/0/wfc/plugin/1fefd5a9127ae81cd9e10ebb95084366/dist/index.html
虽然可以加载 但是第一次进去页面的时候 进度条会重复加载6到8次  这个是路由问题还是我加载方法用错了？

**Comment by yuzhongrong** [comment]
我加载的是本地html文件

**Comment by aaronKueng** [comment]
使用file协议
