### ISSUE TITLE
Telegram Bot domain invalid

### ISSUE THREAD

**Issue by YeaonLee** [Justson/AgentWeb#751]
你好，我在尝试用webview授权Telegram的login时，在重定向后报错了:Bot domain invalid,貌似是telegram没有收到referer，不知道有没有好的解决办法？这个是telegram login的链接：https://core.telegram.org/widgets/login。

**Comment by YeaonLee** [comment]
用手机浏览器测试是正常的，很神奇在webview里面不可以

**Comment by shanshuo0918** [comment]
请问这个问题有解决吗？

**Comment by duff627** [comment]
同问，这个问题解决了吗？
