### ISSUE TITLE
5.1报空指针

### ISSUE THREAD

**Issue by woleigeququ** [Justson/AgentWeb#756]
![f58786ad3e58c9d9c17d53467330eda](https://user-images.githubusercontent.com/28921977/79037619-7f430200-7c05-11ea-8476-0800e09aabed.png)

用了别的iusse中提的DownloadImpl.getInstance().with(activity.getApplication()); //提前初始化DownloadImpl   也还是不行

**Comment by woleigeququ** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Activity.getApplicationContext()' on a null object reference
at com.just.agentweb.DefaultDownloadImpl.(DefaultDownloadImpl.java:74)

**Comment by Justson** [comment]
4.1.3 刷新gradle cache

**Comment by woleigeququ** [comment]
请问怎么刷新呢 ，我现在就是用的4.1.3，网上查的gradlew build --refresh-dependencies 命令运行了还报错

**Comment by TxcA** [comment]
@woleigeququ #759

**Comment by woleigeququ** [comment]
谢谢
