### ISSUE TITLE
(4.1.3)com.just.agentweb.DefaultDownloadImpl.<init>临时解决办法

### ISSUE THREAD

**Issue by TxcA** [Justson/AgentWeb#759]
**异常详情：**
![2.png](https://i.loli.net/2020/04/14/9F2k5wRmNTJSM3l.png)
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Activity.getApplicationContext()' on a null object reference
        at com.just.agentweb.DefaultDownloadImpl.<init>(DefaultDownloadImpl.java:74)
        at com.just.agentweb.DefaultDownloadImpl.create(DefaultDownloadImpl.java:244)
        at com.just.agentweb.AgentWebSettingsImpl.setDownloader(AgentWebSettingsImpl.java:44)
        at com.just.agentweb.AgentWeb.ready(AgentWeb.java:437)
        at com.just.agentweb.AgentWeb.access$3100(AgentWeb.java:43)
        at com.just.agentweb.AgentWeb$PreAgentWeb.ready(AgentWeb.java:314)
```

**问题追溯**
![1.png](https://i.loli.net/2020/04/14/Bekm8I7EHWsJuTA.png)
![3.png](https://i.loli.net/2020/04/14/s6Vu3X5KapWhHPz.png)
![4.png](https://i.loli.net/2020/04/14/k6dornMIh2Ou9ew.png)

```
    @Override
    public WebListenerManager setDownloader(WebView webView, DownloadListener downloadListener) {
        // Fix Android 5.1 crashing:
        // ClassCastException: android.app.ContextImpl cannot be cast to android.app.Activity
        if (downloadListener == null) {
            Activity activity = getActivityByContext(webView.getContext());
            downloadListener = DefaultDownloadImpl.create(activity, webView, mAgentWeb.getPermissionInterceptor());
        }
        return super.setDownloader(webView, downloadListener);
    }
```

getActivityByView()抛null了，具体原因没详细追。因为目前ActivityUtils已更新为getActivityByContext()，抛弃了getActivityByView()。

**解决流程**
clone 代码，发现其实作者 @Justson 已修复该问题，感谢作者的付出。
```
  @Override
    public WebListenerManager setDownloader(WebView webView, DownloadListener downloadListener) {
        if (downloadListener == null) {
            downloadListener = DefaultDownloadImpl.create(mAgentWeb.getActivity(), webView, mAgentWeb.getPermissionInterceptor());
        }
        return super.setDownloader(webView, downloadListener);
    }
```

作者也说明清理gradle 缓存，但是无论是>gradlew build --refresh-dependencies，还是删除.gradle 都无法解决。为了保持代码独立性，引用module以后更新也不方便。固追了一下代码，发现引用是在
```
 private AgentWeb ready() {
        AgentWebConfig.initCookiesManager(mActivity.getApplicationContext());
        IAgentWebSettings mAgentWebSettings = this.mAgentWebSettings;
        if (mAgentWebSettings == null) {
            this.mAgentWebSettings = mAgentWebSettings = AgentWebSettingsImpl.getInstance();
        }
```
但是mAgentWebSettings是private私有的。
反射替换，问题解决。或者等作者发布下一个版本，自然解决。

**反射解决代码**
```
   override fun initData() {
        val webBuilder= AgentWeb.with(getActivity<AppCompatActivity>())
        try {
                val field: java.lang.reflect.Field = webBuilder::class.java.getDeclaredField("mAgentWebSettings")
                field.isAccessible = true
                field.set(webBuilder, IAgentWebSettingsImpl(getActivity<AppCompatActivity>()))
        } catch (e: Throwable) {
            // NONE
        }
        mAgentWeb = webBuilder
                .setAgentWebParent(mLinearLayout, LinearLayout.LayoutParams(-1, -1))
                .useDefaultIndicator()
                .addJavascriptInterface("iLoadHtml", InJavaScriptLocalObj())
                .addJavascriptInterface("payScript", InJavaScriptClosePage())
                .setWebViewClient(webViewClient)
                .setWebChromeClient(webChromeClient)
                .createAgentWeb()
                .ready()
                .go(url)
    }

        //因为本地的4.1.3中agentWeb没有mAgentWeb.getActivity()的方法，传递进去即可
    class IAgentWebSettingsImpl(private val act: Activity) : AbsAgentWebSettings() {

       private var mSettingAgentWeb: AgentWeb? = null

        override  fun bindAgentWebSupport(agentWeb: AgentWeb?) {
            this.mSettingAgentWeb = agentWeb
        }

        override fun setDownloader(webView: WebView?, downloadListener: DownloadListener?): WebListenerManager? {
            var listener= downloadListener
            if (listener== null) {
                listener= DefaultDownloadImpl.create(act, webView!!, mSettingAgentWeb!!.permissionInterceptor)
            }
            return super.setDownloader(webView, listener)
        }
    }
```

**临时解决办法，因为作者其实已经修复，最好的还是作者直接发布4.1.4，直接可以解决。**

**Comment by Justson** [comment]
4.1.3 没这个问题的， 刷新gradle下缓存

**Comment by xiaoowuu** [comment]
我用的4.1.3，也出现这个错误

**Comment by xiaoowuu** [comment]
本地是这个代码，跟GitHub上不一样，什么时候更新的啊？
/**
 * @author cenxiaozhong
 * @since 1.0.0
 */
public class AgentWebSettingsImpl extends AbsAgentWebSettings {
    private AgentWeb mAgentWeb;

    @Override
    protected void bindAgentWebSupport(AgentWeb agentWeb) {
        this.mAgentWeb = agentWeb;
    }

    @Override
    public WebListenerManager setDownloader(WebView webView, DownloadListener downloadListener) {
        // Fix Android 5.1 crashing:
        // ClassCastException: android.app.ContextImpl cannot be cast to android.app.Activity
        if (downloadListener == null) {
            Activity activity = getActivityByContext(webView.getContext());
            downloadListener = DefaultDownloadImpl.create(activity, webView, mAgentWeb.getPermissionInterceptor());
        }
        return super.setDownloader(webView, downloadListener);
    }

    /**
     * Copy from com.blankj.utilcode.util.ActivityUtils#getActivityByView
     */
    private Activity getActivityByContext(Context context) {
        if (context instanceof Activity) return (Activity) context;
        while (context instanceof ContextWrapper) {
            if (context instanceof Activity) {
                return (Activity) context;
            }
            context = ((ContextWrapper) context).getBaseContext();
        }
        return null;
    }

}

**Comment by LXLYHM** [comment]
我开了个分支把项目转成androidX库，跑到API22没有这个问题了。但是切回原来的support库分支就会有这个问题。

**Comment by Justson** [comment]
@xiaoowuu  你需要刷新你本地gradle cache ，然后重新下载4.1.3

**Comment by qinxinzhang** [comment]
我全部清除本地的gradle缓存。重新下载了所有依赖，包活4.1.3。但是发现仍然是以前的代码，建议作者重新发布4.1.4. 用 @xiaoowuu 的方法解决了，谢谢

**Comment by LillteZheng** [comment]
感谢，用反射搞定了，奇怪了，我也清除缓存什么的了，还是不行，希望坐着更新这个吧，5.1必现的

**Comment by ZevShiShi** [comment]
刷新缓存没用，我也是试过了，不起作用，作者早点更新吧
