### ISSUE TITLE
API 17（4.2） 到 22（5.1） 都是白屏，有进度条但页面没有加载成功

### ISSUE THREAD

**Issue by BarretWu** [Justson/AgentWeb#764]
API 17 到 22 都是白屏，有进度条但页面没有加载成功
1.测试了
    override fun onReceivedSslError(
            view: WebView?,
            handler: SslErrorHandler?,
            error: SslError?
        ) {
            handler?.proceed()
            LogUtils.loge("onReceivedSslError error=" + error?.primaryError)
        }

2.https与http混合
    mWebSettings.setMixedContentMode(WebSettings.MIXED_CONTENT_ALWAYS_ALLOW);

3.升级了4.1.3  ，别appcompat 也升级到androidx.appcompat:appcompat:1.2.0-alpha02

都不行，请指教

**Comment by api888** [comment]
同样问题

**Comment by 932707629** [comment]
同上

**Comment by chocozhao** [comment]
同上

**Comment by Justson** [comment]
白屏原因太多了

**Comment by LXLYHM** [comment]
同上  解决了吗？
