### ISSUE TITLE
4.1.3版本在5.1系统上报错

### ISSUE THREAD

**Issue by xiongsuyan** [Justson/AgentWeb#765]
之前一直用的是4.1.1版本，没有任何问题。最近更新到了4.1.3，结果发现同样的代码在5.1手机上会报空指针，具体log如下：
![image](https://user-images.githubusercontent.com/14892711/80327720-a76e6a00-886f-11ea-96e3-e02f30b95b39.png)
真的很奇怪，开发过程在10.0的手机上一点问题都没有，所以猜测是不是对低版本手机不适配？

**Comment by shenyongwang** [comment]
我也遇到了这种问题

**Comment by xiaochandou** [comment]
我也遇到了这种问题，请问有办法解决吗

**Comment by Justson** [comment]
跌下代码？

**Comment by xiongsuyan** [comment]
> 我也遇到了这种问题，请问有办法解决吗

除非作者更新，不然就降回原来的版本吧

**Comment by Justson** [comment]
刷新gradle cache 重新编译试试

**Comment by xiongsuyan** [comment]
> 跌下代码？

用法是一样的，只是把版本从4.1.1升级到4.1.3，降回去就好了。全程所有代码都没改，只是改了gradle中implementation的版本号，有2个项目用了agentweb，升级后一起崩溃。
o(╥﹏╥)o

**Comment by Justson** [comment]
版本不一样，api有变动。

**Comment by Justson** [comment]
版本更新， 可以参照Sample调整下

**Comment by xiongsuyan** [comment]
> 版本更新， 可以参照Sample调整下

3Q，新项目我重新集成一遍试试~

**Comment by xiaochandou** [comment]
> 刷新gradle cache重新编译试试



> > 版本更新， 可以参照Sample调整下
> 
> 3Q，新项目我重新集成一遍试试~

回退到4.1.1版本 ok 了

**Comment by Justson** [comment]
Sample 是没问题的
