### ISSUE TITLE
最新版本、华为CLT AL00  、华为 BLA AL00 、华为 EML AL00等机型偶现崩溃。。系统版本都是  Android 10,level 29 ROM  arm64-v8a

### ISSUE THREAD

**Issue by hfzhang1987** [Justson/AgentWeb#767]
#357572 SIGTRAP(TRAP_BRKPT)
com.just.agentweb.LollipopFixedWebView.<init>(LollipopFixedWebView.java:17)

#00 pc 018efd86 /system/product/app/TrichromeLibrary/TrichromeLibrary.apk
--
2 java:
3 org.chromium.content.browser.BrowserStartupControllerImpl.a(PG:35)
4 org.chromium.content.browser.BrowserStartupControllerImpl.a(PG:25)
5 org.chromium.android_webview.AwBrowserProcess.a(PG:37)
6 dm.run(Unknown Source:2)
7 org.chromium.base.ThreadUtils.c(PG:9)
8 E5.l(PG:28)
9 E5.a(PG:40)
10 E5.b(PG:8)
11 com.android.webview.chromium.WebViewChromiumFactoryProvider.a(PG:18)
12 com.android.webview.chromium.WebViewChromium.init(PG:14)
13 android.webkit.WebView.<init>(WebView.java:433)
14 android.webkit.WebView.<init>(WebView.java:355)
15 android.webkit.WebView.<init>(WebView.java:338)
16 android.webkit.WebView.<init>(WebView.java:325)
17 android.webkit.WebView.<init>(WebView.java:315)
18 com.just.agentweb.LollipopFixedWebView.<init>(LollipopFixedWebView.java:17)
19 com.just.agentweb.DefaultWebCreator.createWebView(DefaultWebCreator.java:243)
20 com.just.agentweb.DefaultWebCreator.createLayout(DefaultWebCreator.java:188)
21 com.just.agentweb.DefaultWebCreator.create(DefaultWebCreator.java:160)
22 com.just.agentweb.DefaultWebCreator.create(DefaultWebCreator.java:36)
23 com.just.agentweb.AgentWeb.<init>(AgentWeb.java:195)
24 com.just.agentweb.AgentWeb.<init>(AgentWeb.java:43)
25 com.just.agentweb.AgentWeb$AgentBuilder.buildAgentWeb(AgentWeb.java:548)
26 com.just.agentweb.AgentWeb$AgentBuilder.access$3700(AgentWeb.java:482)
27 com.just.agentweb.AgentWeb$CommonBuilder.createAgentWeb(AgentWeb.java:687)
28 com.xxx.xxx.webview.WebViewActivity.startLoadUrl(WebViewActivity.java:887)

**Comment by zwh2927** [comment]
我也遇到了同样问题

**Comment by Justson** [comment]
刷新下gradle cache

**Comment by 1030310877** [comment]
从华为技术人员那得知的原因：Chrome内核从79以下升级到79以上时，/data/data/packagename/app_webview文件夹中的缓存文件结构与79以上内核不兼容，导致读取时出现OOM。
解决方案：app首次启动时，删除/data/data/packagename/app_webview
