### ISSUE TITLE
加载页面issue

### ISSUE THREAD

**Issue by NanyangTaiji** [Justson/AgentWeb#769]
用标准加载直播源页面
mAgentWeb = AgentWeb.with(this)
                .setAgentWebParent((LinearLayout) view, new LinearLayout.LayoutParams(-1, -1))                
                .useDefaultIndicator()
                .createAgentWeb()
                .ready()
                .go("http://111.40.205.87/PLTV/88888888/224/3221225711/index.m3u8");

在加载过程，页面一片黑，可以调用什么image 来覆盖吗？

**Comment by Justson** [comment]
`useDefaultIndicator` 不是有进度条？
