### ISSUE TITLE
VIVO报错NotFoundException: String resource ID #0x2040003

### ISSUE THREAD

**Issue by zqbemail** [Justson/AgentWeb#771]
1 java.lang.RuntimeException:Unable to start activity ComponentInfo{com.xxx.doctor/com.xxx.baselibrary.ui.web.BaseAgentWebActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x2040003
2 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2439)
--
3 ......
4 Caused by:
5 android.content.res.Resources$NotFoundException:String resource ID #0x2040003
6 android.content.res.Resources.getText(Resources.java:318)
7 android.content.res.VivoResources.getText(VivoResources.java:123)
8 android.content.res.Resources.getString(Resources.java:404)
9 com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:695)
10 com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:619)
11 com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:631)
12 com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:780)
13 com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:619)
14 com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:556)
15 com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:312)
16 com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:96)
17 com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:264)
18 com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:123)
19 com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:110)
20 com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
21 com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:107)
22 com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:261)
这是什么问题啊？只有VIVO的21和22的版本才出现。其他手机没出现过。

**Comment by gao13439321200** [comment]
同问，我也出现这个问题了，请问怎么解决啊？

**Comment by Justson** [comment]
https://stackoverflow.com/questions/41025200/android-view-inflateexception-error-inflating-class-android-webkit-webview
