### ISSUE TITLE
下载文件会出现错误页面

### ISSUE THREAD

**Issue by wjsir** [Justson/AgentWeb#772]
点击打开下载文件的链接时会先显示错误页面才开始下载文件。下载demo apk安装重试也是一样的情况

**Comment by ifmvo** [comment]
同问

**Comment by Liweiwei2Anna** [comment]
这作者很垃圾，也不解决问题， 写的代码跟屎一样

**Comment by liyujiang-gzu** [comment]
> 这作者很垃圾，也不解决问题， 写的代码跟屎一样

这样说我觉得你更垃圾，人家开源免费给你用，有bug你不帮忙解决也就罢了，做个伸手党还伤人有意思吗？你又没给作者报酬，作者没义务帮你解决问题，而且你说”写的代码跟屎一样“我就不赞同了，安卓WebView一类的开源库，这个算是很优秀的了，看star数量足以说明。

**Comment by AdminQQZ** [comment]
割掉它的鸡鸡




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "穿青山魈人马"<notifications@github.com&gt;; 
发送时间: 2020年5月26日(星期二) 下午5:12
收件人: "Justson/AgentWeb"<AgentWeb@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [Justson/AgentWeb] 下载文件会出现错误页面 (#772)





  
这作者很垃圾，也不解决问题， 写的代码跟屎一样
  
这样说我觉得你更垃圾，人家开源免费给你用，有bug你不帮忙解决也就罢了，做个伸手党还伤人有意思吗？你又没给作者报酬，作者没义务帮你解决问题，而且你说”写的代码跟屎一样“我就不赞同了，安卓WebView一类的开源库，这个算是很优秀的了，看star数量足以说明。
 
&mdash;

**Comment by Justson** [comment]
#### 原因 WebView 内部错误回调onReceivedError造成的
在 MiddlewareWebClientBase 里面加入如下代码吧。
```
			@Override
			public void onReceivedError(WebView view, WebResourceRequest request, WebResourceError error) {
				if (request.isForMainFrame() && error.getErrorCode() != -1) {
					super.onReceivedError(view, request, error);
				}
			}
```

**Comment by liyujiang-gzu** [comment]
```java
    public void onReceivedError(WebView view, int errorCode, String description, String failingUrl) {
        hasError = true;
        if (errorCode == ERROR_UNSUPPORTED_SCHEME) {
            WebToolkit.openInExternalApp(view.getContext(), failingUrl);
            return;
        }
        if (errorCode != ERROR_UNKNOWN) {
            super.onReceivedError(view, errorCode, description, failingUrl);
        }
    }

```
