### ISSUE TITLE
AgentWeb布局

### ISSUE THREAD

**Issue by HeroLBJ** [Justson/AgentWeb#776]
`<FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <WebView
            android:layout_width="match_parent"
            android:layout_height="match_parent">

        </WebView>
         
        <com.just.library.BaseIndicatorView
            android:layout_width="match_parent"
            android:layout_height="2dp"
            >

        </com.just.library.BaseIndicatorView>
</FrameLayout>`

请问作者，使用这个库可以将FrameLayout改成RelativeLayout么？

**Comment by Justson** [comment]
为什么要改成RelativeLayout？
