### ISSUE TITLE
搭配JsBridge框架使用有问题

### ISSUE THREAD

**Issue by LeeUsun** [Justson/AgentWeb#779]
下载了项目，里面有个agentweb.apk 版本好像是3.1.0的，运行起来没问题，点击”JsBridge例子“item，运行起来，点击按钮，都是预期内的效果。然后直接编译项目运行，发现”JsBridge例子“这里有bug,点击”调用native方法“，没有改变页面内容，打log调试了一下，发现并没有调用安卓的方法，模拟器安卓6.0系统可以正常运行，9.0有bug

**Comment by LeeUsun** [comment]
各位下载最新demo中，”JsBridge例子“能正常运行吗？点击”调用native方法“并不是预期中的效果

**Comment by xiaoxiaohua333** [comment]
JsBridge 项目里面缺失了WebViewJavascriptBridge.js，去下载一个导进去就好了
