### ISSUE TITLE
4.1.3

### ISSUE THREAD

**Issue by Wzert** [Justson/AgentWeb#787]
java.lang.RuntimeException
异常信息:Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377
关键堆栈:com.just.agentweb.LollipopFixedWebView.<init>(LollipopFixedWebView.java:17)

**Comment by liyujiang-gzu** [comment]
试试在你的Application类的onCreate里`WebView.setDataDirectorySuffix(processName);`

**Comment by Wzert** [comment]
使用了下面的方法 好像还会报错，有的手机会报错，有的不会 同样都是9.0以上  

  public void webviewSetPath(Context context) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            String processName = getProcessName(context);
            if (!context.getPackageName().equals(processName)) {//判断不等于默认进程名称
                WebView.setDataDirectorySuffix(processName);
            }
        }
    }

    public String getProcessName(Context context) {
        if (context == null) return null;
        ActivityManager manager = (ActivityManager) context.getSystemService(Context.ACTIVITY_SERVICE);
        for (ActivityManager.RunningAppProcessInfo processInfo : manager.getRunningAppProcesses()) {
            if (processInfo.pid == android.os.Process.myPid()) {
                return processInfo.processName;
            }
        }
        return null;
    }

**Comment by Justson** [comment]
[单进程也会抛出该问题](https://bugs.chromium.org/p/chromium/issues/detail?id=558377#c126)
