### ISSUE TITLE
陈年老问题--怎么加载 html静态网页

### ISSUE THREAD

**Issue by githubPgy** [Justson/AgentWeb#788]
mAgentWeb.getUrlLoader().loadData("file:///android_asset/hello1.html","",""); 不行

**Comment by AdminQQZ** [comment]
就是普通加载网页地址的方法，你传入静态html路径就可以了。

**Comment by githubPgy** [comment]
tks 好了 
//        mAgentWeb = AgentWeb.with(this)
//                .setAgentWebParent((LinearLayout) viewById, new LinearLayout.LayoutParams(-1, -1))
//                .useDefaultIndicator()
//                .createAgentWeb()
//                .ready()
//                .go("file:///android_asset/hello1.html");
