### ISSUE TITLE
下载文件显示错误页面

### ISSUE THREAD

**Issue by ColdSongDvl** [Justson/AgentWeb#789]
如题，每次都复现，应该所有人都遇到的

**Comment by ColdSongDvl** [comment]
修复方法：在DefaultWebClient类的新版onReceivedError方法中更改显示错误页的判断条件
**(request.isForMainFrame())**
为
**(request.isForMainFrame() && request.getUrl().toString().equals(view.getUrl()))**

**Comment by as1105** [comment]
请问一下这个怎么改，项目集成源码再修改？

**Comment by as1105** [comment]
> 修复方法：在DefaultWebClient类的新版onReceivedError方法中更改显示错误页的判断条件
> **(request.isForMainFrame())**
> 为
> **(request.isForMainFrame() && request.getUrl().toString().equals(view.getUrl()))**

没用

**Comment by Justson** [comment]
```java
			@Override
			public void onReceivedError(WebView view, WebResourceRequest request, WebResourceError error) {
				if (request.isForMainFrame() && error.getErrorCode() != -1) {
					super.onReceivedError(view, request, error);
				}
			}
```
