### ISSUE TITLE
如何获取当前页数

### ISSUE THREAD

**Issue by dary123** [Justson/AgentWeb#790]
我这边有个需求，需要次级页面显示叉按钮，如果不是次级，是第一个页面，则显示返回键按钮，不显示叉

**Comment by dary123** [comment]
或者如何获取webview控件呀，获取到这个控件哦我也能判断是不是次级页面

**Comment by Justson** [comment]
....无语

**Comment by cowoboy007** [comment]
怎么无语了。很正常的需求哈。有路子吗。我也遇到了
