### ISSUE TITLE
最新版本4.1.3，存在以下问题Can't set data directory suffix: WebView already initialized

### ISSUE THREAD

**Issue by Petterpx** [Justson/AgentWeb#791]
机型 三星s8 Android9.0
compileSdkVersion 29
android gradle 4.0.0

昨天将版本升到4.1.3后出现了这个问题。
java.lang.IllegalStateException: Can't set data directory suffix: WebView already initialized
搜索是Android P以上WebView多进程问题，尝试了现有的解决方法，都没什么用。

将版本退回4.1.2就是正常的。

**Comment by Justson** [comment]
[Can't set data directory suffix: WebView already initialized](https://bugs.chromium.org/p/chromium/issues/detail?id=558377#c126)
