### ISSUE TITLE
缓存问题

### ISSUE THREAD

**Issue by liupeng1991** [Justson/AgentWeb#795]
agentWeb = AgentWeb.with(this)
                .setAgentWebParent(frameLayout, new FrameLayout.LayoutParams(-1, -1))
                .useDefaultIndicator()
                .createAgentWeb()
                .ready()
                .go(url);

为什么总是取得缓存，服务器已经更新了，经过测试，浏览器上面是回去重新下载的。

**Comment by zaoyilikai** [comment]
if (AgentWebUtils.checkNetwork(webView.getContext())) {
            //根据cache-control获取数据。
            mWebSettings.setCacheMode(WebSettings.LOAD_DEFAULT);
        } else {
            //没网，则从本地获取，即离线加载
            mWebSettings.setCacheMode(WebSettings.LOAD_CACHE_ELSE_NETWORK);
        }
这是默认缓存设置，可以根据业务需求，自行设置。
