### ISSUE TITLE
html中使用video无法播放

### ISSUE THREAD

**Issue by afunnyrainman** [Justson/AgentWeb#796]
html中使用video无法播放
![WechatIMG12](https://user-images.githubusercontent.com/22904462/85008216-40927080-b18f-11ea-9180-be64db4610ce.jpeg)

**Comment by afunnyrainman** [comment]
android:hardwareAccelerated="true"
                android:configChanges="orientation|screenSize"

**Comment by afunnyrainman** [comment]
android:hardwareAccelerated="true"
                android:configChanges="orientation|screenSize" 加了这个也不管用

**Comment by afunnyrainman** [comment]
![9c19d4dd08ee99ba15ab3ca4958308e](https://user-images.githubusercontent.com/22904462/85086420-1ed7ce80-b20d-11ea-8487-a88fa8432d85.jpg)

**Comment by a8469758** [comment]
解决了吗

**Comment by afunnyrainman** [comment]
没有



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "蛋蛋"<notifications@github.com&gt;; 
发送时间: 2020年10月26日(星期一) 晚上7:21
收件人: "Justson/AgentWeb"<AgentWeb@noreply.github.com&gt;; 
抄送: "Key"<876314095@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Justson/AgentWeb] html中使用video无法播放 (#796)





 
解决了吗
