### ISSUE TITLE
在网页无法吊起客户端，比如优酷，京东

### ISSUE THREAD

**Issue by yhsj0919** [Justson/AgentWeb#80]

**Comment by Justson** [comment]
您好， 我特意又测试了下， 是可以调起客户端的，但是需要满足以下条件
*  `shouldOverrideUrlLoading`方法不进行拦截，交给`DefaultWebClient` 处理该链接。
*   手机必须安装了客户端。（1.2.6 把跳应用市场和跳浏览器下载应用部分去掉了）
*   url 里面包含的包名与手机安装客户端的包名一致
