### ISSUE TITLE
 Unable to create layer for LollipopFixedWebView

### ISSUE THREAD

**Issue by mazhenming892** [Justson/AgentWeb#803]
│ ************* Log Head ****************
    │ Time Of Crash      : 2020_07_07-21_41_41
    │ Device Manufacturer: HUAWEI
    │ Device Model       : SCL-TL00H
    │ Android Version    : 5.1.1
    │ Android SDK        : 22
    │ App VersionName    : 3.0.0
    │ App VersionCode    : 1
    │ ************* Log Head ****************
    │ 
    │ java.lang.IllegalStateException: Unable to create layer for LollipopFixedWebView
    │ 	at android.os.MessageQueue.nativePollOnce(Native Method)
    │ 	at android.os.MessageQueue.next(MessageQueue.java:143)
    │ 	at android.os.Looper.loop(Looper.java:122)
    │ 	at android.app.ActivityThread.main(ActivityThread.java:5593)
    │ 	at java.lang.reflect.Method.invoke(Native Method)
    │ 	at java.lang.reflect.Method.invoke(Method.java:372)
    │ 	at com.android.internal.os.ZygoteInit$MethodAndArg

**Comment by mazhenming892** [comment]
agentweb version is 4.1.3

**Comment by mazhenming892** [comment]
布局嵌套如下，在android 10.0下能正常使用，不知道怎么回事
<androidx.coordinatorlayout.widget.CoordinatorLayout
        android:id="@+id/root"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <com.google.android.material.appbar.AppBarLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">
            <androidx.appcompat.widget.Toolbar
                android:id="@+id/toolbar"
                android:layout_width="match_parent"
                android:layout_height="?actionBarSize"
                android:background="?colorPrimary"
                app:layout_scrollFlags="scroll|enterAlways|snap"
                app:menu="@menu/webview_menu"
                app:navigationIcon="@drawable/back"
                app:titleTextColor="@color/white" />


        </com.google.android.material.appbar.AppBarLayout>

        <androidx.core.widget.NestedScrollView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior">

            <LinearLayout
                android:id="@+id/ll"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:orientation="vertical">

            </LinearLayout>
        </androidx.core.widget.NestedScrollView>

    </androidx.coordinatorlayout.widget.CoordinatorLayout>

**Comment by DocHuangys** [comment]
https://stackoverflow.com/questions/41025200/android-view-inflateexception-error-inflating-class-android-webkit-webview
