### ISSUE TITLE
h5调用相册多选图片无效？需要怎么配置吗，h5链接在浏览器打开是能多选的但咱们agentweb却不行，有解决的办法吗

### ISSUE THREAD

**Issue by tom1993721** [Justson/AgentWeb#804]

**Comment by ThirdPrince** [comment]
建议 对接 图片选择器 比如 pictureSelecter

**Comment by Justson** [comment]
Chooser能做不止图片选择，有文件、视频、拍照等，图片选择建议用图片库 ，  Chooser存在一定的兼容问题 。

**Comment by tom1993721** [comment]
我通过自定义WebChromeClient里头的openFileChooer和onShowFileChooser来吊起自己定义的选择

**Comment by robinhoo2010** [comment]
> 我通过自定义WebChromeClient里头的openFileChooer和onShowFileChooser来吊起自己定义的选择

你好，如何做的，能提供代码吗，谢谢

**Comment by cocowobo** [comment]
![image](https://user-images.githubusercontent.com/19485885/117635455-66af6d80-b1b2-11eb-9d6d-488e1a9945c2.png)
![image](https://user-images.githubusercontent.com/19485885/117635491-6f07a880-b1b2-11eb-8839-00f4c92e80e6.png)
