### ISSUE TITLE
页面有时候  打不开

### ISSUE THREAD

**Issue by w1186859682** [Justson/AgentWeb#807]
oppo手机，页面有时候 打不卡显示一片 空白 我使用的是4.0.2的版本， 并且每次页面加载前都调用的 清空缓存的方法。  这是缓存的问题吗？

**Comment by w1186859682** [comment]
app  卸载重装  后 还是打不开

**Comment by Justson** [comment]
debug 看下吗？

**Comment by AdminQQZ** [comment]
我也遇到了这个问题，我的操作步骤是，进入返回，进入返回，进入返回。后来我调整了下退出的时候清理缓存，触发的概率比较少了，但是偶尔还是会出现，主要是测试发现了这个问题，一直揪着我。小米6 小米5 测试机，应该不是兼容性问题。猜测应该是什么没有初始化好，因为偶尔进入就空白了

**Comment by w1186859682** [comment]
我这也是 用户反馈的，在我的测试机上没有问题，我让用户重装好几回都不行

**Comment by w1186859682** [comment]
你的现在的改好了吗？ 我这是oppo r9m  android 5.1 的版本   现在又有个  vivo的手机 用户也是显示空白

**Comment by jerryyh** [comment]
我也遇到这个问题，vivo7plus，oppor9km等机型显示空白，不能加载出内容

**Comment by jerryyh** [comment]
> 你的现在的改好了吗？ 我这是oppo r9m android 5.1 的版本 现在又有个 vivo的手机 用户也是显示空白

你的问题解决了吗

**Comment by jerryyh** [comment]
貌似重写下面方法可以解决
webview.setWebViewClient(new WebViewClient() {
    @Override
    public void onReceivedSslError(WebView view, SslErrorHandler handler, SslError error) {
 
        // 不要使用super，否则有些手机访问不了，因为包含了一条 handler.cancel()
        // super.onReceivedSslError(view, handler, error);
 
        // 接受所有网站的证书，忽略SSL错误，执行访问网页
        handler.proceed();
    }
}

**Comment by lutao2599** [comment]
我也遇到这个问题，现在正在找解决办法，偶尔出现网页打不开的情况？该怎么解决

**Comment by lantesi** [comment]
android 4.4的工业屏遇到同样的问题，有没有人解决了的，上面那个兄弟的解决办法没有用，还是白屏

**Comment by zhengfa365** [comment]
> 我也遇到这个问题，现在正在找解决办法，偶尔出现网页打不开的情况？该怎么解决

最后解决没呢 ？
