### ISSUE TITLE
手势放大缩小屏幕功能如何设置

### ISSUE THREAD

**Issue by wushge11** [Justson/AgentWeb#81]
重新设置WebSetting的放大缩小不生效， 请问如何实现。

**Comment by Justson** [comment]
` mAgentWeb.getWebCreator().get().getSettings();`

**Comment by edifangyi** [comment]
WebSettings settings = mAgentWeb.getWebCreator().get().getSettings();
        settings.setSupportZoom(true);
        settings.setBuiltInZoomControls(true);
        settings.setUseWideViewPort(true);
        settings.setDisplayZoomControls(false);
