### ISSUE TITLE
调用前端给的网页报错JsInterfaceObjectException

### ISSUE THREAD

**Issue by huwencheng** [Justson/AgentWeb#810]
报错信息：this object has not offer method javascript to call , please check addJavascriptInterface annotation was be added。
请问抛这个异常是要客户端还是前端处理什么呢？

**Comment by AdminQQZ** [comment]
没有注册成功

**Comment by huwencheng** [comment]
是前端问题导致注册失败，还是客户端问题，具体需要怎么样处理呢

**Comment by huwencheng** [comment]
@AdminQQZ 麻烦大佬指点下

**Comment by Justson** [comment]
```
@JavascriptInterface
```
 注入方法加上该注解

**Comment by AdminQQZ** [comment]
注册方法写在你APP上面的，前端只是来调用，这时候你的日志里面报错了，这个要仔细看你代码了，细节问题。

**Comment by huwencheng** [comment]
![image](https://user-images.githubusercontent.com/8435177/87371205-70c70680-c5b7-11ea-8708-4db0ff1f2f0d.png)，addJavaObject("appMethod", androidInterface)  我这边是有调用JavascriptInterface方法的，为啥会出现这个错误呢

**Comment by huwencheng** [comment]
class AndroidInterface {

    private var context: Context
    private var agentWeb: AgentWeb
    private var listener: JSBridgeLifeCycleListener? = null

    constructor(context: Context, agentWeb: AgentWeb) {
        this.context = context
        this.agentWeb = agentWeb
    }

    fun setJSBridgeLifeCycleListener(listener: JSBridgeLifeCycleListener?) {
        this.listener = listener
    }

    /**
     * h5调用原生方法
     */
    @JavascriptInterface
    fun router(json: String?) {
        try {
            if (TextUtils.isEmpty(json)) {
                return
            }
            json!!.trimStart('"')
            json.trimEnd('"')
            val jsonObject = JSONObject(json)
            val action = jsonObject.optString("action")
            if (TextUtils.isEmpty(action)) {
                return
            }
            var data: JSONObject? = null
            if (jsonObject.has("data")) {
                data = jsonObject.getJSONObject("data")
            }
//            JumpToUtils.onJumpTo(context, action, data, listener)
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }

    /**
     * 原生调用h5方法
     */
    fun routerCallback(json: JSONObject?) {
        agentWeb.jsAccessEntrace.quickCallJs("routerCallback", json.toString())
    }

}
