### ISSUE TITLE
Activity.getApplicationContext()' on a null object

### ISSUE THREAD

**Issue by custqqy** [Justson/AgentWeb#814]
android 5.1.1上（雷电模拟器）AgentWeb.java类中ready()方法里面会报Activity.getApplicationContext()' on a null object异常

**Comment by Justson** [comment]
4.1.3 已修复

**Comment by ling9400** [comment]
4.1.3好像还是有问题，在android5.1 OPPO R9m手机上

**Comment by krcdxnh** [comment]
@Justson 问题没有解决

**Comment by webor2006** [comment]
Samsung GT-I9500也还有，android 5.0.1

**Comment by Justson** [comment]
4.1.4?
