### ISSUE TITLE
需要和其他布局嵌套的时候怎么办?

### ISSUE THREAD

**Issue by ppg408331701** [Justson/AgentWeb#82]
类似淘宝的商品的详情页,
上半部的是native的控件
下半部才是webview

现在我嵌套上去之后发现和scrollview的滚动事件冲突了
现在是打算重写滚动事件解决,还是想问问您又没有什么最优的解决方案

另外,还有一个问题,
在加载本地html文本的时候有时会出现webview下面有大量的空白的情况,请问您有遇到过吗

**Comment by Justson** [comment]
AgentWeb 没有对滑动事件进行处理 ， 如果出现冲突， 需要自行处理 。
有可能 html 本身没满屏 , 或者可以检查下传入 agentWebParent  。
