### ISSUE TITLE
Webview明文存储密码风险、Webview File同源策略绕过漏洞、Webview远程代码执行漏洞

### ISSUE THREAD

**Issue by 2642134396** [Justson/AgentWeb#823]
您好，我们的APP使用了agent web，经过第三方安全检测发现还有这几个高风险漏洞：
**一、检测App应用的Webview组件中是否使用明文保存用户名及密码。**

测评结果描述 | 该App应用的Webview组件中未设置关闭自动保存密码功能，用户名和密码可能被明文存储。
测评详细信息 | 1.   [文件]：   com/just/agentweb/AgentWebUtils   [方法]：   static   clearWebViewAllCache(Landroid/content/Context;Landroid/webkit/WebView;)V  
 2.   [文件]：   com/just/agentweb/AgentWebView   [方法]：   protected   fixedAccessibilityInjectorExceptionForOnPageFinished(Ljava/lang/String;)V

**二、检测Apk中WebView的file域协议是否存在同源策略绕过的漏洞。**

测评结果描述 | 该Apk程序存在webview File同源策略绕过的漏洞。
测评详细信息 | 1.   [文件]：   com/just/agentweb/AbsAgentWebSettings   [方法]：   private settings(Landroid/webkit/WebView;)V

**三、检测app应用的webview组件中是否存在远程代码执行漏洞**

测评结果描述 | 该App应用中可能存在被addJavascriptInterface接口导出的未注册Java类函数。
测评详细信息 | 1.   [文件]：   com/just/agentweb/JsInterfaceHolderImpl   
2.   [文件]：   com/just/agentweb/AgentWebView

麻烦问下怎么处理？或者修复一下。万分感谢！

**Comment by Justson** [comment]
感谢你反馈的问题。不知道你用的是什么第三方安全分析， 你这些问题能在AgentWeb源码中找到答案 。

**Comment by liupeng1991** [comment]
我的也是验证不通过，使用了华为的安全检测！ 请作者看看怎么绕过这个检测！万分感谢

**Comment by liupeng1991** [comment]
> 感谢你反馈的问题。不知道你用的是什么第三方安全分析， 你这些问题能在AgentWeb源码中找到答案 。

我的也是验证不通过，使用了华为的安全检测！ 请作者看看怎么绕过这个检测！万分感谢

**Comment by 2642134396** [comment]
我是这样解决的: 听同事说即使组件里面那个漏洞修复了，安全检测还是不通过，因为没有进行app加固。后来使用腾讯云app加固平台将app加固后再没报那个漏洞了。



---原始邮件---
发件人: "liupeng1991"<notifications@github.com&gt;
发送时间: 2020年12月28日(周一) 晚上7:56
收件人: "Justson/AgentWeb"<AgentWeb@noreply.github.com&gt;;
抄送: "2642134396"<2642134396@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Justson/AgentWeb] Webview明文存储密码风险、Webview File同源策略绕过漏洞、Webview远程代码执行漏洞 (#823)




  
感谢你反馈的问题。不知道你用的是什么第三方安全分析， 你这些问题能在AgentWeb源码中找到答案 。
  
我的也是验证不通过，使用了华为的安全检测！ 请作者看看怎么绕过这个检测！万分感谢
