### ISSUE TITLE
嗨，发现这个报错，

### ISSUE THREAD

**Issue by AdminQQZ** [Justson/AgentWeb#828]
类似解决办法https://www.jianshu.com/p/9d0cd219d982

![image](https://user-images.githubusercontent.com/12959954/89600083-c085ae80-d893-11ea-8d3d-e59aa83c3e0a.png)

![image](https://user-images.githubusercontent.com/12959954/89600106-ce3b3400-d893-11ea-8b89-186e6dbe4b33.png)

**Comment by AdminQQZ** [comment]
![image](https://user-images.githubusercontent.com/12959954/89600186-02165980-d894-11ea-862b-e01e89bdccd4.png)

**Comment by Justson** [comment]
4.1.3?
