### ISSUE TITLE
5.1系统打开页面时闪退

### ISSUE THREAD

**Issue by RockRoll666** [Justson/AgentWeb#829]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Activity.getApplicationContext()' on a null object reference

Caused by:
--
java.lang.NullPointerException:Attempt to invoke virtual method 'android.content.Context android.app.Activity.getApplicationContext()' on a null object reference
com.just.agentweb.DefaultDownloadImpl.<init>(DefaultDownloadImpl.java:74)
com.just.agentweb.DefaultDownloadImpl.create(DefaultDownloadImpl.java:244)
com.just.agentweb.AgentWebSettingsImpl.setDownloader(AgentWebSettingsImpl.java:44)
com.just.agentweb.AgentWeb.ready(AgentWeb.java:437)
com.just.agentweb.AgentWeb.access$3100(AgentWeb.java:43)
com.just.agentweb.AgentWeb$PreAgentWeb.ready(AgentWeb.java:314)

**Comment by Love667767** [comment]
拉源码手动打个aar，  4.13版本的源码跟 4.13远程版本的代码在 AgentWebSettingsImpl 上有差异。

**Comment by RockRoll666** [comment]
> 拉源码手动打个aar， 4.13版本的源码跟 4.13远程版本的代码在 AgentWebSettingsImpl 上有差异。

查看源码发现是AgentWebSettingsImpl里设置downloader相关逻辑导致的，我没有使用到这些功能，所以改成使用setAgentWebWebSettings方法传参AbsAgentWebSettings的空实现匿名类
