### ISSUE TITLE
请问新版本如何为所有url添加统一的Header

### ISSUE THREAD

**Issue by UltramanTIGA** [Justson/AgentWeb#831]
如题，旧版本的添加Header的方法可以对所有url生效，新版本没有提供了吗？只能指定特定的url添加Header？

**Comment by Justson** [comment]
置顶Host

**Comment by Justson** [comment]
指定Host

**Comment by UltramanTIGA** [comment]
> 指定Host

作者你好，我知道现有方法是指定host，我的意思是如果host不可控的情况下，是否可以通过WebChromeClient或其他方式统一设定Header

**Comment by UltramanTIGA** [comment]
> 指定Host

看了下源码，如果host设为空字符串，是否就可以对所有的路径生效Header
