### ISSUE TITLE
WebChromeClient，WebViewClient新版本使用了自定义的类，导致老版本不兼容

### ISSUE THREAD

**Issue by hongpp** [Justson/AgentWeb#839]
/**
	 * WebChromeClient
	 */
	private WebChromeClient mWebChromeClient;
	private com.just.agentweb.WebChromeClient mWebChromeClient;
	/**
	 * WebViewClient
	 */
	private WebViewClient mWebViewClient;
	private com.just.agentweb.WebViewClient mWebViewClient;

**Comment by Justson** [comment]
是的
