### ISSUE TITLE
加载网页会偶尔出现同一个网页加载异常

### ISSUE THREAD

**Issue by dempsey** [Justson/AgentWeb#844]
agentweb 版本号：4.1.3
debug查看错误信息：
errorCode:-6
description:net::ERR_CONNECTION_RESET
同一个网页会偶尔出现加载失败的情况。
网页是https开头

**Comment by Justson** [comment]
资源是在内核请求的

**Comment by dempsey** [comment]
> 资源是在内核请求的

请问是什么原因导致的？
