### ISSUE TITLE
是否支持调起相机录制视频

### ISSUE THREAD

**Issue by MrZhaoying** [Justson/AgentWeb#852]
起初点击后没有任何反应, 报错提示缺少 implementation 'com.just.agentweb:filechooser:4.1.4, 又在grandle中增加了该库, 点击后有弹窗选择出现,选择文件可以进入手机文件夹, 但选择相机会导致界面卡死无反应, 貌似也没有明确报错;

如果选择重写 onShowFileChooser 和 openFileChooser后,方法并不执行, 并且也不会有上面的弹窗选择出现

**Comment by robinhoo2010** [comment]
同问，如果可以开访问自定义文件上传就好了

**Comment by Justson** [comment]
支持自定义文件上传的
