### ISSUE TITLE
加载assets 的html问题

### ISSUE THREAD

**Issue by jianmo123** [Justson/AgentWeb#856]
加载assets的html之后，  如果html中通过js的location.href跳转assets其他页面时，导致无法跳转
4.1.3版本时还能正常跳转
更新到4.1.4之后就无法跳转了

**Comment by mengmengmeng01** [comment]
请问解决了吗，遇到同样的问题，如果解决了，能告知下吗

**Comment by jianmo123** [comment]
我换回了4.1.3

**Comment by mengmengmeng01** [comment]
4.1.3的全路径能否给下我，我用这个改成4.1.3，一直加载不出来
implementation 'com.github.Justson.AgentWeb:agentweb-core:v4.1.9'
谢谢回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月29日(星期四) 上午10:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Justson/AgentWeb] 加载assets 的html问题 (#856)





 
我换回了4.1.3

**Comment by mengmengmeng01** [comment]
我找到了，替换了，然后还是加载不出来，需要其他的配置吗
  AgentWeb mAgentWeb = AgentWeb.with(this)
                .setAgentWebParent((LinearLayout) linearLayout, new LinearLayout.LayoutParams(-1, -1))
                .useDefaultIndicator()

                .createAgentWeb()
                .ready()
                .go("file:///android_asset/meituan/index.html");




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月29日(星期四) 上午10:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Justson/AgentWeb] 加载assets 的html问题 (#856)





 
我换回了4.1.3

**Comment by jianmo123** [comment]
implementation 'com.just.agentweb:agentweb:4.1.3'

**Comment by jianmo123** [comment]
看来4.1.9还是没解决这个bug  ~~

**Comment by mengmengmeng01** [comment]
谢谢，我找到了，但是还是不行，需要其他的配置吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月29日(星期四) 中午12:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Justson/AgentWeb] 加载assets 的html问题 (#856)





 
implementation 'com.just.agentweb:agentweb:4.1.3'

**Comment by Justson** [comment]
`.interceptUnkownUrl(false)` 加上这个试下

**Comment by mengmengmeng01** [comment]
没有，不知道怎么弄




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月29日(星期四) 中午12:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Justson/AgentWeb] 加载assets 的html问题 (#856)





 
看来4.1.9还是没解决这个bug  ~~

**Comment by mengmengmeng01** [comment]
好的，谢谢，下午试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月29日(星期四) 中午12:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Justson/AgentWeb] 加载assets 的html问题 (#856)





 
.interceptUnkownUrl(false) 加上这个试下

**Comment by mengmengmeng01** [comment]
还是不可以，不过谢谢了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月29日(星期四) 中午12:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Justson/AgentWeb] 加载assets 的html问题 (#856)





 
.interceptUnkownUrl(false) 加上这个试下

**Comment by jianmo123** [comment]
我这里可以了 加上 .isInterceptUnkownUrl(false) 之后   页面内使用location跳转可以了

**Comment by mengmengmeng01** [comment]
我看了下方法，默认好像是false，设置后为true了，没有找到在哪加.isInterceptUnkownUrl(false)&nbsp;这个方法






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月29日(星期四) 中午1:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Justson/AgentWeb] 加载assets 的html问题 (#856)





 
我这里可以了 加上 .isInterceptUnkownUrl(false) 之后   页面内使用location跳转可以了

**Comment by jianmo123** [comment]
我换成4.1.9了  4.1.9有这个方法

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年4月29日 13:57
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Justson/AgentWeb] 加载assets 的html问题 (#856)

我看了下方法，默认好像是false，设置后为true了，没有找到在哪加.isInterceptUnkownUrl(false)&nbsp;这个方法






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;;
发送时间: 2021年4月29日(星期四) 中午1:47
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;; ***@***.***&gt;;
主题: Re: [Justson/AgentWeb] 加载assets 的html问题 (#856)






我这里可以了 加上 .isInterceptUnkownUrl(false) 之后 页面内使用location跳转可以了

―
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.

―

**Comment by sungbu** [comment]
AgentWeb.with(this)
                .setAgentWebParent(ly,new LinearLayout.LayoutParams(-1,-1))
                .useDefaultIndicator()
                .setWebViewClient(new WebViewClient() {
                    @Override
                    public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request) {
                        view.loadUrl(request.getUrl().toString());
                        return true;
                    }
                })
                .createAgentWeb()
                .ready()
                .go("file:///android_asset/community.html");
设置一下WebViewClient试试
