### ISSUE TITLE
网页中点击链接打开pdf，应该怎么做呢

### ISSUE THREAD

**Issue by delecarnegie** [Justson/AgentWeb#86]
我的系统需要再网页中打开PDF并且打印，请问应该如何在webview中显示pdf呢，我不能在第三方app打开PDF。

**Comment by delecarnegie** [comment]
作者能不能给个思路，是不是要自己写一个DefaultDownLoaderImpl

**Comment by Justson** [comment]
`DefaultDownLoaderImpl ` 是负责把文件下载下来 ，然后通过 `DownLoadResultListener` 回调给用户 ， 你可以根据需求 ， 处理文件 。

**Comment by delecarnegie** [comment]
感谢作者，正在拜读源码
