### ISSUE TITLE
老哥，偶尔出现这错误

### ISSUE THREAD

**Issue by AdminQQZ** [Justson/AgentWeb#863]
![Uploading QQ截图20200924145036.png…]()

**Comment by AdminQQZ** [comment]
Using WebView from more than one process at once with the same data directory is not supported

**Comment by AdminQQZ** [comment]
![QQ截图20200924145036](https://user-images.githubusercontent.com/12959954/94110951-f8fa3f80-fe75-11ea-994b-a73b0d8856a3.png)

**Comment by AdminQQZ** [comment]
// agentweb
    api 'com.just.agentweb:agentweb:4.1.3'
    api 'com.just.agentweb:filechooser:4.1.3' 现用的版本

**Comment by Justson** [comment]
[WebView Bug 暂时无解，从官方描述来看，概率应该是很低的](https://bugs.chromium.org/p/chromium/issues/detail?id=558377#c126)
