### ISSUE TITLE
设置无网界面

### ISSUE THREAD

**Issue by kangdawei** [Justson/AgentWeb#865]
.setMainFrameErrorView(R.layout.agentweb_error_page, R.id.ivRefresh)
有网的时候点击刷新没有隐藏该界面

**Comment by lianghao777** [comment]
+1

**Comment by lianghao777** [comment]
用自带的ErrorView可以

**Comment by lianghao777** [comment]
问题依然存在

**Comment by lhcteam** [comment]
super.onPageStarted(view,url,favicon);  查看一下是否没有加上这一句
