### ISSUE TITLE
5.1.1版本上自己闪退，找不到资源id

### ISSUE THREAD

**Issue by zhanghangyes** [Justson/AgentWeb#867]
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x2040003

**Comment by zhanghangyes** [comment]
com.just.agentweb.AgentWeb$CommonBuilder.createAgentWeb(AgentWeb.java:706)

**Comment by litliang** [comment]
> agentweb version?

4.1.3
1.0.3 both
