### ISSUE TITLE
的确高版本兼容性有问题，显示空白

### ISSUE THREAD

**Issue by acjf** [Justson/AgentWeb#87]
首先，感觉作者，这问题，今天略查看了下，最早发现的人提出的Issues是在上个月，到现在作者仍没有提出相关的信息。
再次感谢作者的封装，如果我发现问题所在我会在此提出，不过毕竟没有友好的log日志输出，不一定能查到问题所在。

**Comment by acjf** [comment]
//适配5.0不允许http和https混合使用情况
```
 if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
      mWebSettings.setMixedContentMode(android.webkit.WebSettings.MIXED_CONTENT_ALWAYS_ALLOW);
}
```
1、作者在WebDefaultSettingsManager中写有，正常情况下是不会空白，空白的情况是当https是非正规的协议,浏览器显示不安全，或者证书错误，极可能显示空白。

2、一开始没细看源码，LoaderImpl这里直接调用web.loadurl
 ```
       if (mHttpHeaders==null|| mHttpHeaders.isEmptyHeaders())
            this.mWebView.loadUrl(url);
        else {
            this.mWebView.loadUrl(url, mHttpHeaders.getHeaders());
        }
```
因为WebView请求连接需要完整的协议，所以：链接如：www.***.com 、***.com 或者不支持https协议的 https://***这种链接都会显示空白 。

**Comment by Sabirjan** [comment]
自签名的https 网址  很多情况下出现空白页面

**Comment by Justson** [comment]
@acjf 说的很正确 WebView 请求链接需要完整协议 。

**Comment by hegaojian** [comment]
我写了兼容处理，为什么再华为荣耀10上面还是显示空白
