### ISSUE TITLE
Android高版本webview加载本地网页无法相互跳转？

### ISSUE THREAD

**Issue by JaneYork** [Justson/AgentWeb#874]
描述问题
android7和9，asset目录下有两个网页a.html，b.html,点击a.html里的一个按钮location.href="b.html"。现在webview.loadurl("a.html")可以正常显示，但是在点击按钮时，无法跳转b.html。Android5里可以跳转。，

报错信息
android.os.FileUriExposedException: file:///android_asset/js_interaction/hello_bak.html exposed beyond app through Intent.getData()
尝试使用file provider解决，但是没有效果

**Comment by mengmengmeng01** [comment]
请问解决了吗，同样的问题，不知道怎么解决，希望能告知下
