### ISSUE TITLE
html地址,加载不出来

### ISSUE THREAD

**Issue by duolanmeng** [Justson/AgentWeb#876]
AgentWebConfig.debug();
        mAgentWeb = AgentWeb.with(this)
                .setAgentWebParent(binding.container, new LinearLayout.LayoutParams(-1, -1))
                .useDefaultIndicator()
                .createAgentWeb()
                .ready()
                .go("http://lqerp.f3322.net:2021/login.html");

这个地址,加载后是空白的.但是把地址换成 http:baidu.com 就可以了. 不知道这个地址有什么问题? 在web端这个地址没有问题

**Comment by duolanmeng** [comment]
想问下,对访问的url有什么要求吗?

**Comment by zhaozihan** [comment]
检查看是不是你的targetSdkVersion>27，9.0会有http无法访问网络的问题。
