### ISSUE TITLE
关于X请求的关闭或修改问题

### ISSUE THREAD

**Issue by farendaibiao** [Justson/AgentWeb#879]
WebView内核在请求Ajax等的时候，就强制加上X-Requested-With，请问有办法改变value或者消去吗
前面有位老兄问过没有人回复，这里再问一次
https://github.com/Justson/AgentWeb/issues/755

**Comment by Justson** [comment]
自己写个代理?

**Comment by farendaibiao** [comment]
> 自己写个代理?

给代理的话，手机如果开了其他软件代理，端口会有冲突，我想问一下WebView的Ajax的X-Requested-With，这一类的强制性增加可否去掉，不利于匿名访问
