### ISSUE TITLE
Android11 打开相册选择图片返回后无法显示。

### ISSUE THREAD

**Issue by fddlpz** [Justson/AgentWeb#883]
Android11 打开相册选择图片返回后无法显示。拍照没有问题
 报错：
E/DatabaseUtils: Writing exception to parcel
    java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaDocumentsProvider uri content://com.android.providers.media.documents/document/image%3A35 from pid=25351, uid=10155 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs

现使用代码：

	private Intent getFileChooserIntent() {
		Intent mIntent = null;
		if (mIsAboveLollipop && mFileChooserParams != null && (mIntent = mFileChooserParams.createIntent()) != null) {
			if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT && mIntent.getAction().equals(Intent.ACTION_GET_CONTENT)) {
				mIntent.setAction(Intent.ACTION_OPEN_DOCUMENT);
			}
			return mIntent;
		}

		Intent i = new Intent();
		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
			i.setAction(Intent.ACTION_OPEN_DOCUMENT);
		} else {
			i.setAction(Intent.ACTION_GET_CONTENT);
		}
		i.addCategory(Intent.CATEGORY_OPENABLE);
		if (TextUtils.isEmpty(this.mAcceptType)) {
			i.setType("*/*");
		} else {
			i.setType(this.mAcceptType);
		}
		i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
		return mIntent = Intent.createChooser(i, "");
	}

**Comment by mengsr** [comment]
解决了么？

**Comment by mengsr** [comment]
rivate Uri[] processData(Intent data) {
Uri[] datas = null;
if (data == null) {
return datas;
}
String target = data.getDataString();
if (!TextUtils.isEmpty(target)) {
String[] path = AgentWebUtils.uriToPath(mActivity, new Uri[]{Uri.parse(target)});
datas = new Uri[path.length];
File file;
for (int i = 0; i < path.length; i++) {
file = new File(path[i]);
datas[i] = Uri.fromFile(file);
}
return datas;
}
ClipData mClipData = data.getClipData();
if (mClipData != null && mClipData.getItemCount() > 0) {
datas = new Uri[mClipData.getItemCount()];
for (int i = 0; i < mClipData.getItemCount(); i++) {

            ClipData.Item mItem = mClipData.getItemAt(i);
            datas[i] = mItem.getUri();

        }
    }
    return datas;
}

**Comment by timenoenough** [comment]
> rivate Uri[] processData(Intent data) {
> Uri[] datas = null;
> if (data == null) {
> return datas;
> }
> String target = data.getDataString();
> if (!TextUtils.isEmpty(target)) {
> String[] path = AgentWebUtils.uriToPath(mActivity, new Uri[]{Uri.parse(target)});
> datas = new Uri[path.length];
> File file;
> for (int i = 0; i < path.length; i++) {
> file = new File(path[i]);
> datas[i] = Uri.fromFile(file);
> }
> return datas;
> }
> ClipData mClipData = data.getClipData();
> if (mClipData != null && mClipData.getItemCount() > 0) {
> datas = new Uri[mClipData.getItemCount()];
> for (int i = 0; i < mClipData.getItemCount(); i++) {
> 
> ```
>         ClipData.Item mItem = mClipData.getItemAt(i);
>         datas[i] = mItem.getUri();
> 
>     }
> }
> return datas;
> ```
> 
> }

这方法怎么用啊

**Comment by VectorWen** [comment]
解决了吗

**Comment by mengsr** [comment]
&nbsp;解决了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Justson/AgentWeb"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月26日(星期二) 下午4:43
收件人:&nbsp;"Justson/AgentWeb"<AgentWeb@noreply.github.com&gt;;
抄送:&nbsp;"在路上"<953512062@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Justson/AgentWeb] Android11 打开相册选择图片返回后无法显示。 (#883)





 
解决了吗

**Comment by Aaroneee** [comment]
> Android11 打开相册选择图片返回后无法显示。拍照没有问题
> 报错：
> E/DatabaseUtils: Writing exception to parcel
> java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaDocumentsProvider uri content://com.android.providers.media.documents/document/image%3A35 from pid=25351, uid=10155 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
> 
> 现使用代码：
> 
> ```
> private Intent getFileChooserIntent() {
> 	Intent mIntent = null;
> 	if (mIsAboveLollipop && mFileChooserParams != null && (mIntent = mFileChooserParams.createIntent()) != null) {
> 		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT && mIntent.getAction().equals(Intent.ACTION_GET_CONTENT)) {
> 			mIntent.setAction(Intent.ACTION_OPEN_DOCUMENT);
> 		}
> 		return mIntent;
> 	}
> 
> 	Intent i = new Intent();
> 	if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
> 		i.setAction(Intent.ACTION_OPEN_DOCUMENT);
> 	} else {
> 		i.setAction(Intent.ACTION_GET_CONTENT);
> 	}
> 	i.addCategory(Intent.CATEGORY_OPENABLE);
> 	if (TextUtils.isEmpty(this.mAcceptType)) {
> 		i.setType("*/*");
> 	} else {
> 		i.setType(this.mAcceptType);
> 	}
> 	i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
> 	return mIntent = Intent.createChooser(i, "");
> }
> ```

老哥,这个问题解决了吗?怎么解决的

**Comment by XuRan-Zhao-lucky** [comment]
解决了吗

**Comment by Aaroneee** [comment]
> 解决了吗

更新版本后就可以了
