### ISSUE TITLE
下载完文件，会自动弹出安装，如何禁止呢

### ISSUE THREAD

**Issue by 137303553322** [Justson/AgentWeb#884]

**Comment by xiexin52k** [comment]
两种解决方法:
1.  在构建ResourceRequest时不要调用autoOpenXXX函数.
2. 在```DownloadListener#boolean onResult(Throwable throwable, Uri path, String url, Extra extra);```方法中, 返回"true"进行拦截.表示"我已经把这个结果处理完了, 不需要框架再继续处理"
