### ISSUE TITLE
混淆报错

### ISSUE THREAD

**Issue by xiaoe1314** [Justson/AgentWeb#888]
@SpenceAcc @liyujiang-gzu @Justson @desfate 

===========================下面是我写的代码=========================
 buildTypes {
        debug {
            buildConfigField("boolean", "LOG_DEBUG", "true")
            zipAlignEnabled true     //Zipalign优化
            shrinkResources true    // 移除无用的resource文件
            minifyEnabled true     //混淆
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            buildConfigField("boolean", "LOG_DEBUG", "false")
            zipAlignEnabled true     //Zipalign优化
            shrinkResources true    // 移除无用的resource文件
            minifyEnabled true     //混淆
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

------------------------这里是依赖

//AgentWeb 是一个基于的 Android WebView ，极度容易使用以及功能强大的库
    //https://github.com/Justson/AgentWeb
    implementation 'com.just.agentweb:agentweb-androidx:4.1.4' // (必选)

------------------------这里是混淆
-keep class com.just.agentweb.** {
    *;
}
-dontwarn com.just.agentweb.**

-keep class com.alipay.android.app.IAlixPay{*;}
-keep class com.alipay.android.app.IAlixPay$Stub{*;}
-keep class com.alipay.android.app.IRemoteServiceCallback{*;}
-keep class com.alipay.android.app.IRemoteServiceCallback$Stub{*;}
-keep class com.alipay.sdk.app.PayTask{ public *;}
-keep class com.alipay.sdk.app.AuthTask{ public *;}
-keep class com.alipay.sdk.app.H5PayCallback {
    <fields>;
    <methods>;
}
-keep class com.alipay.android.phone.mrpc.core.** { *; }
-keep class com.alipay.apmobilesecuritysdk.** { *; }
-keep class com.alipay.mobile.framework.service.annotation.** { *; }
-keep class com.alipay.mobilesecuritysdk.face.** { *; }
-keep class com.alipay.tscenter.biz.rpc.** { *; }
-keep class org.json.alipay.** { *; }
-keep class com.alipay.tscenter.** { *; }
-keep class com.ta.utdid2.** { *;}
-keep class com.ut.device.** { *;}

===========================下面是我混淆后的报错=========================

> Task :app:minifyReleaseWithR8
AGPBI: {"kind":"warning","text":"Missing class: com.alipay.sdk.app.H5PayCallback","sources":[{}],"tool":"R8"}
AGPBI: {"kind":"warning","text":"Missing class: com.download.library.DownloadListenerAdapter","sources":[{}],"tool":"R8"}

**Comment by liyujiang-gzu** [comment]
是AgentWeb可选的依赖的支付宝SDK和下载库混淆报错了，可以试试：
```groovy
-dontwarn com.alipay.sdk.app.*
-dontwarn com.download.library.*
```

**Comment by xiaoe1314** [comment]
可以了，谢谢
