### ISSUE TITLE
建议加入webview页面左右切换动画

### ISSUE THREAD

**Issue by hellolixy** [Justson/AgentWeb#892]
尝试在agentweb中使用https://www.jianshu.com/p/b7f44ba49270 提供的方法来实现动画效果，有bug，前后页面切换时概率性显示混乱。

试了使用最简单的webview没有问题。

**Comment by Justson** [comment]
看了下你提供的例子，动画流畅优化是在WebView层面覆盖一个ImageView 通过截图来实现， 这个优化不太可能放在SDK 内部去做，完全可以根据AgentWeb 提供的API来实现
