### ISSUE TITLE
打开图片链接没法自适应

### ISSUE THREAD

**Issue by ollie100** [Justson/AgentWeb#893]
agentweb 去打开一个图片链接，不同手机显示的是尺寸不一样的，有没有可以打开自适应手机尺寸的方法？

**Comment by kyumin213** [comment]
.setAgentWebWebSettings(new AbsAgentWebSettings() {
                                            @Override
                                            protected void bindAgentWebSupport(AgentWeb agentWeb) {
                                            }

                                            @Override
                                            public IAgentWebSettings toSetting(WebView webView) {
                                                IAgentWebSettings iAgentWebSettings = super.toSetting(webView);
                                                iAgentWebSettings.getWebSettings().setUseWideViewPort(true); //将图片调整到适合webview的大小
                                                iAgentWebSettings.getWebSettings().setLoadWithOverviewMode(true); // 缩放至屏幕的大小
                                                iAgentWebSettings.getWebSettings().setCacheMode(WebSettings.LOAD_NO_CACHE);
                                                return iAgentWebSettings;
                                            }
                                        })

**Comment by kyumin213** [comment]
.setAgentWebWebSettings(new AbsAgentWebSettings() {
                                            @Override
                                            protected void bindAgentWebSupport(AgentWeb agentWeb) {
                                            }

                                            @Override
                                            public IAgentWebSettings toSetting(WebView webView) {
                                                IAgentWebSettings iAgentWebSettings = super.toSetting(webView);
                                                iAgentWebSettings.getWebSettings().setUseWideViewPort(true); //将图片调整到适合webview的大小
                                                iAgentWebSettings.getWebSettings().setLoadWithOverviewMode(true); // 缩放至屏幕的大小
                                                iAgentWebSettings.getWebSettings().setCacheMode(WebSettings.LOAD_NO_CACHE);
                                                return iAgentWebSettings;
                                            }
                                        })
