### ISSUE TITLE
js 调用java

### ISSUE THREAD

**Issue by w2282346548** [Justson/AgentWeb#9]
我看到代码中，java 调用js，可以使用quickCallJs();那么 js 调用java，需要在那里做设置呢

**Comment by Justson** [comment]
```
//Android 端
mAgentWeb.getJsInterfaceHolder().addJavaObject("android",new AndroidInterface(mAgentWeb,this.getActivity()));
```

在 Js 里就能通过 `window.android.callAndroid()` 调用 Java 层的 AndroidInterface 类里 callAndroid 方法

**Comment by wonxll** [comment]
最后是怎么回事啊？我的也是这样，没有用，提示Undifined
