### ISSUE TITLE
有没有遇见过玄学类似问题（状态栏一直闪）

### ISSUE THREAD

**Issue by stytooldex** [Justson/AgentWeb#900]
✌(̿▀̿ ̿Ĺ̯̿̿▀̿ ̿)✌

**Comment by ttdazi** [comment]
我也遇到了，我们应用没有申请定位权限，web页面中不断的去定位申请权限，就会不断的回调onGeolocationPermissionsShowPrompt方法，最终走到了DefaultChromeClient中的onGeolocationPermissionsShowPromptInternal这个方法，一直去调起ActionActivity去请求权限。权限还没有通过，activity不断切换，导致状态栏闪烁。目前解决方案是：重写，
    private val mWebChromeClient = object : com.just.agentweb.WebChromeClient() {
        var isGeolocationPermissionsRquest:Boolean=false;
        override fun onProgressChanged(view: WebView, newProgress: Int) {
        }

        override fun onReceivedTitle(view: WebView?, title: String?) {
            super.onReceivedTitle(view, title)
            if (mWebTitle != null) {
                mWebTitle!!.title = title
            }
        }
     //解决问题位置。
        override fun onGeolocationPermissionsShowPrompt(origin: String?, callback: GeolocationPermissions.Callback?) {
            Log.i("ExDownload", "ExDownload------- onGeolocationPermissionsShowPrompt----- ${isRquest}")
            if(!isGeolocationPermissionsRquest) {
                isGeolocationPermissionsRquest=true
                super.onGeolocationPermissionsShowPrompt(origin, callback)
            }
        }
    }
使用上面的mWebChromeClient 。

**Comment by ztind** [comment]
何爲玄学？

**Comment by wangshuohulala** [comment]
直接重写   onGeolocationPermissionsShowPrompt  不要调super就可以了

**Comment by ppg408331701** [comment]
我这边是调用
  override fun onGeolocationPermissionsShowPrompt(origin: String?, callback: GeolocationPermissions.Callback?) {
              callback?.invoke(origin, true, false)
              super.onGeolocationPermissionsShowPrompt(origin, callback)
          }

否则会一直闪，原因是agentweb一直没有返回定位结果给网页，导致网页重复发起吧
