### ISSUE TITLE
红米 A6 webview退出activity页面后要重新登录

### ISSUE THREAD

**Issue by llh2010** [Justson/AgentWeb#905]
用的AgentWeb版本是 4.1.4
手机红米 A6， 安卓8.1系统。

打开一个activity页，agentweb加载url登录，退出这个activity后（执行了activity的onDestroy），再点击打开这个activity后，页面还是要重新登录。

已经在onDestory里保存了cookies，在再次打开的时候AgentWebConfig.syncCookie保存的cookies。但还是失败，尽力交瘁，望解答。多谢

**Comment by cocowobo** [comment]
作者只管关闭，也不解答下吗
