### ISSUE TITLE
mAgentWeb.getWebCreator().getWebView().setOverScrollMode(View.OVER_SCROLL_NEVER); 无效

### ISSUE THREAD

**Issue by sophiemarceau** [Justson/AgentWeb#907]
不想有这种拖拽回弹 如何禁止 如题的设置无效 请教 怎么设置能有效禁止？ 烦请解答 谢谢了

**Comment by Justson** [comment]
下拉回弹不是这个library提供的功能

**Comment by sophiemarceau** [comment]
如何弄 才能禁止滑动到头 还能拖拽的问题呢？ 这个问题能否指点一下？

**Comment by Justson** [comment]
贴下代码?

**Comment by yuhuazhu** [comment]
> 不想有这种拖拽回弹 如何禁止 如题的设置无效 请教 怎么设置能有效禁止？ 烦请解答 谢谢了

按你的那样设置，有效果呀，设置完就没有那个波纹了
