### ISSUE TITLE
mAgentWeb打开开放平台支付宝人脸时无法正常调起

### ISSUE THREAD

**Issue by l5416211** [Justson/AgentWeb#910]
使用了 
    @Override
    protected void onPause() {
        mAgentWeb.getWebLifeCycle().onPause();
        super.onPause();

    }
后在mAgentWeb容器中打开支付宝人脸识别SDK的服务就无法正常拉起 
https://opendocs.alipay.com/open/20181012100420932508/00zc1e这个版本的支付宝

**Comment by l5416211** [comment]
@Justson 找到原因了mAgentWeb.getWebLifeCycle().onPause();停用了所有web的JS 支付宝开放平台的这个版本会用到webview调起人脸的时候JS阻塞   您这边考虑下是不是能改为只停用这一个的不要全局停用JS 排查了好久还找了支付宝的同学才定位到

**Comment by Justson** [comment]
看一下注意事项
