### ISSUE TITLE
跳转第三方app设置scheme的问题

### ISSUE THREAD

**Issue by xiaolongbao22333** [Justson/AgentWeb#917]
<a href="abc://abcd">打开app</a>
自己设置的scheme，
通过debug调试后发现在DefaultWebClient中的shouldOverrideUrlLoading下的代码
 if (handleCommonLink(url)) {
            return true;
        }
在handleCommonLink这个方法中不符合if (url.startsWith(WebView.SCHEME_TEL)
                || url.startsWith(SCHEME_SMS)
                || url.startsWith(WebView.SCHEME_MAILTO)
                || url.startsWith(WebView.SCHEME_GEO)) {}这四种所以直接return false了
也就无法继续了

**Comment by Justson** [comment]
看下Sample哈 , 不太看得懂你上面的逻辑
