### ISSUE TITLE
TrichromeLibrary.apk /product/app/TrichromeLibrary/TrichromeLibrary.apk

### ISSUE THREAD

**Issue by mengsr** [Justson/AgentWeb#918]
TrichromeLibrary.apk
/product/app/TrichromeLibrary/TrichromeLibrary.apk
友盟统计后台出现好多这个错误，之前的老版本还没发现，升级过4.1.9出现好多，不知道跟这个版本有关系没

**Comment by twufive** [comment]
@mengsr @Justson 请问这个问题后面解决了吗
