### ISSUE TITLE
请尽快把DownloadImpl这个类删了，GooglePlay上架直接被封

### ISSUE THREAD

**Issue by pichsy** [Justson/AgentWeb#920]
想用的让用户自定义，实现类写到App里，别搞到框架里，downloader本来就抽离了，这里还残留着，实在是坑

**Comment by prczhb** [comment]
应用昨天被封了,说是其中含有未知来源或安装应用的代码. 翻来翻去,也就是这个的问题了
😭😭😭😭😭😭

**Comment by Justson** [comment]
```
 implementation 'com.github.Justson:Downloader:v4.2.0' 
or
 implementation 'com.github.Justson:Downloader:v4.2.0-androidx'
```

**Comment by VliceZ** [comment]
@pichsy 老哥 我遇到同样的问题了，能够加下你的联系方式请教下？

**Comment by pichsy** [comment]
> @pichsy 老哥 我遇到同样的问题了，能够加下你的联系方式请教下？

我的问题还没解决呢，申诉google没反应。O疼........

**Comment by pichsy** [comment]
> ```
>  implementation 'com.github.Justson:Downloader:v4.2.0' 
> or
>  implementation 'com.github.Justson:Downloader:v4.2.0-androidx'
> ```

好的，感谢，我试试

**Comment by VliceZ** [comment]
@pichsy 我打算直接移除这个库了，不敢再冒这个风险。

**Comment by pichsy** [comment]
> @pichsy 我打算直接移除这个库了，不敢再冒这个风险。

Downloader肯定要删掉，agentweb，我打算留着，这块业务渗透太多，移不掉。

**Comment by pichsy** [comment]
> @pichsy 我打算直接移除这个库了，不敢再冒这个风险。

我把源码下载下来自己改了，删了Downloader相关的类个代码，重新上传公司maven自己用了。

**Comment by pichsy** [comment]
> ```
>  implementation 'com.github.Justson:Downloader:v4.2.0' 
> or
>  implementation 'com.github.Justson:Downloader:v4.2.0-androidx'
> ```

猛一看以为你把Agentweb升级了，看错了，这个库Google是禁用的，检测类名直接下架，你需要吧Agentweb lib库中使用此库相关的代码删除一下，出个fix版本也行，默认下载器实现类写到app demo中可以吧。

**Comment by Justson** [comment]
Google 这个操作太流氓了，DownloadImpl+ Downloader 下载文件而apk只是文件的一种的，Downloader 作为整个agentweb library的一部分， 许多用户用途下载doc、pdf 等其他文件格式的文件，安装应用权限已从Downloader 这个library中剔除

**Comment by VliceZ** [comment]
我看你们的提问都是3天前，我们的应用也是大概3天前被封的。应用上线一年没问题，这几天才被下架，结合你们的情况，我怀疑这一波是一次整顿运动。这一次过了后面估计问题不大。

**Comment by Justson** [comment]
> Your app contains content that doesn’t comply with the Device and Network Abuse policy. We found your app is using a non-compliant version of Loan Download SDK which contains code to download or install applications from unknown sources outside of Google Play.

**Comment by Justson** [comment]
> Your app contains content that doesn’t comply with the Device and Network Abuse policy. We found your app is using a non-compliant version of Loan Download SDK which contains code to download or install applications from unknown sources outside of Google Play.

重点应该是`install applications from unknown sources`   影响到Google Play的垄断收入了， Google 在作恶。

**Comment by Justson** [comment]
Downloader 默认应该是会被混淆的

**Comment by pichsy** [comment]
> Downloader 默认应该是会被混淆的

没有被混淆，google他检测 import   com.download.xxxx  相关的类。没法了，只能删了

**Comment by pichsy** [comment]
// 全局移除部分黑名单权限
project.afterEvaluate {
    project.android.applicationVariants.all { variant ->
        variant.outputs.each { output ->
            output.processResources.doFirst { pm ->
                String manifestPath = output.processResources.manifestFile
                def manifestContent = file(manifestPath).getText()
                manifestContent = manifestContent.replace('android.permission.REQUEST_INSTALL_PACKAGES', 'android.permission.INTERNET')
                manifestContent = manifestContent.replace('android.permission.ACCESS_BACKGROUND_LOCATION', 'android.permission.INTERNET')
                manifestContent = manifestContent.replace('android.permission.ACCESS_FINE_LOCATION', 'android.permission.INTERNET')
                manifestContent = manifestContent.replace('android.permission.ACCESS_COARSE_LOCATION', 'android.permission.INTERNET')
                manifestContent = manifestContent.replace('android.permission.ACCESS_MOCK_LOCATION', 'android.permission.INTERNET')
                manifestContent = manifestContent.replace('android.permission.MOUNT_UNMOUNT_FILESYSTEMS', 'android.permission.INTERNET')
                manifestContent = manifestContent.replace('android.permission.READ_LOGS', 'android.permission.INTERNET')
                file(manifestPath).write(manifestContent)
            }
        }
    }
}

**Comment by yj970** [comment]
我使用的是4.1.4的版本，前几天也被谷歌封停了。
```
 api 'com.just.agentweb:agentweb-androidx:4.1.4' 
 api 'com.download.library:downloader-androidx:4.1.4'
```

目前是删除了downloader，保留了agentweb，重新发上去审核了，现在等待结果 TvT

**Comment by PandanKill** [comment]
> 我使用的是4.1.4的版本，前几天也被谷歌封停了。
> 
> ```
>  api 'com.just.agentweb:agentweb-androidx:4.1.4' 
>  api 'com.download.library:downloader-androidx:4.1.4'
> ```
> 
> 目前是删除了downloader，保留了agentweb，重新发上去审核了，现在等待结果 TvT

hello，保留agentweb，重新审核，结果怎样

**Comment by yj970** [comment]
> > 我使用的是4.1.4的版本，前几天也被谷歌封停了。
> > ```
> >  api 'com.just.agentweb:agentweb-androidx:4.1.4' 
> >  api 'com.download.library:downloader-androidx:4.1.4'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 目前是删除了downloader，保留了agentweb，重新发上去审核了，现在等待结果 TvT
> 
> hello，保留agentweb，重新审核，结果怎样

审核通过了。但因为app内webview功能较弱，为了保险起见我替换成原生的webview，又上架了一个版本。
