### ISSUE TITLE
你好，请问有兴趣了解一下字节跳动的工作机会吗？

### ISSUE THREAD

**Issue by linisme** [Justson/AgentWeb#924]
Hi，我这边是字节跳动深圳这边做Android基础相关的，请问有兴趣了解一下这边的工作机会吗？主要工作内容是底层技术相关的～

**Comment by moten07** [comment]
> Hi，我这边是字节跳动深圳这边做Android基础相关的，请问有兴趣了解一下这边的工作机会吗？主要工作内容是底层技术相关的～

你好，会删库的要吗
