### ISSUE TITLE
请问，怎么打开autoPlay的开关，使得页面加载后与用户无交互视频可以自动播放

### ISSUE THREAD

**Issue by xinjiyier** [Justson/AgentWeb#929]
因为我需要在广告机上播放，没有办法进行人机交互。火狐浏览器有开关可以打开
![图片](https://user-images.githubusercontent.com/18064887/125714447-1938b7ea-16aa-4f28-8fef-430063f6b466.png)
google 浏览器没有找到开关。
edge 浏览器默认就能自动播放，支持无交互下的autoplay。
![图片](https://user-images.githubusercontent.com/18064887/125714565-2cc19d47-e5ec-4dff-b0bd-bb1fc172ad62.png)

请问有办法解决么？期待您的回复，非常感谢。

**Comment by Justson** [comment]
注入js去处理
