### ISSUE TITLE
FileChooser.getFileChooserIntent 方法逻辑

### ISSUE THREAD

**Issue by sunbeams001** [Justson/AgentWeb#936]
当网页表单的 input 的 accepts 属性类似 ```accept="image/png,image/jpeg,image/gif"``` 时，通过 `mFileChooserParams.createIntent()` 返回的 intent 的 mType 生成不完全，会丢失信息（本例会只保留"image/png"），导致后续选择文件时，一些类型被屏蔽

**Comment by sunbeams001** [comment]
@Justson 所以这是我使用有问题还是feature不打算修？

**Comment by Justson** [comment]
下个版本支持

**Comment by sunbeams001** [comment]
好，谢谢修复
