### ISSUE TITLE
simple无法点击。如图

### ISSUE THREAD

**Issue by yecaler** [Justson/AgentWeb#944]
![图片](https://user-images.githubusercontent.com/25024969/140603057-fbce4ccf-edbd-433e-bb12-5e20ad1da7b5.png)

**Comment by yecaler** [comment]
@SpenceAcc @liyujiang-gzu @Justson @desfate 
大佬抽时间搞一下。辛苦了！

**Comment by Justson** [comment]
https://github.com/Justson/AgentWeb
