### ISSUE TITLE
最新版本4.1.9,在Android 4.4的机器上,加载网页,提示"ReferenceError: Promise is not defined"

### ISSUE THREAD

**Issue by Yangwenhua44** [Justson/AgentWeb#950]
这是网页:https://app.kuhuace.com/player/index.html?id=929836142306525184,安卓4.4原生的webview,不支持es6的语法,我可以理解,但是我使用咱们的框架,为什么同样的问题??

**Comment by Justson** [comment]
语法问题不是该库范围
