### ISSUE TITLE
The dependency for v5.0.0-alpha. 1-AndroidX is in the support package

### ISSUE THREAD

**Issue by huanghaobiu** [Justson/AgentWeb#956]
The dependency for v5.0.0-alpha. 1-AndroidX is in the support package
Fragment is from v4 , build failed

**Comment by kongnanlive** [comment]
不如放弃AndroidX分支，反正Android Studio IDE会帮助编译切换至AndroidX，省的你维护两个分支，合并来合并去的。


或者放弃v4，没有支持AndroidX可以使用老版本。

**Comment by xiexindev** [comment]
AndroidX都推出来好几年了. 没必要再维护Support了. 现在还在用Support的, 大概率也是老旧项目, 也不会有事没事去更新依赖了
