### ISSUE TITLE
老哥，我发现个问题，在快速打开关闭web页面的activity时候，刚打开然后紧接着滑动或者执行啥别的操作，会重启app，偶尔出现，好不容易有一个错误信息，也不知道是不是这个😂

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [Justson/AgentWeb#973]
E/chromium: [ERROR:aw_browser_terminator.cc(149)] Renderer process (31969) crash detected (code 11).
A/chromium: [FATAL:crashpad_client_linux.cc(670)] Render process (31969)'s crash wasn't handled by all associated  webviews, triggering application crash.
A/libc: Fatal signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0xc545f13a in tid 20567 (mple.wanandroid), pid 20567 (mple.wanandroid)

**Comment by AyakaAgo** [comment]
需要为 AgentWebView 设置 [WebViewClient#onRenderProcessGone](https://developer.android.google.cn/reference/android/webkit/WebViewClient?hl=en#onRenderProcessGone(android.webkit.WebView,%20android.webkit.RenderProcessGoneDetail)) 

返回 true 来表示你处理了此渲染进程崩溃，否则，默认实现将让应用崩溃

**Comment by SaltedFish-Extreme** [comment]
> 返回 true 来表示你处理了此渲染进程崩溃，否则，默认实现将让应用崩溃

哇，将近半年前的问题了，一直没解决，感谢老哥的解答了😘
