### ISSUE TITLE
国际化的问题

### ISSUE THREAD

**Issue by guagua22** [Justson/AgentWeb#982]
请问app做国际化适配时,进入AgentWeb后会自动切换成默认语言,也就是设置的地区语言会失效 要怎么解决呢?

**Comment by LXLYHM** [comment]
语言跟AgentWeb没关系吧，你们前端要自己去获取你传过去的语言或者系统语言吧

**Comment by LXLYHM** [comment]
您好，我是李晓玲，邮件已查收，会尽快给您回复。谢谢！
