### ISSUE TITLE
mPermissionInterceptor  返回false 可能会导致那些请求地理位置的web 页面死循环而导致卡死

### ISSUE THREAD

**Issue by woshiwzy** [Justson/AgentWeb#987]
protected PermissionInterceptor mPermissionInterceptor = new PermissionInterceptor() {

        /**
         * PermissionInterceptor 能达到 url1 允许授权， url2 拒绝授权的效果。
         * @param url
         * @param permissions
         * @param action
         * @return true 该Url对应页面请求权限进行拦截 ，false 表示不拦截。
         */
        @Override
        public boolean intercept(String url, String[] permissions, String action) {
            Log.i(TAG, "2mUrl:" + url + "  permission:" + mGson.toJson(permissions) + " action:" + action);
            return true;//如果是false 可能导致死循环，导致网页卡死无法点击
        }
    };

**Comment by ByteRax** [comment]
+1
比如打开滴滴

**Comment by woshiwzy** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by woshiwzy** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
