### ISSUE TITLE
加了mAgentWeb.getJsInterfaceHolder().addJavaObject 页面显示空白，无法正常显示

### ISSUE THREAD

**Issue by zivxia** [Justson/AgentWeb#989]
为什么加了mAgentWeb.getJsInterfaceHolder().addJavaObject 页面显示空白，无法正常显示

**Comment by zhugefubin** [comment]
我也遇到了,又换回webivew自带的了
`
mAgentWeb.webCreator.webView.addJavascriptInterface(JSObject,"objectName")
`

还不行的话 检查一下是不是调用错了生命周期回调

`
   mAgentWeb?.webLifeCycle?.onResume()
`
